"""Scripted policy that moves one arm in a straight joint-space line, then holds.

Code generated by Claude

Used by experiments/branch_jump_demo.py to drive the solver toward arm
configurations that do not round-trip (see experiments/safety_filter_roundtrip.py
with --spread 0): near joint limits the solver can return a different valid
arm solution than the one it was given.
"""

import numpy as np
from src.actuator_mapping import ACTUATOR_NAMES, NAME_TO_IDX

# The solver's default arm pose (geo_kin RetargetSession.default_q): elbow bent 90 degrees.
SOLVER_DEFAULT_Q = np.array([0.0, 0.0, 0.0, 1.5708, 0.0, 0.0, 0.0])

# "Reach forward at shoulder height" (the pose from experiments/elbow_snap_sweep.py),
# with the wrist set that gave the large snap for that arm (left: wristB,
# right: wristA). Joint order 1..7. `target` is the full reach (joint 4 = 0);
# `start` is a natural pose: elbow bent 90 degrees, upper arm slightly forward,
# hand in front of the body at about chest height. Joints 1-3 of the right arm are the
# left arm's mirrored (-j1, -j2, -j3; checked: identical points reflected in y).
REACH_FORWARD = {
    "left": dict(
        start=[-0.45, 0.0039, 0.0, 1.5708, -0.6, -0.4, -0.9],
        target=[-1.4707, 0.0039, 0.0, 0.0, -0.6, -0.4, -0.9]),
    "right": dict(
        start=[0.45, -0.0039, 0.0, 1.5708, 0.5, 0.4, 0.8],
        target=[1.4707, -0.0039, 0.0, 0.0, 0.5, 0.4, 0.8]),
}


class BranchJumpPolicy:
    """Moves one arm linearly in joint space from `start` to `target`.

    q(t) = start + (target - start) * s(clip(t / duration, 0, 1))

    s(u) = u for profile "linear" (constant joint velocity), or the minimum-jerk
    curve 10u^3 - 15u^4 + 6u^5 for profile "smooth" (zero velocity and
    acceleration at both ends). After `duration` seconds the arm holds. Same
    interface as the other policies: call it with (state, t) and get a
    20-element action indexed like src.actuator_mapping.ACTUATOR_NAMES. Only
    the moving arm's seven joints are set; every other entry is 0.
    """

    def __init__(self, arm, target, start=None, duration=5.0, profile="linear"):
        if arm not in ("left", "right"):
            raise ValueError("arm must be 'left' or 'right'")
        self.arm = arm
        self.target = np.asarray(target, dtype=float)
        self.start = SOLVER_DEFAULT_Q.copy() if start is None else np.asarray(start, dtype=float)
        if self.target.shape != (7,) or self.start.shape != (7,):
            raise ValueError("start and target must each have 7 joint angles")
        self.duration = float(duration)
        if profile not in ("linear", "smooth"):
            raise ValueError("profile must be 'linear' or 'smooth'")
        self.profile = profile
        self.n_actuators = len(ACTUATOR_NAMES)
        self.indices = [NAME_TO_IDX[f"{arm}_joint{i}"] for i in range(1, 8)]

    @classmethod
    def from_failure(cls, index=0, seed=0, duration=5.0):
        """Target = an arm config that failed to round-trip with the filter off.

        The failures are those of `experiments/safety_filter_roundtrip.py
        --spread 0 --seed SEED`, biggest joint error first, so index 0 is the
        one with the biggest jump. Returns (policy, failure_dict, all_failures).
        """
        from experiments.safety_filter_roundtrip import branch_failures
        failures = branch_failures(seed=seed, spread=0.0)
        if not failures:
            raise RuntimeError("no round-trip failures found for that seed")
        if not 0 <= index < len(failures):
            raise IndexError(f"index {index} out of range (0..{len(failures) - 1})")
        f = failures[index]
        return cls(f["arm"], f["q"], duration=duration), f, failures

    @classmethod
    def reach_forward(cls, arm="left", duration=4.0, profile="smooth"):
        """Natural pose (elbow 90 deg) -> full forward reach at shoulder height."""
        p = REACH_FORWARD[arm]
        return cls(arm, p["target"], start=p["start"], duration=duration, profile=profile)

    def joints(self, t):
        """The moving arm's 7 joint angles at time t."""
        u = float(np.clip((t or 0.0) / self.duration, 0.0, 1.0))
        s = u if self.profile == "linear" else u ** 3 * (10 - 15 * u + 6 * u * u)
        return self.start + s * (self.target - self.start)

    def __call__(self, state, t=None):
        action = np.zeros(self.n_actuators)
        action[self.indices] = self.joints(t)
        return action
