"""Waving policy - raises the right arm and oscillates the wrist to wave hello.

Code generated by Claude
"""

import numpy as np
from src.actuator_mapping import ACTUATOR_NAMES, NAME_TO_IDX


class WavingPolicy:
    """Two-phase wave: ramp the right arm up, then oscillate the wrist.

    Phase 1 (t < RAMP_DURATION): smoothly ramps the right shoulder and
        elbow from rest into a raised "wave-ready" pose.
    Phase 2 (t >= RAMP_DURATION): holds the raised shoulder/elbow and
        oscillates the wrist joint sinusoidally to produce the wave.
        Runs indefinitely -- call it every step for as long as you want
        the robot to keep waving.

    The joint angles/signs below are a starting guess (same "watch it in
    the viewer and retune" workflow dummy_policy.py needed), not
    calibrated against the real arm geometry -- adjust RAISED_* / WAVE_*
    below if the motion doesn't look like a wave for your model's joint
    conventions.
    """

    RAMP_DURATION = 1.5    # seconds to reach the raised pose
    WAVE_FREQUENCY = 1.0   # Hz, how fast the wave oscillates
    WAVE_AMPLITUDE = 0.4   # radians, how wide the wrist swings

    RAISED_SHOULDER = 0.3   # right_joint1: lifts the arm up and out
    RAISED_ELBOW = -1.2     # right_joint3: bends the elbow so the hand is raised

    def __init__(self):
        self.n_actuators = len(ACTUATOR_NAMES)

    def __call__(self, state, t=None):
        action = np.zeros(self.n_actuators)
        t = t or 0.0

        if t < self.RAMP_DURATION:
            ramp = t / self.RAMP_DURATION
            action[NAME_TO_IDX["right_joint1"]] = self.RAISED_SHOULDER * ramp
            action[NAME_TO_IDX["right_joint3"]] = self.RAISED_ELBOW * ramp
        else:
            action[NAME_TO_IDX["right_joint1"]] = self.RAISED_SHOULDER
            action[NAME_TO_IDX["right_joint3"]] = self.RAISED_ELBOW
            wave_t = t - self.RAMP_DURATION
            action[NAME_TO_IDX["right_joint6"]] = (
                self.WAVE_AMPLITUDE * np.sin(2 * np.pi * self.WAVE_FREQUENCY * wave_t)
            )

        return action