# Code generated by Claude
"""
The operator alert sound: a short two-tone beep, played once when the task policy asks for operator control.

    play_alert()

No audio library is needed: the beep is generated with the standard library (wave) into a WAV file in the temp directory, once, and played
in the background with ALSA's `aplay` (present on this VM; it routes through the sound server). If `aplay` is missing or fails, the terminal
bell is written to stdout instead. Never blocks and never raises.
"""

import math
import shutil
import struct
import subprocess
import sys
import tempfile
import wave
from pathlib import Path

_PATH = Path(tempfile.gettempdir()) / "openarm_tracer_sim_alert.wav"


def _make_wav(path, rate=22050):
    frames = bytearray()
    for freq, dur in ((880, 0.18), (0, 0.07), (1175, 0.25)):          # a rising two-tone beep
        n = int(rate * dur)
        for i in range(n):
            v = 0 if freq == 0 else int(12000 * math.sin(2 * math.pi * freq * i / rate) * min(1.0, i / 200, (n - i) / 200))
            frames += struct.pack("<h", v)
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(rate)
        w.writeframes(bytes(frames))


def play_alert():
    try:
        if not _PATH.exists():
            _make_wav(_PATH)
        if shutil.which("aplay"):
            subprocess.Popen(["aplay", "-q", str(_PATH)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            return True
    except Exception:
        pass
    try:
        sys.stdout.write("\a")
        sys.stdout.flush()
    except Exception:
        pass
    return False
