"""Arm and finger actuators, set up at load time through MjSpec.

Code generated by Claude

Same pattern as src/cameras.py and src/pedestal.py: the XML stays untouched and RobotSimulator applies
this before compiling, always on. Every number comes from robot_specs.ARM_ACTUATOR_SPECS (sources there).

What it does
  1. Armature. The upstream openarm_mujoco v2 model gives each joint the rotor inertia of its motor
     (DM8009 0.0081, DM4340 0.16, DM4310 0.0100 kg m^2). The combined model dropped them (armature 0 on all
     14 arm joints). Restored here. The values are the upstream model's, not measured on our hardware.
     Without them the wrist links are so light (3-6e-3 kg m^2) that an explicit 750 Hz PD chatters at
     375 Hz and saturates (data/arm_hold/summary.txt, fixes_summary.txt).
  2. Position actuators. The 14 arm joint motors become MuJoCo position actuators, so the PD runs inside
     MuJoCo with its velocity term integrated implicitly instead of in Python from the previous step's
     state. kp and kv are the joint's, ctrlrange is the joint range, forcerange the motor's torque
     limit. The gains are PLACEHOLDERS pending the real ros2_control values. data.ctrl for these
     actuators is now the target angle in rad.
  3. All 4 fingers are position actuators with ARM_ACTUATOR_SPECS["fingers"] (the right fingers
     already were; the left ones were torque motors with no force limit).
  4. Gravity compensation, always on: gravcomp = 1 on both arms' link1 through the fingers
     (ARM_ACTUATOR_SPECS["gravcomp_bodies"]). Assumes the real controller compensates for gravity.
  5. Integrator implicitfast. The scene XML asks for "implicit". Both integrate the actuator and joint
     damping terms implicitly, which is what makes the servo stable; they differ only in that "implicit"
     also differentiates the Coriolis terms (more cost, no visible difference here). Measured on the hold
     tests: see data/arm_hold/. implicitfast is MuJoCo's recommended choice.
Actuator order and names are unchanged (src/actuator_mapping.ACTUATOR_NAMES still indexes them).
"""

import mujoco

from src import robot_specs


def _make_position(act, kp, kv, lo, hi, fmax):
    """Turn an actuator (motor or position) into force = kp*(ctrl - q) - kv*qdot, limited."""
    act.gaintype = mujoco.mjtGain.mjGAIN_FIXED
    act.gainprm[0] = kp
    act.biastype = mujoco.mjtBias.mjBIAS_AFFINE
    act.biasprm[:3] = [0.0, -kp, -kv]
    act.ctrllimited = mujoco.mjtLimited.mjLIMITED_TRUE
    act.ctrlrange = [lo, hi]
    act.forcelimited = mujoco.mjtLimited.mjLIMITED_TRUE
    act.forcerange = [-fmax, fmax]


def add_arm_actuators(spec):
    """Apply the arm armature, the position actuators on arm and fingers, gravcomp and the integrator."""
    specs = robot_specs.ARM_ACTUATOR_SPECS
    for side in ("left", "right"):
        for i, j in specs["joints"].items():
            joint, act = spec.joint(f"openarm_{side}_joint{i}"), spec.actuator(f"{side}_joint{i}_ctrl")
            if joint is None or act is None:
                raise ValueError(f"arm joint/actuator for {side} joint {i} not found in model")
            joint.armature = j["armature"]
            _make_position(act, j["kp"], j["kv"], joint.range[0], joint.range[1], j["torque_nm"])
        f = specs["fingers"]
        for k in (1, 2):
            joint, act = spec.joint(f"openarm_{side}_finger_joint{k}"), spec.actuator(f"{side}_finger{k}_ctrl")
            if joint is None or act is None:
                raise ValueError(f"finger {k} joint/actuator for the {side} hand not found in model")
            _make_position(act, f["kp"], f["kv"], joint.range[0], joint.range[1], f["force_limit"])
        for name in specs["gravcomp_bodies"]:
            body = spec.body(f"openarm_{side}_{name}")
            if body is None:
                raise ValueError(f"gravcomp body openarm_{side}_{name} not found in model")
            body.gravcomp = 1.0
    spec.option.integrator = mujoco.mjtIntegrator.mjINT_IMPLICITFAST
