# Code generated by Claude
"""Twist -> free-joint velocity base drive for the Tracer, moved unchanged out of experiments/combined_controller.py.

The base is NOT driven through the wheel actuators: the mesh wheels have no traction in MuJoCo (see the BASE DRIVE
NOTE in experiments/combined_controller.py), so the free joint's velocity is written directly, on every physics step,
from a Twist (forward speed along the base's own x axis, yaw rate).

    base_dof = find_base_dof(model)
    vx, vy, wz = twist_to_world_velocity(base_yaw(data), lin, ang)    # once per command update
    apply_base_velocity(data, base_dof, vx, vy, wz)                   # before every mj_step
"""

import math

import mujoco


def find_base_dof(model):
    """dof address of the first free joint (the Tracer base), or None if the model has none."""
    for j in range(model.njnt):
        if model.jnt_type[j] == mujoco.mjtJoint.mjJNT_FREE:
            return int(model.jnt_dofadr[j])
    return None


def base_yaw(data):
    """Yaw (rad) of the free-joint body from its quaternion."""
    qw, qx, qy, qz = data.qpos[3:7]
    return math.atan2(
        2.0 * (qw * qz + qx * qy),
        1.0 - 2.0 * (qy * qy + qz * qz))


def twist_to_world_velocity(yaw, lin_vel, ang_vel):
    """Project the forward velocity into the world frame using the robot yaw (control_loop: lines ~916-925 of the old file)."""
    base_vx = lin_vel * math.cos(yaw)
    base_vy = lin_vel * math.sin(yaw)
    base_wz = ang_vel
    return base_vx, base_vy, base_wz


def apply_base_velocity(data, base_dof, base_vx, base_vy, base_wz):
    """Set base XY velocity and yaw rate (call before every mj_step). Also zero out roll and pitch angular velocity:
    without this, the wheel-floor contact friction opposes the forced linear velocity and creates a pitching torque
    that tips the robot over. Z velocity is left to physics (gravity, settling)."""
    data.qvel[base_dof + 0] = base_vx
    data.qvel[base_dof + 1] = base_vy
    # qvel[base_dof + 2] (Z) left to physics
    data.qvel[base_dof + 3] = 0.0  # no roll
    data.qvel[base_dof + 4] = 0.0  # no pitch
    data.qvel[base_dof + 5] = base_wz
