"""Simulated Orbbec cameras: injected into the model at load time and rendered offscreen.

Code generated by Claude
"""

import mujoco
import numpy as np


def look_at_quat(pos, target, up):
    """Quaternion (w, x, y, z) for a MuJoCo camera at `pos` looking at `target`.

    MuJoCo cameras look along their own -Z axis with +Y up in the image, so the
    rotation matrix columns are [right, cam_up, -forward]. This is NOT the ROS
    optical frame convention (+Z forward, +Y down); convert if the images or
    poses are handed to ROS tooling.

    Raises ValueError if `up` is parallel to the viewing direction.
    """
    pos = np.asarray(pos, dtype=float)
    forward = np.asarray(target, dtype=float) - pos
    forward = forward / np.linalg.norm(forward)

    right = np.cross(forward, np.asarray(up, dtype=float))
    norm = np.linalg.norm(right)
    if norm < 1e-9:
        raise ValueError(
            f"up vector {list(up)} is parallel to the viewing direction "
            f"{forward.round(3).tolist()}")
    right = right / norm
    cam_up = np.cross(right, forward)

    mat = np.column_stack([right, cam_up, -forward])
    quat = np.zeros(4)
    mujoco.mju_mat2Quat(quat, mat.flatten())
    return quat


def add_cameras(spec, camera_specs):
    """Add each camera in `camera_specs` (see robot_specs.CAMERA_SPECS) to an MjSpec."""
    for cs in camera_specs:
        if cs["parent"] == "world":
            parent = spec.worldbody
        else:
            parent = spec.body(cs["parent"])
            if parent is None:
                raise ValueError(
                    f"Camera '{cs['name']}': parent body '{cs['parent']}' "
                    f"not found in model")
        cam = parent.add_camera()
        cam.name = cs["name"]
        cam.pos = cs["pos"]
        cam.quat = look_at_quat(cs["pos"], cs["look_at"], cs["up"])
        cam.fovy = cs["fovy"]
        cam.resolution = list(cs["resolution"])


def make_offscreen_big_enough(model, camera_specs):
    """Raise the offscreen framebuffer size to fit the largest camera.

    Must be called before the MjrContext is created.
    """
    max_w = max(cs["resolution"][0] for cs in camera_specs)
    max_h = max(cs["resolution"][1] for cs in camera_specs)
    model.vis.global_.offwidth = max(model.vis.global_.offwidth, max_w)
    model.vis.global_.offheight = max(model.vis.global_.offheight, max_h)


class CameraRig:
    """Renders every spec'd camera offscreen into self.images[name] as (H, W, 3) uint8.

    Uses the caller's MjrContext (shared with the GLFW viewer) rather than
    mujoco.Renderer, so there is only one GL context to manage. The context
    must be created after make_offscreen_big_enough().

    shadows=False turns off shadows and reflections in the camera renders,
    which is ~8x faster on software GL (a VM without a GPU).
    """

    def __init__(self, model, camera_specs, context, shadows=True):
        self.model = model
        self.context = context
        self.specs = list(camera_specs)
        self.shadows = shadows
        self.option = mujoco.MjvOption()
        self.scene = mujoco.MjvScene(model, maxgeom=10_000)
        self.cameras = {}
        self.images = {}
        for cs in self.specs:
            cam_id = mujoco.mj_name2id(
                model, mujoco.mjtObj.mjOBJ_CAMERA, cs["name"])
            if cam_id < 0:
                raise ValueError(f"Camera '{cs['name']}' not in compiled model")
            cam = mujoco.MjvCamera()
            cam.type = mujoco.mjtCamera.mjCAMERA_FIXED
            cam.fixedcamid = cam_id
            self.cameras[cs["name"]] = cam
            w, h = cs["resolution"]
            self.images[cs["name"]] = np.zeros((h, w, 3), dtype=np.uint8)

    def render(self, data, names=None):
        """Render the cameras in `names` (default all) from the current `data` state."""
        mujoco.mjr_setBuffer(mujoco.mjtFramebuffer.mjFB_OFFSCREEN, self.context)
        for cs in self.specs:
            name = cs["name"]
            if names is not None and name not in names:
                continue
            w, h = cs["resolution"]
            viewport = mujoco.MjrRect(0, 0, w, h)
            # A spec may set "shadows" to override the rig default (the
            # shadow pass is most of the render cost on software GL).
            on = int(cs.get("shadows", self.shadows))
            self.scene.flags[mujoco.mjtRndFlag.mjRND_SHADOW] = on
            self.scene.flags[mujoco.mjtRndFlag.mjRND_REFLECTION] = on
            mujoco.mjv_updateScene(
                self.model, data, self.option, None, self.cameras[name],
                mujoco.mjtCatBit.mjCAT_ALL, self.scene)
            mujoco.mjr_render(viewport, self.scene, self.context)
            rgb = np.zeros((h, w, 3), dtype=np.uint8)
            mujoco.mjr_readPixels(rgb, None, viewport, self.context)
            # OpenGL rows are bottom up; flip so row 0 is the top of the image
            self.images[name] = np.flipud(rgb)
        mujoco.mjr_setBuffer(mujoco.mjtFramebuffer.mjFB_WINDOW, self.context)
