# Code generated by Claude
"""
The command format of the control loop (src/control_loop.py), in one place, and validate_command().

A command tells the loop what ONE subsystem should do. A source's step(obs) returns a command, a list of commands,
or None / [] for "nothing new". Commands are plain dicts tagged with a mode:

    {"mode": "base",     "twist": (vx, wz)}       forward speed along the base's x axis [m/s], yaw rate [rad/s]
    {"mode": "pedestal", "height": h}             pedestal_lift command [m]: 0 = fully raised, negative = lowered
    {"mode": "arms",     "arm_targets": {"left": [7 rad], "right": [7 rad]},     joint targets, joints 1-7
                         "gripper":     {"left": g, "right": g}}                  finger travel [m], 0 closed .. 0.044 open
    {"mode": "neck",     "neck_targets": {"shoulder_pan": rad, ...}}      camera neck joint targets (joint names of
                                                                          NECK_SPECS["active_joints"]); partial dicts are fine
    {"mode": "idle"}                              nothing is commanded; the base is brought to a stop
    {"mode": "request_teleop", "reason": str}     not a subsystem command: the task policy asks for operator control. The loop honours it
                                                  only from its auto source while the controller is in "auto" mode: it switches to "teleop"
                                                  at once (the rest of that tick's commands are dropped).

"arm_targets" and "gripper" are both optional in an arms command, and either side may be left out: only what is
present changes. Targets are absolute, not increments. Subsystems that are not commanded hold their last targets
(the base holds a zero Twist once it has been stopped).

The neck is EXEMPT from exclusivity (EXEMPT_SUBSYSTEMS): it may move while the base, pedestal or arms move, and it is never held
back or counted as the active subsystem. The loop moves the neck's position targets toward the commanded ones at no more than
cfg["neck_max_speed"].

Exclusivity (LOOP_CFG["exclusive"], off by default): when on, only one subsystem moves at a time. If a command for a
different subsystem arrives while the active one is still moving, the loop holds it until the active subsystem has
settled (logged), then applies it; a newer command replaces an older waiting one. When off, every command is applied
at once, so base, pedestal and arms can move together (the behavior of the keyboard / teleop / policy modes today).

Adding a subsystem (a camera neck, say) means adding its name to SUBSYSTEMS and a branch in validate_command().
"""

import math

SUBSYSTEMS = ("base", "pedestal", "arms", "neck")
EXEMPT_SUBSYSTEMS = ("neck",)                  # not subject to exclusivity / the hold rule
MODES = SUBSYSTEMS + ("idle", "request_teleop")
SIDES = ("left", "right")


def _finite(x):
    try:
        return math.isfinite(float(x))
    except (TypeError, ValueError):
        return False


def validate_command(cmd, limits=None):
    """Check one command. Returns (clean_command or None, messages).

    A malformed command (not a dict, unknown mode, missing or non-finite values, wrong lengths) returns None with the
    reasons. Out-of-range values are clipped to `limits` and reported in the messages (the command is still returned).
    limits (optional): {"arm": {side: (lo[7], hi[7])}, "gripper": (lo, hi), "pedestal": (lo, hi), "neck": {joint: (lo, hi)}}.
    """
    limits = limits or {}
    msgs = []
    if not isinstance(cmd, dict) or cmd.get("mode") not in MODES:
        return None, [f"unknown or missing mode in {cmd!r}"]
    mode = cmd["mode"]
    if mode == "idle":
        return {"mode": "idle"}, msgs
    if mode == "request_teleop":
        return {"mode": "request_teleop", "reason": str(cmd.get("reason", ""))}, msgs
    if mode == "base":
        tw = cmd.get("twist")
        if tw is None or len(tw) != 2 or not all(_finite(v) for v in tw):
            return None, [f"base command needs a finite twist (vx, wz), got {tw!r}"]
        return {"mode": "base", "twist": (float(tw[0]), float(tw[1]))}, msgs
    if mode == "pedestal":
        h = cmd.get("height")
        if not _finite(h):
            return None, [f"pedestal command needs a finite height, got {h!r}"]
        h = float(h)
        lo, hi = limits.get("pedestal", (-math.inf, math.inf))
        if not lo <= h <= hi:
            msgs.append(f"pedestal height {h:.4f} clipped to [{lo:.3f}, {hi:.3f}]")
            h = min(max(h, lo), hi)
        return {"mode": "pedestal", "height": h}, msgs
    if mode == "neck":
        nt = cmd.get("neck_targets")
        if not isinstance(nt, dict) or not nt:
            return None, ["neck command needs a non-empty neck_targets dict"]
        out = {"mode": "neck", "neck_targets": {}}
        for name, v in nt.items():
            if not _finite(v):
                return None, [f"neck_targets[{name!r}] must be a finite angle, got {v!r}"]
            v = float(v)
            if "neck" in limits:
                if name not in limits["neck"]:
                    return None, [f"unknown neck joint {name!r}"]
                lo, hi = limits["neck"][name]
                if not lo <= v <= hi:
                    msgs.append(f"neck_targets[{name!r}] {v:.3f} clipped to [{lo:.3f}, {hi:.3f}]")
                    v = min(max(v, lo), hi)
            out["neck_targets"][name] = v
        return out, msgs
    # arms
    out = {"mode": "arms"}
    at = cmd.get("arm_targets")
    gr = cmd.get("gripper")
    if at is None and gr is None:
        return None, ["arms command needs arm_targets and/or gripper"]
    if at is not None:
        out["arm_targets"] = {}
        for side, q in at.items():
            if side not in SIDES or len(q) != 7 or not all(_finite(v) for v in q):
                return None, [f"arm_targets[{side!r}] must be 7 finite joint angles, got {q!r}"]
            q = [float(v) for v in q]
            if "arm" in limits and side in limits["arm"]:
                lo, hi = limits["arm"][side]
                clipped = [min(max(v, l), h) for v, l, h in zip(q, lo, hi)]
                if clipped != q:
                    msgs.append(f"arm_targets[{side!r}] clipped to the joint limits")
                q = clipped
            out["arm_targets"][side] = q
    if gr is not None:
        out["gripper"] = {}
        for side, g in gr.items():
            if side not in SIDES or not _finite(g):
                return None, [f"gripper[{side!r}] must be a finite finger travel, got {g!r}"]
            g = float(g)
            lo, hi = limits.get("gripper", (-math.inf, math.inf))
            if not lo <= g <= hi:
                msgs.append(f"gripper[{side!r}] {g:.4f} clipped to [{lo:.3f}, {hi:.3f}]")
                g = min(max(g, lo), hi)
            out["gripper"][side] = g
    return out, msgs
