# Code generated by Claude
"""
The control loop, moved out of experiments/combined_controller.py so any code can import and run it.

    from src.control_loop import run_loop
    run_loop(model, data, sources, cfg, viewer=None, logger=None)

It separates "who decides" from "how it is executed". Sources (keyboard, teleop, a policy, later a scripted sequence or
a VLA) are dicts with step(obs) -> command(s); the loop validates the commands (src/commands.py), applies them to
the robot's targets and executes them: arms, grippers and the pedestal are MuJoCo position actuators tracking the
loop's targets on every physics step, the base is driven from a Twist (src/base_control.py).

Each iteration ("tick", cfg["source_hz"] = 62.5 Hz = 12 physics steps at 750 Hz):
  1. build the observation (sim.get_observation() plus tick, base pose, pedestal height, the applied targets and the
     latest camera frames; the frames are re-rendered at 30 Hz, one camera per render tick unless
     cfg["camera_roundrobin"] is off, and reused in between)
  2. hotkeys (F2 = router switch, F5 = trajectory logging); call every source; keep the commands the router routes to
     that source; validate them
  3. apply them: at once, or, with cfg["exclusive"], one subsystem at a time with the hold rule
  3b. the neck (exempt from exclusivity) moves its position targets toward the commanded ones at cfg["neck_max_speed"]
  4. write the position targets to data.ctrl once, then step physics 12 times, writing the base velocity before every
     step and rendering a camera every cam_every (25) steps
  5. logging, then viewer["frame"](info) if there is a viewer. The window is redrawn at cfg["viewer_draw_hz"] (30 Hz: every
     2nd tick, 31.25 Hz); on the other ticks the viewer only polls keys and paces. Physics and control run at the full rate.

Router: cfg["routes"] maps each field to the source that owns it. Fields: "base", "pedestal", "arms.left", "arms.right",
"gripper.left", "gripper.right", "neck". A value is a source name or a tuple of names (several sources may command the
field; later ones in the sources dict win a tick). By default everything is the keyboard. The F2 hotkey (teleop runs) moves both
"arms.*" fields between "keyboard" and "teleop" at run time (calling the teleop source's enable / disable); a policy
source owns the fields of its auto groups for the whole run. Sources that are not routed still get step() called (the
teleop source keeps its camera preview fresh).

Exclusivity (cfg["exclusive"], OFF by default so the keyboard, teleop and policy modes behave exactly as before): with
it on, a tick applies at most one subsystem's command. A command for a different subsystem than the active one is
held while the active one moves, then applied (newest replaces an older waiting one; each hold is logged with its
duration). While holding, a moving base is brought to a stop at cfg["base_stop_*_decel"]. "Settled" thresholds are
cfg["settle_*"] (provisional).

Supervisor hook (used by src/episode_runner.py; unset = no effect): cfg["on_tick"](obs, loop) is called every tick right after
the observation is built and before the sources step. It may add keys to `obs` (every source then sees them, e.g.
obs["episode"]), change routes at run time (loop["routes"] is the live router table), end the run with loop["stop"](reason), and render
one camera frame with loop["render"](camera_name) (works headless: an offscreen EGL context is created on first use). It may return a short
status string, shown in the viewer's HUD. cfg["spawn_yaw"] sets the base's yaw at spawn (None = the XML's).

Cameras. Two separate rigs, so what the operator sees can be cheap while what a policy sees stays full quality:
  * the policy cameras (cfg["cameras"], "camera_hz", "camera_shadows"; shadows on, 30 Hz round robin by default) fill obs["cameras"];
  * the operator insets (cfg["inset_cameras"], only with a viewer): a second rig with shadows off, rendered at cfg["inset_res"],
    one camera per render, each camera updating at cfg["inset_hz"]. It feeds only the viewer's insets.
A viewer run that does not need the policy cameras sets cfg["cameras"] = False; loop["render"](name) still gives full-quality frames on demand.

Headless: viewer=None runs without a window. Cameras then render through an offscreen context (set MUJOCO_GL=egl before
importing mujoco on a machine without a display) or are skipped with cfg["cameras"] = False.
"""

import csv
import math
import time

import mujoco
import numpy as np

from src import robot_specs
from src.base_control import apply_base_velocity, base_yaw, find_base_dof, twist_to_world_velocity
from src.cameras import CameraRig
from src.commands import EXEMPT_SUBSYSTEMS, validate_command
from src.neck import neck_ids

LOOP_CFG = {
    "source_hz": 62.5,             # command / viewer tick; the physics rate must be a whole multiple (12 steps at 750 Hz)
    "camera_hz": None,             # None = robot_specs.CAMERA_HZ (30)
    "camera_roundrobin": True,     # one camera per render tick (a VM performance setting); False renders all each tick
    "camera_shadows": True,
    "cameras": True,               # policy cameras. False: no policy rig (pure physics run, or a viewer run that only needs the insets)
    "viewer_draw_hz": 30,          # window redraw rate; the tick is quantised to a whole number of ticks per redraw (2 -> 31.25 Hz)
    "inset_cameras": True,         # operator insets from their own cheap rig (used only when there is a viewer)
    "inset_hz": 1.0,               # update rate of EACH inset camera (they take turns: 3 x this many renders per second)
    "inset_res": (320, 240),       # inset render size (the viewer draws them at most this big)
    "inset_shadows": False,
    "spawn_pos": None,             # [x, y, z] for the base free joint, or None for the XML default
    "warmup_s": 1.0,               # settle durations in seconds, converted to steps from the physics rate
    "resettle_s": 0.4,
    "routes": {},                  # overrides of DEFAULT_ROUTES
    "claimed_ids": (),             # actuators owned by auto groups: not held at the captured rest pose (as before)
    "hotkeys": {},                 # {"toggle_route": key code (F2), "toggle_log": key code (F5), "quit": key code (Esc)}
    "held": None,                  # held(key code) -> bool, from the launcher; None = no keys
    "tick_ref": None,              # a one-element list the loop keeps equal to the tick number (for key injection)
    "exclusive": False,
    # "settled" thresholds (measured velocities below the limit for the dwell time), provisional
    "settle_base_lin": 0.01, "settle_base_ang": 0.02, "settle_base_dwell": 0.1,
    "settle_ped_speed": 0.002, "settle_ped_dwell": 0.2,
    "settle_arm_speed": 0.02, "settle_finger_speed": 0.002, "settle_arm_dwell": 0.2,
    "base_stop_lin_decel": 1.875,  # m/s^2, bringing the base to rest during a hold (= the keyboard's SPACE ramp rate)
    "base_stop_ang_decel": 2.5,    # rad/s^2
    # test / benchmark hooks
    "bench_frames": 0,             # run this many ticks (after 10 warm-up ticks), print timings, then stop
    "bench_log": None,             # CSV path: base pose, pedestal height, arm joints, fingers every 75 physics steps
    "preview": False,              # teleop: the operator preview inset is shown
    "on_tick": None,               # supervisor hook, see above
    "spawn_yaw": None,             # rad, base yaw at spawn (None = leave the XML's)
    "neck_specs": None,            # None = robot_specs.NECK_SPECS (the neck is skipped if the model has none)
    "neck_max_speed": None,        # rad/s; None = NECK_SPECS["max_speed"]
}

ROUTE_KEYS = ("base", "pedestal", "arms.left", "arms.right", "gripper.left", "gripper.right", "neck")
DEFAULT_ROUTES = {k: "keyboard" for k in ROUTE_KEYS}


def observation(model, data):
    """The same dict as RobotSimulator.get_observation() (the logger and the policies read it)."""
    return {
        "time": data.time,
        "joint_angles": data.qpos.copy(),
        "joint_velocities": data.qvel.copy(),
        # actual actuator force (N m for rotary joints, N for slides and the pedestal lift), as
        # the servo applied it; "ctrl" is what was commanded (target angles/heights for position
        # actuators, wheel torque commands for the motors)
        "joint_torques": data.actuator_force.copy(),
        "ctrl": data.ctrl.copy(),
    }


def _headless_context(model):
    gl = mujoco.GLContext(model.vis.global_.offwidth, model.vis.global_.offheight)
    gl.make_current()
    return gl, mujoco.MjrContext(model, mujoco.mjtFontScale.mjFONTSCALE_150)


def _filter_by_route(cmd, name, routes):
    """The part of `cmd` that source `name` owns, or None."""
    mode = cmd["mode"]
    owns = lambda field: name in ((routes.get(field),) if not isinstance(routes.get(field), tuple) else routes[field])
    if mode == "idle":
        return cmd
    if mode in ("base", "pedestal", "neck"):
        return cmd if owns(mode) else None
    at = {sd: q for sd, q in cmd.get("arm_targets", {}).items() if owns(f"arms.{sd}")}
    gr = {sd: g for sd, g in cmd.get("gripper", {}).items() if owns(f"gripper.{sd}")}
    if not at and not gr:
        return None
    out = {"mode": "arms"}
    if at:
        out["arm_targets"] = at
    if gr:
        out["gripper"] = gr
    return out


def run_loop(model, data, sources, cfg, viewer=None, logger=None):
    cfg = {**LOOP_CFG, **cfg}
    routes = {**DEFAULT_ROUTES, **cfg["routes"]}
    held = cfg["held"] or (viewer["key_down"] if viewer else (lambda code: False))
    hk = cfg["hotkeys"]
    tick_ref = cfg["tick_ref"]
    pc = time.perf_counter

    # --- Multi-rate schedule (all derived from the model timestep) ---
    physics_hz = 1.0 / model.opt.timestep

    def _every(hz, what):
        n = physics_hz / hz
        if abs(n - round(n)) > 1e-6:
            raise ValueError(f"physics {physics_hz:.1f} Hz is not an integer "
                             f"multiple of {what} {hz} Hz")
        return int(round(n))

    camera_hz = cfg["camera_hz"] or robot_specs.CAMERA_HZ
    cam_every = _every(camera_hz, "camera")
    steps_per_frame = _every(cfg["source_hz"], "source")
    tick_dt = steps_per_frame * model.opt.timestep
    warmup_steps = round(cfg["warmup_s"] * physics_hz)
    resettle_steps = round(cfg["resettle_s"] * physics_hz)
    print(f"Rates: physics {physics_hz:.0f} Hz (arm/finger servos every step) | cameras every {cam_every} steps "
          f"({physics_hz / cam_every:.0f} Hz, "
          f"{'one camera per tick' if cfg['camera_roundrobin'] else 'all cameras per tick'}) "
          f"| commands/viewer {steps_per_frame} steps/frame "
          f"(~{physics_hz / steps_per_frame:.0f} Hz)")
    print("  routes: " + ", ".join(f"{k}->{v}" for k, v in routes.items()))

    # --- Actuators ---
    def aid(name):
        a = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_ACTUATOR, name)
        if a < 0:
            raise RuntimeError(f"Actuator '{name}' not in model.")
        return a

    wheel_ids = [aid("left_motor"), aid("right_motor")]
    claimed = set(wheel_ids) | set(cfg["claimed_ids"])
    # Unclaimed actuators hold their settled position so the robot
    # doesn't collapse.  This is not "auto" — it's just gravity
    # compensation for joints nobody is actively controlling.
    unclaimed_ids = sorted(set(range(model.nu)) - claimed)

    base_dof = find_base_dof(model)
    if base_dof is not None:
        print(f"  Free joint '{model.joint(int(model.dof_jntid[base_dof])).name}' "
              f"dof_adr={base_dof} (velocity drive target)")
    else:
        print("  WARNING: no free joint found — velocity drive disabled")

    # Arms, fingers and the pedestal lift are MuJoCo position actuators (ctrl = target
    # angle / height); only the wheel motors are torque actuators and they get ctrl 0 (the base is
    # velocity-driven). A masked-out position actuator therefore holds its last hold target, since
    # ctrl 0 would mean "go to angle 0", not "limp".
    is_pos = model.actuator_biastype == mujoco.mjtBias.mjBIAS_AFFINE

    sides = ("left", "right")
    arm_act = {s: [aid(f"{s}_joint{i}_ctrl") for i in range(1, 8)] for s in sides}
    fing_act = {s: [aid(f"{s}_finger1_ctrl"), aid(f"{s}_finger2_ctrl")] for s in sides}
    jr = lambda a: model.jnt_range[model.actuator_trnid[a, 0]]
    vadr = lambda a: int(model.jnt_dofadr[model.actuator_trnid[a, 0]])
    arm_vadr = {s: [vadr(a) for a in arm_act[s]] for s in sides}
    fing_vadr = [vadr(a) for s in sides for a in fing_act[s]]
    ped_aid = aid(robot_specs.PEDESTAL_SPECS["actuator_name"])
    ped_lo, ped_hi = model.actuator_ctrlrange[ped_aid]
    ped_vadr = vadr(ped_aid)
    ped_qadr = int(model.jnt_qposadr[model.actuator_trnid[ped_aid, 0]])
    limits = {"arm": {s: (np.array([jr(a)[0] for a in arm_act[s]]), np.array([jr(a)[1] for a in arm_act[s]])) for s in sides},
              "gripper": tuple(jr(fing_act["left"][0])), "pedestal": (float(ped_lo), float(ped_hi))}

    neck_specs = cfg["neck_specs"] or robot_specs.NECK_SPECS
    neck = neck_ids(model, neck_specs)                    # None if the model has no neck
    neck_max_speed = cfg["neck_max_speed"] or neck_specs["max_speed"]
    if neck is not None:
        limits["neck"] = {n: (float(l), float(h)) for n, l, h in zip(neck["names"], neck["lo"], neck["hi"])}
        neck_home = np.array(neck_specs["drive_pose"], float)
        print(f"  neck: {neck['names']} actuators {neck['act']}, default aim (drive pose) {np.degrees(neck_home).round(1)} deg, "
              f"max {neck_max_speed:g} rad/s")

    base_body_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "base_link")
    if base_body_id < 0:
        base_body_id = 1

    # --- Spawn and settle ---
    if cfg["spawn_pos"] is not None:
        data.qpos[0:3] = cfg["spawn_pos"]
        if cfg["spawn_yaw"] is not None:
            data.qpos[3:7] = [math.cos(cfg["spawn_yaw"] / 2), 0.0, 0.0, math.sin(cfg["spawn_yaw"] / 2)]
        mujoco.mj_forward(model, data)

    if neck is not None:                      # start with the neck at its default aim, not in a transient from zero
        for a, v in zip(neck["qadr"], neck_home):
            data.qpos[a] = v
        mujoco.mj_forward(model, data)

    print("Settling physics ...")
    # Hold arm joints at home (zero) during warmup so they settle under
    # PD control instead of drooping limp and then oscillating when the
    # main loop starts.
    hold_qpos_targets = np.zeros(model.nu)
    hold_qpos_targets[ped_aid] = robot_specs.PEDESTAL_SPECS["target_height"]
    if neck is not None:
        hold_qpos_targets[neck["act"]] = neck_home
    for i in range(warmup_steps):
        # Only apply hold targets for unclaimed position actuators; zero the rest
        for a in range(model.nu):
            data.ctrl[a] = hold_qpos_targets[a] if (a in unclaimed_ids and is_pos[a]) else 0.0
        mujoco.mj_step(model, data)
    print(f"Settled at z={data.qpos[2]:.4f}")

    # Capture the natural resting pose after warmup — arms hanging down
    # under gravity.  Zero velocities so they're still, then re-settle
    # briefly with PD holding at this pose.  The PD doesn't need to fight
    # gravity (it's already at equilibrium) — it just resists disturbances
    # when the base moves.
    hold_qpos_targets = np.zeros(model.nu)
    for a in unclaimed_ids:
        qadr = model.jnt_qposadr[model.actuator_trnid[a, 0]]
        hold_qpos_targets[a] = data.qpos[qadr]  # actual drooped angle
        va = model.jnt_dofadr[model.actuator_trnid[a, 0]]
        data.qvel[va] = 0.0  # kill any residual swing
    hold_qpos_targets[ped_aid] = robot_specs.PEDESTAL_SPECS["target_height"]
    if neck is not None:                      # the neck holds its default aim exactly (its servos are stiff; no sag capture)
        hold_qpos_targets[neck["act"]] = neck_home
    mujoco.mj_forward(model, data)

    # Brief re-settle with PD active so everything stabilizes
    for i in range(resettle_steps):
        for a in unclaimed_ids:
            if is_pos[a]:
                data.ctrl[a] = hold_qpos_targets[a]
        mujoco.mj_step(model, data)
    print(f"Arms locked at resting pose, re-settled at z={data.qpos[2]:.4f}")

    # Sources that build things that need the settled robot (the teleop session, the fake operator's clock)
    for src in sources.values():
        if "start" in src:
            src["start"]()

    # --- Cameras: the viewer's GL context, or an offscreen one when headless ---
    rig, gl_keepalive = None, None
    if cfg["cameras"]:
        if viewer is not None:
            context = viewer["context"]
        else:
            gl_keepalive, context = _headless_context(model)
        # Render once so frames exist before the first camera tick.
        rig = CameraRig(model, robot_specs.CAMERA_SPECS, context, shadows=cfg["camera_shadows"])
        rig.render(data)
    cam_names = [cs["name"] for cs in robot_specs.CAMERA_SPECS]
    cam_tick = 0

    # --- Operator insets: their own rig (shadows off, small), rendered only on viewer redraws ---
    draw_every = max(1, round(cfg["source_hz"] / cfg["viewer_draw_hz"])) if viewer is not None else 1
    irig, inset_every, inset_tick = None, 1, 0
    if viewer is not None and cfg["inset_cameras"]:
        w_i, h_i = cfg["inset_res"]
        ispecs = [{**cs, "resolution": (w_i, h_i), "shadows": cfg["inset_shadows"]} for cs in robot_specs.CAMERA_SPECS]
        irig = CameraRig(model, ispecs, viewer["context"], shadows=cfg["inset_shadows"])
        irig.render(data)
        # renders per second = n_cameras * inset_hz, one every `inset_every` redraws
        inset_every = max(1, round((cfg["source_hz"] / draw_every) / (len(ispecs) * cfg["inset_hz"])))
        print(f"Viewer: redraw every {draw_every} ticks ({cfg['source_hz'] / draw_every:.1f} Hz); operator insets {w_i}x{h_i}, shadows "
              f"{'on' if cfg['inset_shadows'] else 'off'}, one camera every {inset_every} redraws "
              f"(each camera ~{cfg['source_hz'] / draw_every / inset_every / len(ispecs):.1f} Hz)")
    elif viewer is not None:
        print(f"Viewer: redraw every {draw_every} ticks ({cfg['source_hz'] / draw_every:.1f} Hz); no operator insets")

    # --- The loop's state: the applied targets, the base Twist, the exclusivity / hold bookkeeping ---
    st = {"twist": (0.0, 0.0)}
    neck_goal = neck_home.copy() if neck is not None else None
    ex = {"active": None, "pending": None, "hold_t0": None, "hold_blocker": None, "log": [], "warned": set(),
          "still": {"base": 0.0, "pedestal": 0.0, "arms": 0.0}}
    msgs_seen = set()

    def applied():
        return {"twist": st["twist"], "pedestal": float(hold_qpos_targets[ped_aid]),
                "arm_targets": {s: [float(hold_qpos_targets[a]) for a in arm_act[s]] for s in sides},
                "gripper": {s: float(hold_qpos_targets[fing_act[s][0]]) for s in sides}, "mode": ex["active"],
                "neck_targets": {n: float(hold_qpos_targets[a]) for n, a in zip(neck["names"], neck["act"])} if neck is not None else {},
                "neck_goal": {n: float(g) for n, g in zip(neck["names"], neck_goal)} if neck is not None else {}}

    def apply_cmd(cmd):
        mode = cmd["mode"]
        if mode == "base":
            st["twist"] = cmd["twist"]
        elif mode == "pedestal":
            hold_qpos_targets[ped_aid] = cmd["height"]
        elif mode == "neck":
            if neck is not None:
                for n, v in cmd["neck_targets"].items():
                    neck_goal[neck["names"].index(n)] = v
        elif mode == "arms":
            for s, q in cmd.get("arm_targets", {}).items():
                hold_qpos_targets[arm_act[s]] = q
            for s, g in cmd.get("gripper", {}).items():
                hold_qpos_targets[fing_act[s]] = g

    # --- Exclusivity and the hold rule ---
    def measure_still():
        """Update, per subsystem, how long its measured velocity has been below the settled threshold."""
        qv = data.qvel
        base_ok = base_dof is None or (math.hypot(qv[base_dof], qv[base_dof + 1]) < cfg["settle_base_lin"]
                                       and abs(qv[base_dof + 5]) < cfg["settle_base_ang"]
                                       and abs(st["twist"][0]) < cfg["settle_base_lin"] and abs(st["twist"][1]) < cfg["settle_base_ang"])
        ped_ok = abs(qv[ped_vadr]) < cfg["settle_ped_speed"]
        arm_ok = max(abs(qv[v]) for s in sides for v in arm_vadr[s]) < cfg["settle_arm_speed"] \
            and max(abs(qv[v]) for v in fing_vadr) < cfg["settle_finger_speed"]
        for name, ok in (("base", base_ok), ("pedestal", ped_ok), ("arms", arm_ok)):
            ex["still"][name] = ex["still"][name] + tick_dt if ok else 0.0

    dwell = {"base": cfg["settle_base_dwell"], "pedestal": cfg["settle_ped_dwell"], "arms": cfg["settle_arm_dwell"]}
    settled = lambda sub: ex["still"][sub] >= dwell[sub]

    def stop_base():
        """Bring the Twist toward zero at the configured deceleration (during a hold, or on idle)."""
        lin, ang = st["twist"]
        dl, da = cfg["base_stop_lin_decel"] * tick_dt, cfg["base_stop_ang_decel"] * tick_dt
        st["twist"] = (lin - math.copysign(min(abs(lin), dl), lin), ang - math.copysign(min(abs(ang), da), ang))

    def exclusive_select(cmds, t):
        """Reduce this tick's commands to the ones to apply now (at most one subsystem)."""
        nonidle = [c for c in cmds if c["mode"] != "idle"]
        modes = {c["mode"] for c in nonidle}
        if len(modes) > 1 and tuple(sorted(modes)) not in ex["warned"]:
            ex["warned"].add(tuple(sorted(modes)))
            print(f"[exclusive] commands for {sorted(modes)} in one tick: only the first ('{nonidle[0]['mode']}') is used")
        new = nonidle[0] if nonidle else None
        if new is None and any(c["mode"] == "idle" for c in cmds):
            ex["pending"] = None
            stop_base()
            return []
        cand = new if new is not None else ex["pending"]
        if cand is None:
            return []
        active = ex["active"]
        if active in (None, cand["mode"]) or settled(active):
            if ex["pending"] is not None or ex["hold_t0"] is not None:
                dur = t - ex["hold_t0"]
                ex["log"].append({"t_start": ex["hold_t0"], "t_end": t, "duration": dur, "waiting": cand["mode"],
                                  "blocked_by": ex["hold_blocker"], "applied": True})
                print(f"[hold] t={t:.2f} s: '{cand['mode']}' command applied after waiting {dur:.2f} s for '{ex['hold_blocker']}' to settle")
            ex["pending"], ex["hold_t0"], ex["hold_blocker"] = None, None, None
            ex["active"] = cand["mode"]
            return [cand]
        if ex["hold_t0"] is None:
            ex["hold_t0"], ex["hold_blocker"] = t, active
            print(f"[hold] t={t:.2f} s: '{cand['mode']}' command waits for '{active}' to settle")
        ex["pending"] = cand                       # newest replaces older
        if active == "base":
            stop_base()
        return []

    # --- Bench / test hooks ---
    bench_log = None
    if cfg["bench_log"]:
        bench_log = open(cfg["bench_log"], "w", newline="")
        bench_csv = csv.writer(bench_log)
        log_joints = [model.joint(f"openarm_{sd}_joint{i}").qposadr[0] for sd in ("left", "right") for i in range(1, 8)] \
            + [model.joint(f"openarm_{sd}_finger_joint{k}").qposadr[0] for sd in ("left", "right") for k in (1, 2)]
        bench_csv.writerow(["sim_time", "base_x", "base_y", "base_yaw_deg", "pedestal_m"]
                           + [f"{sd}_joint{i}" for sd in ("left", "right") for i in range(1, 8)]
                           + [f"{sd}_finger{k}" for sd in ("left", "right") for k in (1, 2)]
                           + ([f"neck_{n}" for n in neck["names"]] if neck is not None else []))
    tm = {"phys": 0.0, "cam": 0.0, "inset": 0.0}
    t_bench0 = None
    ds_state = sources["keyboard"]["state"]["drive"] if "keyboard" in sources else {}
    teleop = sources.get("teleop")
    jog_ids = {"L3": arm_act["left"][2], "R1": arm_act["right"][0], "Lg": fing_act["left"][0], "Rg": fing_act["right"][0]}

    # --- hook API for cfg["on_tick"] ---
    stop_req = [None]
    rig_box = {"rig": rig, "gl": None}

    def render(name):
        """One frame of camera `name` from the current state (creates a rig on first use if the loop has none)."""
        if rig_box["rig"] is None:
            if viewer is not None:
                ctx = viewer["context"]
            else:
                rig_box["gl"], ctx = _headless_context(model)
            rig_box["rig"] = CameraRig(model, robot_specs.CAMERA_SPECS, ctx, shadows=cfg["camera_shadows"])
        rig_box["rig"].render(data, [name])
        return rig_box["rig"].images[name].copy()

    def snapshot_images():
        """Full-quality frames of every camera from the current state (the viewer's F3 and test snapshots)."""
        return {n: render(n) for n in cam_names}

    loop_api = {"routes": routes, "stop": lambda reason="stop": stop_req.__setitem__(0, reason), "render": render}
    status = None

    print(f"--- entering loop ---")
    logging_active = False
    prev_l = False
    prev_t = False
    step_count = 0
    frame = 0
    base_vx = base_vy = base_wz = 0.0
    t_f0 = pc()

    # ---------------------------------------------------------------
    while True:
      try:
        t_f0 = pc()
        obs = observation(model, data)
        t = data.time
        qw_, qx_, qy_, qz_ = data.qpos[3:7]
        obs.update(tick=frame, timestep=model.opt.timestep, steps_per_frame=steps_per_frame,
                   base_pose=(float(data.qpos[0]), float(data.qpos[1]), base_yaw(data)),
                   pedestal_height=float(data.qpos[ped_qadr]), applied=applied(),
                   cameras=rig.images if rig else None)
        if cfg["on_tick"] is not None:
            status = cfg["on_tick"](obs, loop_api)
            if stop_req[0] is not None:
                break

        # F2: move the arm joints between the keyboard and the teleop source (the old set_teleop)
        if teleop is not None and hk.get("toggle_route") is not None:
            cur_t_key = held(hk["toggle_route"])
            if cur_t_key and not prev_t:
                new = "keyboard" if routes["arms.left"] == "teleop" else "teleop"
                routes["arms.left"] = routes["arms.right"] = new
                teleop["enable"]() if new == "teleop" else teleop["disable"]()
            prev_t = cur_t_key

        # --- Commands: every source steps; each keeps what the router gives it ---
        cmds = []
        for name, src in sources.items():
            out = src["step"](obs)
            if out is None:
                continue
            for cmd in ([out] if isinstance(out, dict) else out):
                if isinstance(cmd, dict) and cmd.get("mode") in ("base", "pedestal", "arms", "idle"):
                    cmd = _filter_by_route(cmd, name, routes)       # a malformed command goes on to validate_command
                if cmd is None:
                    continue
                clean, notes = validate_command(cmd, limits)
                for n in notes:
                    if (name, n) not in msgs_seen:
                        msgs_seen.add((name, n))
                        print(f"[{name}] {n}")
                if clean is not None:
                    cmds.append(clean)
        measure_still()
        exempt = [c for c in cmds if c["mode"] in EXEMPT_SUBSYSTEMS]          # the neck: never held, never exclusive
        cmds = [c for c in cmds if c["mode"] not in EXEMPT_SUBSYSTEMS]
        for cmd in exempt:
            apply_cmd(cmd)
        if neck is not None:                                                  # position targets move at most neck_max_speed
            step_ = neck_max_speed * tick_dt
            hold_qpos_targets[neck["act"]] += np.clip(neck_goal - hold_qpos_targets[neck["act"]], -step_, step_)
        to_apply = exclusive_select(cmds, t) if cfg["exclusive"] else [c for c in cmds if c["mode"] != "idle"]
        if not cfg["exclusive"] and any(c["mode"] == "idle" for c in cmds):
            stop_base()
        for cmd in to_apply:
            apply_cmd(cmd)

        # Project forward velocity into world frame using robot yaw
        base_vx, base_vy, base_wz = twist_to_world_velocity(base_yaw(data), *st["twist"])

        # --- Step physics with velocity drive ---
        t_p0 = pc()
        # Targets are held for the whole frame: write them once as position commands; the MuJoCo
        # servos track them from the live state on every physics step.
        data.ctrl[:] = np.where(is_pos, hold_qpos_targets, 0.0)
        for _ in range(steps_per_frame):
            if base_dof is not None:
                apply_base_velocity(data, base_dof, base_vx, base_vy, base_wz)
            mujoco.mj_step(model, data)
            step_count += 1
            if bench_log is not None and step_count % 75 == 0:
                qw_, qx_, qy_, qz_ = data.qpos[3:7]
                bench_csv.writerow([f"{data.time:.6f}", f"{data.qpos[0]:.9f}", f"{data.qpos[1]:.9f}",
                                    f"{math.degrees(math.atan2(2.0 * (qw_ * qz_ + qx_ * qy_), 1.0 - 2.0 * (qy_ * qy_ + qz_ * qz_))):.9f}",
                                    f"{data.qpos[ped_qadr]:.9f}"] + [f"{data.qpos[a]:.9f}" for a in log_joints]
                                   + ([f"{data.qpos[a]:.9f}" for a in neck["qadr"]] if neck is not None else []))
            if rig is not None and step_count % cam_every == 0:
                t_c0 = pc()
                if cfg["camera_roundrobin"]:
                    rig.render(data, [cam_names[cam_tick % len(cam_names)]])
                    cam_tick += 1
                else:
                    rig.render(data)
                tm["cam"] += pc() - t_c0
        tm["phys"] += pc() - t_p0

        # Logging
        if logging_active:
            logger.record(obs)
        if hk.get("toggle_log") is not None and logger is not None:
            cur_l = held(hk["toggle_log"])
            if cur_l and not prev_l:
                logging_active = not logging_active
                print(f"Logging: {'ON' if logging_active else 'OFF'}")
            prev_l = cur_l

        quit_now = False
        if viewer is not None:
            draw = frame % draw_every == 0
            if draw and irig is not None:
                if (frame // draw_every) % inset_every == 0:
                    t_c0 = pc()
                    irig.render(data, [cam_names[inset_tick % len(cam_names)]])
                    inset_tick += 1
                    tm["inset"] += pc() - t_c0
            res = viewer["frame"]({
                "draw": draw, "draw_every": draw_every, "tick_dt": tick_dt, "snapshot_images": snapshot_images,
                "frame": frame, "time": t, "t_frame_start": t_f0,
                "images": irig.images if irig is not None else (rig.images if rig else {}),
                "base_vel": (base_vx, base_vy, base_wz), "drive_state": ds_state, "targets": hold_qpos_targets,
                "teleop_status": teleop["status"]() if teleop is not None else None,
                "preview_frame": teleop["state"].get("preview_frame") if teleop is not None else None,
                "preview": cfg["preview"], "status": status,
                "neck_deg": [math.degrees(float(data.qpos[a])) for a in neck["qadr"]] if neck is not None else None})
            quit_now = res["quit"]
            yaw_deg = res["yaw_deg"]
        else:
            yaw_deg = math.degrees(base_yaw(data))

        frame += 1
        if tick_ref is not None:
            tick_ref[0] = frame
        if cfg["bench_frames"]:
            if frame == 10:  # discard warm-up
                tm = dict.fromkeys(tm, 0.0)
                t_bench0 = pc()
            elif frame >= 10 + cfg["bench_frames"]:
                n = cfg["bench_frames"]
                wall = pc() - t_bench0
                extra = " ".join(f"{k}={1000 * v / n:.0f}ms" for k, v in (viewer["timers"] if viewer else {}).items())
                print(f"BENCH {n} frames: {1000 * wall / n:.0f} ms/frame "
                      f"({n / wall:.1f} fps) | " + " ".join(f"{k}={1000 * v / n:.0f}ms" for k, v in tm.items()) + " " + extra)
                break
        # --- DEBUG ---
        verbose = (frame <= 10) or (frame % 60 == 0)
        if verbose:
            print(f"  f={frame:5d}  t={t:.2f}  "
                  f"lin={ds_state.get('linear',0):+.2f} ang={ds_state.get('angular',0):+.2f}  "
                  f"vel=[{base_vx:+.2f},{base_vy:+.2f}]  wz={base_wz:+.2f}  "
                  f"yaw={yaw_deg:+.1f}°  "
                  f"jog[L3={hold_qpos_targets[jog_ids['L3']]:+.2f} "
                  f"R1={hold_qpos_targets[jog_ids['R1']]:+.2f} "
                  f"Lg={hold_qpos_targets[jog_ids['Lg']]:.3f} "
                  f"Rg={hold_qpos_targets[jog_ids['Rg']]:.3f}]  "
                  f"pos={data.qpos[0:3].round(3)}")

        if hk.get("quit") is not None and held(hk["quit"]):
            print("ESC pressed")
            break
        if quit_now:                                     # the window was closed
            break

      except Exception as e:
            print(f"EXCEPTION in loop at frame {frame}: {e}")
            import traceback; traceback.print_exc()
            break

    # ---------------------------------------------------------------
    if viewer is not None:
        viewer["finish"]()
    if bench_log is not None:
        bench_log.close()
    print(f"\nLoop exited after {frame} frames.")
    if logging_active and logger is not None and len(logger.trajectory) > 0:
        logger.save()
    for src in sources.values():
        if "cleanup" in src and src.get("started", True):
            try:
                src["cleanup"]()
            except Exception as e:                       # a source that never started has nothing to clean up
                print(f"cleanup of source '{src.get('name')}' failed: {e}")
    if viewer is not None:
        viewer["close"]()
    for gl_ctx in (gl_keepalive, rig_box["gl"]):
        if gl_ctx is not None:
            try:
                gl_ctx.free()                            # avoids an EGL error message at interpreter exit
            except Exception:
                pass
    print("Done.")
    return {"frames": frame, "hold_log": ex["log"], "routes": routes, "stopped_by": stop_req[0]}
