# Code generated by Claude
"""
Episode runner for the beaker-on-hotplate task: one run = reset, stage, hand off to a source under test, judge, log.

    summary = run_episode(make_test_source, model, data, task_cfg=TASK_CFG, staging_cfg=STAGING_CFG, episode_cfg=EPISODE_CFG,
                          viewer=None, out_dir=None, handoff_frame=None, held=None, loop_cfg=None, record_dir=None)

  reset     mj_resetData + the task's object poses; the loop spawns the robot at the task's spawn pose (position and yaw) and
            settles it (nothing is randomized). The same model / data can be reused for any number of episodes.
  staging   the scripted staging source (src/staging_source.py) owns every route (base, pedestal, arms, grippers, neck) until DONE.
  handoff   at DONE the arms and gripper routes switch to the source under test; the base keeps a zero Twist, the pedestal and the neck
            hold (the staging source stays their owner and says nothing). The eagle frame is saved to `handoff_frame`.
  judge     check_success() every tick after HANDOFF only: success ends the episode; so does TIMEOUT (episode_cfg timeout_after_handoff
            of sim time). If staging cannot reach its pose within the tolerances the episode ends at once as STAGING_FAILED.
  log       out_dir/episode_log.csv (state and applied commands at episode_cfg["log_hz"]) and out_dir/episode_summary.json.
Exclusivity is ON in episodes (episode_cfg["exclusive"]); the loop's default stays off elsewhere.

The runner drives src/control_loop.run_loop through its cfg["on_tick"] hook (route switching, end conditions, logging, measurements).
The summary: outcome, per-phase durations (including the two pose-correction phases when they ran), arrival errors, the final in-place turn
angle, the pose corrections (needed or not, error before and after, extended-arm clearances), base drift per phase and after HANDOFF,
minimum base-to-bench clearance during the drive, contacts per phase, the neck framing report at HANDOFF, the holds the loop logged,
and the success-check diagnostics.
"""

import csv
import json
import math
import time
from pathlib import Path

import cv2
import mujoco
import numpy as np

from src import robot_specs
from src.control_loop import ROUTE_KEYS, run_loop
from src.neck import neck_ids
from src.staging_source import make_staging_source
from src.task_beaker_hotplate import apply_task_poses, arm_ids, check_success, wrap
from src.task_config import EPISODE_CFG, STAGING_CFG, SUCCESS_CFG, TASK_CFG

VIEWER_HZ = 60


def _body_set(model, root_name):
    root = model.body(root_name).id
    out = set()
    for b in range(model.nbody):
        c = b
        while c > 0:
            if c == root:
                out.add(b)
                break
            c = int(model.body_parentid[c])
    return out


def run_episode(make_test_source, model, data, task_cfg=TASK_CFG, staging_cfg=STAGING_CFG, episode_cfg=EPISODE_CFG,
                viewer=None, out_dir=None, handoff_frame=None, held=None, loop_cfg=None, record_dir=None):
    wall0 = time.perf_counter()
    mujoco.mj_resetData(model, data)
    apply_task_poses(model, data, task_cfg)

    staging = make_staging_source(model, data, task_cfg, staging_cfg)
    test = make_test_source(model, data)
    sources = {"staging": staging, "test": test}
    routes = {k: "staging" for k in ROUTE_KEYS}
    st = staging["state"]

    # --- geometry used by the measurements ---
    robot_bodies = _body_set(model, "base_link")
    in_robot = np.zeros(model.ngeom, bool)
    for g in range(model.ngeom):
        in_robot[g] = int(model.geom_bodyid[g]) in robot_bodies
    floor = np.array([int(model.geom_bodyid[g]) == 0 for g in range(model.ngeom)])
    is_finger = np.array(["finger" in model.body(int(model.geom_bodyid[g])).name for g in range(model.ngeom)])
    base_names = ["base_link", "right_link", "left_Link", "right_front_link", "right_rear_link", "left_front_link", "left_rear_link"]
    base_geoms = [g for g in range(model.ngeom) if model.body(int(model.geom_bodyid[g])).name in base_names]
    bench_body = model.body("bench").id
    bench_geoms = [g for g in range(model.ngeom) if int(model.geom_bodyid[g]) == bench_body]
    ft = np.zeros(6)
    beaker_adr = int(model.joint("task_beaker_free").qposadr[0])
    sides = ("left", "right")
    arm_act = {s: arm_ids(model, s) for s in sides}
    neck = neck_ids(model, robot_specs.NECK_SPECS)
    ped_qadr = int(model.joint(robot_specs.PEDESTAL_SPECS["joints"][0]).qposadr[0])
    finger_qadr = [int(model.jnt_qposadr[model.actuator_trnid[a, 0]]) for s in sides for a in arm_act[s]["fingers"]]

    # --- bookkeeping ---
    R = {"outcome": None, "handoff_time": None, "success_time": None, "phase": None, "phase_base": {}, "drift": {}, "contacts": {},
         "min_clearance": None, "diag": None, "handoff_base": None, "t_end": None}
    log_file, log_csv, next_log = None, None, [0.0]
    if out_dir is not None:
        Path(out_dir).mkdir(parents=True, exist_ok=True)
        log_file = open(Path(out_dir) / "episode_log.csv", "w", newline="")
        log_csv = csv.writer(log_file)
        log_csv.writerow(["sim_time", "phase", "base_x", "base_y", "base_yaw_deg", "pedestal_m"]
                         + [f"{s}_joint{i}" for s in sides for i in range(1, 8)] + [f"{s}_finger{k}" for s in sides for k in (1, 2)]
                         + [f"neck_{n}" for n in (neck["names"] if neck else [])] + ["beaker_x", "beaker_y", "beaker_z"]
                         + ["cmd_twist_lin", "cmd_twist_ang", "cmd_pedestal"] + [f"cmd_{task_cfg['arm']}_joint{i}" for i in range(1, 8)]
                         + [f"cmd_{task_cfg['arm']}_gripper"] + [f"cmd_neck_{n}" for n in (neck["names"] if neck else [])])

    def contacts_now():
        n = data.ncon
        if n == 0:
            return []
        g1, g2 = data.contact.geom1[:n], data.contact.geom2[:n]
        mask = (in_robot[g1] != in_robot[g2]) & ~floor[g1] & ~floor[g2]
        mask |= in_robot[g1] & in_robot[g2] & ~(is_finger[g1] & is_finger[g2]) & (data.contact.dist[:n] < 0)
        return [(model.geom(int(a)).name or model.body(int(model.geom_bodyid[a])).name,
                 model.geom(int(b)).name or model.body(int(model.geom_bodyid[b])).name) for a, b in zip(g1[mask], g2[mask])]

    def on_tick(obs, loop):
        t = obs["time"]
        phase = "DONE" if st["done"] else st["phase"]
        x, y, yaw = obs["base_pose"]
        # phase change: remember the base pose it started from (drift is measured against it)
        if phase != R["phase"]:
            R["phase"] = phase
            R["phase_base"][phase] = (x, y, yaw)
            R["drift"].setdefault(phase, {"max_pos": 0.0, "max_yaw": 0.0})
        # routes at DONE
        if st["done"] and R["handoff_time"] is None:
            R["handoff_time"] = t
            R["handoff_base"] = (x, y, yaw)
            for k in ("arms.left", "arms.right", "gripper.left", "gripper.right"):
                loop["routes"][k] = "test"
            if handoff_frame is not None:
                Path(handoff_frame).parent.mkdir(parents=True, exist_ok=True)
                cv2.imwrite(str(handoff_frame), cv2.cvtColor(loop["render"]("eagle_cam"), cv2.COLOR_RGB2BGR))
            print(f"[episode] t={t:.2f} s: HANDOFF reached; arms and grippers now belong to the source under test ('{test['name']}')")
        obs["episode"] = {"phase": phase, "handoff_time": R["handoff_time"]}
        # measurements: drift per phase, contacts, clearance during DRIVE
        if phase in R["drift"] and phase in R["phase_base"] and phase != "DRIVE" and not phase.startswith("CORRECT"):
            x0, y0, yaw0 = R["phase_base"][phase]
            d = R["drift"][phase]
            d["max_pos"] = max(d["max_pos"], math.hypot(x - x0, y - y0))
            d["max_yaw"] = max(d["max_yaw"], abs(wrap(yaw - yaw0)))
            d["net_pos"], d["net_yaw"] = math.hypot(x - x0, y - y0), wrap(yaw - yaw0)
        for pair in contacts_now():
            c = R["contacts"].setdefault(phase, {}).setdefault(pair, {"first": t, "last": t, "ticks": 0})
            c["last"], c["ticks"] = t, c["ticks"] + 1
        if phase == "DRIVE":
            c = min(mujoco.mj_geomDistance(model, data, a, b, 2.0, ft) for a in base_geoms for b in bench_geoms)
            R["min_clearance"] = c if R["min_clearance"] is None else min(R["min_clearance"], c)
        # log at log_hz
        if log_csv is not None and t >= next_log[0] - 1e-9:
            next_log[0] = (math.floor(t * episode_cfg["log_hz"] + 1e-9) + 1) / episode_cfg["log_hz"]
            ap = obs["applied"]
            q = obs["joint_angles"]
            log_csv.writerow([f"{t:.4f}", phase, f"{x:.9f}", f"{y:.9f}", f"{math.degrees(yaw):.9f}", f"{obs['pedestal_height']:.9f}"]
                             + [f"{q[a]:.9f}" for s in sides for a in arm_act[s]["qadr"]] + [f"{q[a]:.9f}" for a in finger_qadr]
                             + ([f"{q[a]:.9f}" for a in neck["qadr"]] if neck else []) + [f"{q[beaker_adr + k]:.9f}" for k in range(3)]
                             + [f"{ap['twist'][0]:.9f}", f"{ap['twist'][1]:.9f}", f"{ap['pedestal']:.9f}"]
                             + [f"{v:.9f}" for v in ap["arm_targets"][task_cfg["arm"]]] + [f"{ap['gripper'][task_cfg['arm']]:.9f}"]
                             + ([f"{ap['neck_goal'][n]:.9f}" for n in neck["names"]] if neck else []))
        # end conditions
        if st["error"]:
            R["outcome"], R["t_end"] = "STAGING_FAILED", t
            loop["stop"]("staging_failed")
        elif R["handoff_time"] is not None:
            ok, diag = check_success(model, data, SUCCESS_CFG)
            R["diag"] = diag
            if ok:
                R["outcome"], R["success_time"], R["t_end"] = "SUCCESS", t, t
                loop["stop"]("success")
            elif t - R["handoff_time"] >= episode_cfg["timeout_after_handoff"]:
                R["outcome"], R["t_end"] = "TIMEOUT", t
                loop["stop"]("timeout")
        return f"{phase}" + (f"  (+{t - R['handoff_time']:.0f} s)" if R["handoff_time"] is not None else "") + (f"  {R['outcome']}" if R["outcome"] else "")

    physics_hz = 1.0 / model.opt.timestep
    spf = max(1, round(physics_hz / VIEWER_HZ))
    cfg = {"source_hz": physics_hz / spf, "spawn_pos": [task_cfg["spawn_xy"][0], task_cfg["spawn_xy"][1], episode_cfg["spawn_z"]],
           "spawn_yaw": task_cfg["spawn_yaw"], "routes": routes, "exclusive": episode_cfg["exclusive"], "on_tick": on_tick,
           "cameras": False, "camera_roundrobin": True, "held": held,
           "hotkeys": {"quit": __import__("glfw").KEY_ESCAPE} if viewer is not None else {}}
    if record_dir is not None:      # src/run_record.py: replayable with src/replay.py (labels = the phases)
        cfg.update(record_run=str(record_dir), record_meta={"model": {"kind": "task", "task_cfg": task_cfg},
                                                            "episode": {"staging_cfg": staging_cfg, "episode_cfg": episode_cfg}})
    cfg.update(loop_cfg or {})
    result = run_loop(model, data, sources, cfg, viewer=viewer)
    if log_file is not None:
        log_file.close()
    if R["outcome"] is None:
        R["outcome"], R["t_end"] = ("ABORTED" if result["stopped_by"] is None else result["stopped_by"].upper()), data.time

    # --- the summary ---
    phases = {k: v for k, v in st["phases"].items()}
    dur = {k: (v["end"] - v["start"]) if v["end"] is not None else None for k, v in phases.items() if k != "DONE"}
    final = None
    if R["handoff_base"] is not None:
        gx, gy = task_cfg["staging_xy"]
        ex, ey = gx - R["handoff_base"][0], gy - R["handoff_base"][1]
        gyaw = task_cfg["staging_yaw"]
        final = {"pos_err_mm": 1000 * math.hypot(ex, ey), "yaw_err_deg": math.degrees(wrap(R["handoff_base"][2] - gyaw)),
                 "along_mm": 1000 * (ex * math.cos(gyaw) + ey * math.sin(gyaw)),          # > 0: short of the staging pose, farther from the bench
                 "lateral_mm": 1000 * (-ex * math.sin(gyaw) + ey * math.cos(gyaw))}       # > 0: the staging pose is to the base's left
    drift = {k: {"max_pos_mm": 1000 * v["max_pos"], "max_yaw_deg": math.degrees(v["max_yaw"]),
                 "net_pos_mm": 1000 * v.get("net_pos", 0.0), "net_yaw_deg": math.degrees(v.get("net_yaw", 0.0))}
             for k, v in R["drift"].items() if k != "DRIVE" and not k.startswith("CORRECT")}
    rep = st["framing_report"]
    summary = {
        "outcome": R["outcome"], "staging_error": st["error"], "sim_time_end": R["t_end"], "handoff_time": R["handoff_time"],
        "time_after_handoff_to_end": None if R["handoff_time"] is None else R["t_end"] - R["handoff_time"],
        "phase_durations_s": dur, "phase_times": {k: [v["start"], v["end"]] for k, v in phases.items()},
        "arrival_at_end_of_drive": ({"pos_err_mm": 1000 * st["arrival"]["pos_err"], "yaw_err_deg": st["arrival"]["yaw_err_deg"], "ok": st["arrival"]["ok"]}
                                    if st["arrival"] else None),
        "base_pose_error_at_handoff": final,
        "first_turn_deg": st["first_turn_deg"], "final_in_place_turn_deg": st["final_turn_deg"],
        "planned_final_turn_deg": st["planned_final_turn_deg"], "drive_reapproaches": st["reapproaches"],
        "pose_corrections": st["corrections"], "base_drift": drift, "min_base_to_bench_clearance_during_drive_mm": None if R["min_clearance"] is None else 1000 * R["min_clearance"],
        "contacts_by_phase": {k: [{"pair": list(p), "first_s": v["first"], "last_s": v["last"], "ticks": v["ticks"]} for p, v in d.items()]
                              for k, d in R["contacts"].items()},
        "neck_framing_report": rep, "holds": result["hold_log"], "success_check": R["diag"], "log_rows_hz": episode_cfg["log_hz"],
        "wall_seconds": time.perf_counter() - wall0,
    }
    if out_dir is not None:
        (Path(out_dir) / "episode_summary.json").write_text(json.dumps(summary, indent=2, default=lambda o: o.tolist() if hasattr(o, "tolist") else str(o)))
    return summary
