# Code generated by Claude
"""
Episode runner for the beaker-on-hotplate task. It does what a policy must not do itself: reset the scene, check success, enforce the
timeouts, save the log and the summary. Everything else is the task policy's (src/task_policy.py) or the controller's (src/control_loop.py).

    summary = run_episode(make_arm_stage, model, data, task_cfg=TASK_CFG, staging_cfg=STAGING_CFG, episode_cfg=EPISODE_CFG, mode="auto",
                          viewer=None, out_dir=None, handoff_frame=None, held=None, loop_cfg=None, record_dir=None, extra_sources=None)

  reset     mj_resetData + the task's object poses; the loop spawns the robot at the task's spawn pose (position and yaw) and settles it
            (nothing is randomized). The same model / data can be reused for any number of episodes.
  mode      "auto": ONE task policy (staging stage, then the arm stage made by make_arm_stage(model, data); None = hold) owns the whole task. It
            may ask for operator control (the controller then switches to teleop at once). In the viewer F9 takes over from the
            policy, Enter hands control back (the policy continues its stage), Delete aborts (ABORTED_BY_OPERATOR); the last two
            only act while the operator has control.
            "teleop": no policy; the operator (keyboard) drives from the start and time 0 counts as the handoff.
  handoff   the policy's staging stage reaching DONE (teleop start: the first tick). The eagle frame is saved to `handoff_frame`.
  judge     check_success() every tick after the handoff, whoever is in charge: success ends the episode (SUCCESS, with operator_assisted
            true if the operator had control at any time). The operator can end it at once with the abort key (ABORTED_BY_OPERATOR; only while
            the operator has control). TIMEOUT: episode_cfg["timeout_after_handoff"] of sim time under AUTO control (paused
            while the operator has control), or episode_cfg["operator_timeout"] of sim time under OPERATOR control (OPERATOR_NO_RESPONSE instead of TIMEOUT if the policy had requested
            the operator and no key was pressed at all). If staging cannot reach its
            pose the policy reports an error and the episode ends at once as STAGING_FAILED.
  log       out_dir/episode_log.csv (state, mode and applied commands at episode_cfg["log_hz"]) and out_dir/episode_summary.json.
Exclusivity is ON in episodes (episode_cfg["exclusive"]); the loop's default stays off elsewhere. `extra_sources` (test only): a factory
make(model, data) -> {name: source} of additional sources, e.g. the kick source of the correction test.

The runner drives src/control_loop.run_loop through its cfg["on_tick"] hook (success, timeouts, contacts, the log). The summary: outcome,
the staging stage's own report (phase durations, arrival errors, pose corrections, drift, clearance, pose error at HANDOFF, neck framing),
contacts per phase (phase "OPERATOR" while the operator has control), the mode switches, operator_time_s, the holds the loop logged, and the
success-check diagnostics.
"""

import csv
import json
import math
import time
from pathlib import Path

import cv2
import glfw
import mujoco
import numpy as np

from src import robot_specs
from src.control_loop import run_loop
from src.keyboard_source import DRIVE_CFG, make_keyboard_source
from src.neck import neck_ids
from src.task_beaker_hotplate import apply_task_poses, arm_ids, check_success, framing_points
from src.task_config import EPISODE_CFG, STAGING_CFG, SUCCESS_CFG, TASK_CFG
from src.task_policy import make_task_policy

VIEWER_HZ = 60


def _body_set(model, root_name):
    root = model.body(root_name).id
    out = set()
    for b in range(model.nbody):
        c = b
        while c > 0:
            if c == root:
                out.add(b)
                break
            c = int(model.body_parentid[c])
    return out


def run_episode(make_arm_stage, model, data, task_cfg=TASK_CFG, staging_cfg=STAGING_CFG, episode_cfg=EPISODE_CFG, mode="auto",
                viewer=None, out_dir=None, handoff_frame=None, held=None, loop_cfg=None, record_dir=None, extra_sources=None):
    wall0 = time.perf_counter()
    if mode not in ("auto", "teleop"):
        raise ValueError(f"mode must be 'auto' or 'teleop', not {mode!r}")
    mujoco.mj_resetData(model, data)
    apply_task_poses(model, data, task_cfg)

    physics_hz = 1.0 / model.opt.timestep
    spf = max(1, round(physics_hz / VIEWER_HZ))
    tick_dt = spf * model.opt.timestep
    held_fn = held or (lambda code: False)
    ped = model.actuator(robot_specs.PEDESTAL_SPECS["actuator_name"]).id
    sources, policy = {}, None
    if mode == "auto":
        policy = make_task_policy(model, data, task_cfg, staging_cfg, make_arm_stage(model, data) if make_arm_stage else None)
        sources["policy"] = policy
    sources["keyboard"] = make_keyboard_source(model, held_fn, DRIVE_CFG, robot_specs.PEDESTAL_SPECS["jog_speed"] * tick_dt,
                                               tuple(model.actuator_ctrlrange[ped]), data=data, neck_specs=robot_specs.NECK_SPECS,
                                               points_fn=framing_points)
    sources.update(extra_sources(model, data) if extra_sources else {})

    # --- geometry used by the contact measurement ---
    robot_bodies = _body_set(model, "base_link")
    in_robot = np.zeros(model.ngeom, bool)
    for g in range(model.ngeom):
        in_robot[g] = int(model.geom_bodyid[g]) in robot_bodies
    floor = np.array([int(model.geom_bodyid[g]) == 0 for g in range(model.ngeom)])
    is_finger = np.array(["finger" in model.body(int(model.geom_bodyid[g])).name for g in range(model.ngeom)])
    beaker_adr = int(model.joint("task_beaker_free").qposadr[0])
    sides = ("left", "right")
    arm_act = {s: arm_ids(model, s) for s in sides}
    neck = neck_ids(model, robot_specs.NECK_SPECS)
    finger_qadr = [int(model.jnt_qposadr[model.actuator_trnid[a, 0]]) for s in sides for a in arm_act[s]["fingers"]]

    # --- bookkeeping ---
    R = {"outcome": None, "handoff_time": None, "success_time": None, "contacts": {}, "diag": None, "t_end": None, "timeout_kind": None,
         "auto_ticks": 0, "operator_ticks": 0}
    log_file, log_csv, next_log = None, None, [0.0]
    if out_dir is not None:
        Path(out_dir).mkdir(parents=True, exist_ok=True)
        log_file = open(Path(out_dir) / "episode_log.csv", "w", newline="")
        log_csv = csv.writer(log_file)
        log_csv.writerow(["sim_time", "phase", "mode", "base_x", "base_y", "base_yaw_deg", "pedestal_m"]
                         + [f"{s}_joint{i}" for s in sides for i in range(1, 8)] + [f"{s}_finger{k}" for s in sides for k in (1, 2)]
                         + [f"neck_{n}" for n in (neck["names"] if neck else [])] + ["beaker_x", "beaker_y", "beaker_z"]
                         + ["cmd_twist_lin", "cmd_twist_ang", "cmd_pedestal"] + [f"cmd_{task_cfg['arm']}_joint{i}" for i in range(1, 8)]
                         + [f"cmd_{task_cfg['arm']}_gripper"] + [f"cmd_neck_{n}" for n in (neck["names"] if neck else [])]
                         + [f"cmd_{task_cfg['arm']}_grip_max_force_N", f"{task_cfg['arm']}_finger_force_N"])

    def contacts_now():
        n = data.ncon
        if n == 0:
            return []
        g1, g2 = data.contact.geom1[:n], data.contact.geom2[:n]
        mask = (in_robot[g1] != in_robot[g2]) & ~floor[g1] & ~floor[g2]
        mask |= in_robot[g1] & in_robot[g2] & ~(is_finger[g1] & is_finger[g2]) & (data.contact.dist[:n] < 0)
        return [(model.geom(int(a)).name or model.body(int(model.geom_bodyid[a])).name,
                 model.geom(int(b)).name or model.body(int(model.geom_bodyid[b])).name) for a, b in zip(g1[mask], g2[mask])]

    def on_tick(obs, loop):
        t = obs["time"]
        ps = obs.get("policy")                                    # the task policy's status (None in a teleop-start episode)
        cur = obs["mode"]
        phase = "OPERATOR" if cur == "teleop" else ps["phase"]
        x, y, yaw = obs["base_pose"]
        if R["handoff_time"] is None and (ps is None or ps["handoff"]):
            R["handoff_time"] = t
            if policy is not None and handoff_frame is not None:
                Path(handoff_frame).parent.mkdir(parents=True, exist_ok=True)
                cv2.imwrite(str(handoff_frame), cv2.cvtColor(loop["render"]("eagle_cam"), cv2.COLOR_RGB2BGR))
            print(f"[episode] t={t:.2f} s: " + ("HANDOFF reached; the policy's arm stage is in charge of the arms"
                                                 if policy is not None else "teleop start: the operator is in charge from the beginning"))
        for pair in contacts_now():
            c = R["contacts"].setdefault(phase, {}).setdefault(pair, {"first": t, "last": t, "ticks": 0})
            c["last"], c["ticks"] = t, c["ticks"] + 1
        # log at log_hz
        if log_csv is not None and t >= next_log[0] - 1e-9:
            next_log[0] = (math.floor(t * episode_cfg["log_hz"] + 1e-9) + 1) / episode_cfg["log_hz"]
            ap = obs["applied"]
            q = obs["joint_angles"]
            log_csv.writerow([f"{t:.4f}", phase, cur, f"{x:.9f}", f"{y:.9f}", f"{math.degrees(yaw):.9f}", f"{obs['pedestal_height']:.9f}"]
                             + [f"{q[a]:.9f}" for s in sides for a in arm_act[s]["qadr"]] + [f"{q[a]:.9f}" for a in finger_qadr]
                             + ([f"{q[a]:.9f}" for a in neck["qadr"]] if neck else []) + [f"{q[beaker_adr + k]:.9f}" for k in range(3)]
                             + [f"{ap['twist'][0]:.9f}", f"{ap['twist'][1]:.9f}", f"{ap['pedestal']:.9f}"]
                             + [f"{v:.9f}" for v in ap["arm_targets"][task_cfg["arm"]]] + [f"{ap['gripper'][task_cfg['arm']]:.9f}"]
                             + ([f"{ap['neck_goal'][n]:.9f}" for n in neck["names"]] if neck else [])
                             + [f"{ap['gripper_force'][task_cfg['arm']]:.9f}", f"{float(np.mean(np.abs(data.actuator_force[arm_act[task_cfg['arm']]['fingers']]))):.9f}"])
        # end conditions
        auto_t, op_t = R["auto_ticks"] * tick_dt, R["operator_ticks"] * tick_dt
        if ps is not None and ps["error"]:
            R["outcome"], R["t_end"] = "STAGING_FAILED", t
            loop["stop"]("staging_failed")
        elif R["handoff_time"] is not None:
            ok, diag = check_success(model, data, SUCCESS_CFG)
            R["diag"] = diag
            if ok:
                R["outcome"], R["success_time"], R["t_end"] = "SUCCESS", t, t
                loop["stop"]("success")
            elif cur == "auto" and auto_t >= episode_cfg["timeout_after_handoff"] - 1e-6:
                R["outcome"], R["t_end"], R["timeout_kind"] = "TIMEOUT", t, "auto"
                loop["stop"]("timeout")
            elif cur == "teleop" and op_t >= episode_cfg["operator_timeout"] - 1e-6:
                if obs["operator"]["requested"] and not obs["operator"]["responded"]:      # the policy asked and nobody did anything
                    R["outcome"], R["t_end"], R["timeout_kind"] = "OPERATOR_NO_RESPONSE", t, "operator"
                    loop["stop"]("operator_no_response")
                else:
                    R["outcome"], R["t_end"], R["timeout_kind"] = "TIMEOUT", t, "operator"
                    loop["stop"]("timeout")
        if R["handoff_time"] is not None and R["outcome"] is None:   # the clocks: auto time is paused while the operator has control
            R["auto_ticks" if cur == "auto" else "operator_ticks"] += 1
        return (f"{phase}" + (f"  (+{auto_t:.0f} s)" if R["handoff_time"] is not None else "") + (f"  operator {op_t:.0f} s" if op_t else "")
                + (f"  {R['outcome']}" if R["outcome"] else ""))

    cfg = {"source_hz": physics_hz / spf, "spawn_pos": [task_cfg["spawn_xy"][0], task_cfg["spawn_xy"][1], episode_cfg["spawn_z"]],
           "spawn_yaw": task_cfg["spawn_yaw"], "exclusive": episode_cfg["exclusive"], "on_tick": on_tick,
           "mode": mode, "auto_source": "policy" if policy is not None else None,
           "cameras": False, "camera_roundrobin": True, "held": held,
           "hotkeys": {"take_over": glfw.KEY_F9, "hand_back": (glfw.KEY_ENTER, glfw.KEY_KP_ENTER), "abort": glfw.KEY_DELETE,
                       **({"quit": glfw.KEY_ESCAPE} if viewer is not None else {})}}
    if record_dir is not None:      # src/run_record.py: replayable with src/replay.py (labels = the phases)
        cfg.update(record_run=str(record_dir), record_meta={"model": {"kind": "task", "task_cfg": task_cfg}, "mode": mode,
                                                            "episode": {"staging_cfg": staging_cfg, "episode_cfg": episode_cfg}})
    cfg.update(loop_cfg or {})
    result = run_loop(model, data, sources, cfg, viewer=viewer)
    if log_file is not None:
        log_file.close()
    if R["outcome"] is None:
        R["outcome"], R["t_end"] = ("ABORTED" if result["stopped_by"] is None else result["stopped_by"].upper()), data.time

    # --- the summary ---
    summary = {
        "outcome": R["outcome"], "timeout_kind": R["timeout_kind"], "mode_at_start": mode, "sim_time_end": R["t_end"], "handoff_time": R["handoff_time"],
        "time_after_handoff_to_end": None if R["handoff_time"] is None else R["t_end"] - R["handoff_time"],
        "auto_time_after_handoff_s": R["auto_ticks"] * tick_dt, "operator_time_s": R["operator_ticks"] * tick_dt,
        "operator_assisted": R["operator_ticks"] > 0 and R["outcome"] == "SUCCESS", "mode_switches": result["mode_log"],
        **(policy["report"]() if policy is not None else {}),
        "contacts_by_phase": {k: [{"pair": list(p), "first_s": v["first"], "last_s": v["last"], "ticks": v["ticks"]} for p, v in d.items()]
                              for k, d in R["contacts"].items()},
        "holds": result["hold_log"], "success_check": R["diag"], "log_rows_hz": episode_cfg["log_hz"],
        "wall_seconds": time.perf_counter() - wall0,
    }
    if out_dir is not None:
        (Path(out_dir) / "episode_summary.json").write_text(json.dumps(summary, indent=2, default=lambda o: o.tolist() if hasattr(o, "tolist") else str(o)))
    return summary
