# Code generated by Claude
"""
TEST-ONLY command sources for exercising src/episode_runner.py. They are not task policies.

    make_idle_source()                          commands nothing: after HANDOFF the arms hold. Expected episode outcome: TIMEOUT.
    make_cheat_source(model, data, delay_s=2.0) CHEATS: delay_s after HANDOFF it teleports the beaker, upright, onto the hotplate through
                                                its freejoint. Only tests the runner's success path. Expected outcome: SUCCESS.

    make_kick_source(model, data, phase, delay_s, along_mm, lateral_mm, yaw_deg)
                                                TEST ONLY: delay_s into `phase` it displaces the base (teleports it by along_mm along the
                                                staging heading, lateral_mm to the left, yaw_deg) to exercise the pose-correction steps.

A test source is given to the runner as a factory make(model, data) -> source dict. The runner publishes
obs["episode"] = {"phase", "handoff_time" (None before HANDOFF)}, which is what these read.
"""

import mujoco
import numpy as np

from src.task_config import TASK_CFG


def make_idle_source():
    return {"name": "idle", "step": lambda obs: None, "state": {}}


def make_cheat_source(model, data, delay_s=2.0, task_cfg=TASK_CFG):
    jq = int(model.joint("task_beaker_free").qposadr[0])
    jv = int(model.joint("task_beaker_free").dofadr[0])
    state = {"teleported_at": None}

    def step(obs):
        ep = obs.get("episode")
        if state["teleported_at"] is None and ep and ep["handoff_time"] is not None and obs["time"] - ep["handoff_time"] >= delay_s:
            top = data.site("hotplate_top").xpos
            data.qpos[jq:jq + 7] = [top[0], top[1], top[2] + 0.002, 1, 0, 0, 0]      # the beaker's origin is its bottom centre
            data.qvel[jv:jv + 6] = 0.0
            mujoco.mj_forward(model, data)
            state["teleported_at"] = obs["time"]
            print(f"[cheat] t={obs['time']:.2f} s: beaker teleported onto the hotplate (TEST ONLY)")
        return None

    return {"name": "cheat", "step": step, "state": state}


def make_kick_source(model, data, phase, delay_s, along_mm, lateral_mm, yaw_deg, task_cfg=TASK_CFG):
    """Test only: displace the base once, delay_s after the staging source entered `phase`. along > 0 = toward the bench (the staging heading)."""
    import math
    state = {"kicked_at": None, "phase_start": None}
    gyaw = task_cfg["staging_yaw"]

    def step(obs):
        ep = obs.get("episode")
        if state["kicked_at"] is not None or not ep:
            return None
        if ep["phase"] != phase:
            state["phase_start"] = None
            return None
        if state["phase_start"] is None:
            state["phase_start"] = obs["time"]
        if obs["time"] - state["phase_start"] >= delay_s:
            a, l = along_mm / 1000.0, lateral_mm / 1000.0
            data.qpos[0] += a * math.cos(gyaw) - l * math.sin(gyaw)
            data.qpos[1] += a * math.sin(gyaw) + l * math.cos(gyaw)
            yaw = 2.0 * math.atan2(data.qpos[6], data.qpos[3]) + math.radians(yaw_deg)
            data.qpos[3:7] = [math.cos(yaw / 2), 0.0, 0.0, math.sin(yaw / 2)]
            mujoco.mj_forward(model, data)
            state["kicked_at"] = obs["time"]
            print(f"[kick] t={obs['time']:.2f} s in {phase}: base displaced by {along_mm:+.0f} mm along, {lateral_mm:+.0f} mm sideways, {yaw_deg:+.1f} deg (TEST ONLY)")
        return None

    return {"name": "kick", "step": step, "state": state}
