# Code generated by Claude
"""
TEST-ONLY command sources for exercising src/episode_runner.py. They are not task policies.

    make_idle_source()                          commands nothing: after HANDOFF the arms hold. Expected episode outcome: TIMEOUT.
    make_cheat_source(model, data, delay_s=2.0) CHEATS: delay_s after HANDOFF it teleports the beaker, upright, onto the hotplate through
                                                its freejoint. Only tests the runner's success path. Expected outcome: SUCCESS.

A test source is given to the runner as a factory make(model, data) -> source dict. The runner publishes
obs["episode"] = {"phase", "handoff_time" (None before HANDOFF)}, which is what these read.
"""

import mujoco
import numpy as np

from src.task_config import TASK_CFG


def make_idle_source():
    return {"name": "idle", "step": lambda obs: None, "state": {}}


def make_cheat_source(model, data, delay_s=2.0, task_cfg=TASK_CFG):
    jq = int(model.joint("task_beaker_free").qposadr[0])
    jv = int(model.joint("task_beaker_free").dofadr[0])
    state = {"teleported_at": None}

    def step(obs):
        ep = obs.get("episode")
        if state["teleported_at"] is None and ep and ep["handoff_time"] is not None and obs["time"] - ep["handoff_time"] >= delay_s:
            top = data.site("hotplate_top").xpos
            data.qpos[jq:jq + 7] = [top[0], top[1], top[2] + 0.002, 1, 0, 0, 0]      # the beaker's origin is its bottom centre
            data.qvel[jv:jv + 6] = 0.0
            mujoco.mj_forward(model, data)
            state["teleported_at"] = obs["time"]
            print(f"[cheat] t={obs['time']:.2f} s: beaker teleported onto the hotplate (TEST ONLY)")
        return None

    return {"name": "cheat", "step": step, "state": state}
