# Code generated by Claude
"""
The GLFW / MuJoCo viewer of experiments/combined_controller.py, moved here: window, 3rd-person camera follow, HUD,
camera insets, snapshots, viewer recording, key polling and frame pacing. The code is the old code; only its packaging is
new. The viewer is a plain dict of callables, created by the launcher and passed to control_loop.run_loop():

    viewer = make_glfw_viewer(model, data, vcfg)
    viewer["context"]            MjrContext of the window; the loop's camera rig renders through it
    viewer["key_down"](code)     is the GLFW key down right now (the launcher adds the CC_BENCH_KEYS injection)
    viewer["set_held"](held)     the launcher's held(code), used for the F3 / F4 / F6 keys
    viewer["frame"](info)        draw one frame; returns {"quit": bool}   (info: see run_loop)
    viewer["finish"]()           stop an active recording (prints), viewer["close"]() terminate GLFW
    viewer["timers"]             render / hud_insets / swap_poll seconds, for the CC_BENCH_FRAMES report

vcfg (all from the launcher): win, vsync, view_shadows, shadowsize, hud, insets, record, snapshot_every, snapshot_dir,
bench_snap_dir, bench_snap_frame, finish, roundrobin, viewer_hz, record_fps, has_teleop.
"""

import csv
import math
import time
import time as _time
from pathlib import Path

import cv2
import glfw
import mujoco
import numpy as np

from src import robot_specs

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CAMERA_SNAPSHOT_DIR = "data/camera_snapshots"
CAM_DISTANCE = 3.5
CAM_ELEVATION = -45
FOVY_DEG = 90


class ViewerRecorder:
    """Records the viewer image to an MP4 and writes a CSV row per video frame.

    One CSV row is written for every video frame (column `video_frame` is the
    frame index), as the recording goes, and flushed every 30 rows, so the
    joint trajectory can be compared across frames and survives a crash. The
    MP4 plays at `fps` = frames per second of SIM time (physics rate / physics
    steps per viewer frame), so playback runs at real simulated speed however
    slowly the viewer ran on the VM.
    """

    def __init__(self, directory, fps, columns):
        self.directory = Path(directory)
        self.fps = float(fps)
        self.columns = list(columns)
        self.writer = None
        self.csv_file = None
        self.csv = None
        self.frames = 0
        self.size = None
        self.paths = None

    @property
    def active(self):
        return self.writer is not None

    def start(self, width, height):
        self.directory.mkdir(parents=True, exist_ok=True)
        stamp = time.strftime("%Y%m%d_%H%M%S")
        self.paths = (self.directory / f"viewer_{stamp}.mp4",
                      self.directory / f"viewer_{stamp}_joints.csv")
        # mp4v wants even dimensions
        self.size = (width & ~1, height & ~1)
        self.writer = cv2.VideoWriter(
            str(self.paths[0]), cv2.VideoWriter_fourcc(*"mp4v"), self.fps, self.size)
        if not self.writer.isOpened():
            self.writer = None
            raise RuntimeError(f"could not open video writer for {self.paths[0]}")
        self.csv_file = open(self.paths[1], "w", newline="")
        self.csv = csv.writer(self.csv_file)
        self.csv.writerow(["video_frame"] + self.columns)
        self.frames = 0

    def write(self, rgb_bottom_up, values):
        """Add one video frame (RGB, OpenGL bottom-up rows) and one CSV row."""
        img = cv2.cvtColor(np.flipud(rgb_bottom_up), cv2.COLOR_RGB2BGR)
        if (img.shape[1], img.shape[0]) != self.size:  # window resized mid-recording
            img = cv2.resize(img, self.size, interpolation=cv2.INTER_AREA)
        self.writer.write(img[:self.size[1], :self.size[0]])
        self.csv.writerow([self.frames] + [f"{v:.6f}" for v in values])
        self.frames += 1
        if self.frames % 30 == 0:
            self.csv_file.flush()

    def stop(self):
        """Finish the files; returns (mp4 path, csv path, frames)."""
        if not self.active:
            return None
        self.writer.release()
        self.csv_file.close()
        self.writer = self.csv_file = self.csv = None
        return (*self.paths, self.frames)


def make_glfw_viewer(model, data, vcfg):
    show_hud = vcfg.get("hud", True)
    show_insets = vcfg.get("insets", True)
    viewer_hz = vcfg.get("viewer_hz", 60)

    # --- Snapshots (press F4 in the MuJoCo window, or --snapshot-every N) ---
    snap_dir = Path(vcfg["snapshot_dir"]) if vcfg.get("snapshot_dir") else PROJECT_ROOT / "snapshots"
    snapshot_every = vcfg.get("snapshot_every", 0.0)
    snap_state = {"last": _time.time(), "p_down": False}
    hud_state = {"last": _time.time(), "ms": 0.0}
    inset_cache = {}
    state = {"held": lambda code: False, "prev_c": False, "prev_r": False}

    def save_snapshot(rgb, preview_frame):
        snap_dir.mkdir(parents=True, exist_ok=True)
        stamp = _time.strftime("%H%M%S")
        cv2.imwrite(str(snap_dir / f"sim_{stamp}.png"),
                    cv2.cvtColor(np.flipud(rgb), cv2.COLOR_RGB2BGR))
        pf = preview_frame
        if pf is not None:
            cv2.imwrite(str(snap_dir / f"camera_{stamp}.png"), pf)
        print(f"Snapshot saved: {snap_dir}/sim_{stamp}.png"
              f"{' + camera' if pf is not None else ''}")

    # --- GLFW ---
    glfw.set_error_callback(
        lambda err, desc: print(f"GLFW error {err}: {desc}"))
    if not glfw.init():
        raise RuntimeError("Could not initialise GLFW")
    window = glfw.create_window(*vcfg["win"], "Combined Controller", None, None)
    if not window:
        glfw.terminate()
        raise RuntimeError("GLFW window creation failed")
    glfw.make_context_current(window)
    glfw.swap_interval(vcfg["vsync"])

    model.vis.global_.fovy = FOVY_DEG
    cam = mujoco.MjvCamera()
    opt = mujoco.MjvOption()
    mujoco.mjv_defaultCamera(cam)
    mujoco.mjv_defaultOption(opt)
    cam.distance  = CAM_DISTANCE
    cam.elevation = CAM_ELEVATION
    cam.azimuth   = 90

    scene_vis = mujoco.MjvScene(model, maxgeom=10_000)
    if not vcfg["view_shadows"]:
        # The VM GPU renders this scene at ~5 fps with shadows/reflections,
        # too slow to drive or teleoperate the robot.
        scene_vis.flags[mujoco.mjtRndFlag.mjRND_SHADOW] = 0
        scene_vis.flags[mujoco.mjtRndFlag.mjRND_REFLECTION] = 0
    if vcfg.get("shadowsize"):
        model.vis.quality.shadowsize = vcfg["shadowsize"]
    context = mujoco.MjrContext(model, mujoco.mjtFontScale.mjFONTSCALE_150)

    base_body_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "base_link")
    if base_body_id < 0:
        base_body_id = 1
    cam_dir = PROJECT_ROOT / CAMERA_SNAPSHOT_DIR
    tm = {"render": 0.0, "hud_insets": 0.0, "swap_poll": 0.0}
    pc = _time.perf_counter

    # Joint columns for the recording: every arm joint and finger, actual
    # position and the PD target, plus the base pose.
    rec_joints = []
    for aid in range(model.nu):
        aname = model.actuator(aid).name
        if "_joint" in aname or "_finger" in aname:
            qa = model.jnt_qposadr[model.actuator_trnid[aid, 0]]
            rec_joints.append((aname.removesuffix("_ctrl"), qa, aid))
    recorder = ViewerRecorder(
        PROJECT_ROOT / "data" / "recordings", vcfg["record_fps"],
        ["sim_time_s", "wall_s", "base_x", "base_y", "base_yaw_deg"]
        + [f"{n}_pos" for n, _, _ in rec_joints]
        + [f"{n}_target" for n, _, _ in rec_joints])
    rec_t0 = [0.0]

    hud_keys = [("Arrows", "drive"), ("Spc", "stop"),
                ("1-8", "L arm +"), ("Q-I", "L arm -"),
                ("A-K", "R arm +"), ("Z-,", "R arm -"),
                ("PgUp/Dn", "pedestal")] + \
        ([("F2", "man/tele")] if vcfg.get("has_teleop") else []) + \
        [("F3", "cam imgs"), ("F4", "snap"), ("F5", "log"),
         ("F6", "rec video"), ("Esc", "quit")]

    # Text is drawn into small RGB bitmaps with OpenCV and blitted with
    # one mjr_drawPixels each. mjr_overlay draws one glyph per GL call,
    # and on this VM's vmwgfx driver every such call leaks a resource id:
    # a ~200 glyph HUD aborted the process at frame ~250 ("Illegal
    # COTable id"). One single-space overlay is kept per frame because the
    # first mjr_drawPixels right after mjr_render is otherwise dropped
    # (eagle inset blank); a few glyphs/frame is far below the limit.
    def blit(img, left, bottom):
        # drawPixels wants a FLAT contiguous uint8 array, bottom-up rows
        h, w = img.shape[:2]
        flat = np.ascontiguousarray(np.flipud(img)).ravel()
        mujoco.mjr_drawPixels(
            flat, None, mujoco.MjrRect(left, bottom, w, h), context)

    def text_bitmap(rows, w, label_w, keys=()):
        line_h, key_h, font = 20, 24, cv2.FONT_HERSHEY_SIMPLEX
        # Key legend: keycap icon + short label, flowed left to right and
        # wrapped to the panel width, to use as little height as possible.
        layout, x, line = [], 6, 0
        for key, label in keys:
            kw = cv2.getTextSize(key, font, 0.4, 1)[0][0] + 8
            lw = cv2.getTextSize(label, font, 0.4, 1)[0][0]
            if x + kw + 4 + lw > w - 6 and x > 6:
                x, line = 6, line + 1
            layout.append((key, label, x, line, kw))
            x += kw + 4 + lw + 12
        top = line_h * len(rows) + 8
        h = top + (key_h * (line + 1) + 6 if keys else 0)
        bmp = np.full((h, w, 3), 45, np.uint8)
        for i, (lab, val) in enumerate(rows):
            y = line_h * (i + 1) - 3
            cv2.putText(bmp, lab, (6, y), cv2.FONT_HERSHEY_SIMPLEX,
                        0.45, (190, 190, 190), 1, cv2.LINE_AA)
            cv2.putText(bmp, val, (label_w, y), cv2.FONT_HERSHEY_SIMPLEX,
                        0.45, (255, 255, 255), 1, cv2.LINE_AA)
        if keys:
            cv2.line(bmp, (6, top - 2), (w - 6, top - 2), (110, 110, 110), 1)
        for key, label, kx, ln, kw in layout:
            y = top + key_h * ln + 17
            cv2.rectangle(bmp, (kx, y - 14), (kx + kw, y + 4),
                          (80, 80, 80), -1)
            cv2.rectangle(bmp, (kx, y - 14), (kx + kw, y + 4),
                          (200, 200, 200), 1)
            cv2.putText(bmp, key, (kx + 4, y), font, 0.4,
                        (255, 255, 255), 1, cv2.LINE_AA)
            cv2.putText(bmp, label, (kx + kw + 4, y), font, 0.4,
                        (150, 220, 150), 1, cv2.LINE_AA)
        return bmp

    def frame(info):
        """Draw one viewer frame. info: frame, time, t_frame_start, images (the camera rig's), base_vel (vx, vy, wz),
        drive_state, targets (the loop's position targets), teleop_status (None without teleop), preview_frame."""
        held = state["held"]
        t = info["time"]
        fr = info["frame"]
        images = info["images"]
        hold_qpos_targets = info["targets"]
        base_vx, base_vy, base_wz = info["base_vel"]
        t_f0 = info["t_frame_start"]

        cur_r = held(glfw.KEY_F6)
        if (cur_r and not state["prev_r"]) or (vcfg.get("record") and fr == 0):  # --record starts on frame 0
            if recorder.active:
                mp4, csv_path, n = recorder.stop()
                print(f"Recording stopped: {n} frames ({n / recorder.fps:.1f} s sim time)\n"
                      f"  video:  {mp4}\n  joints: {csv_path}")
            else:
                fb_w, fb_h = glfw.get_framebuffer_size(window)
                recorder.start(fb_w, fb_h)
                rec_t0[0] = _time.time()
                print(f"Recording started: {recorder.paths[0]}  ({recorder.fps:g} fps sim time)")
                if vcfg.get("roundrobin"):
                    print("  note: cameras take turns (each updates at CAMERA_HZ/3); "
                          "run with CC_ROUNDROBIN=0 for full-rate camera insets in the video")
        state["prev_r"] = cur_r

        cur_c = held(glfw.KEY_F3)
        if cur_c and not state["prev_c"]:
            cam_dir.mkdir(parents=True, exist_ok=True)
            stamp = _time.strftime("%H%M%S")
            for cname, img in images.items():
                cv2.imwrite(str(cam_dir / f"{cname}_{stamp}.png"),
                            cv2.cvtColor(img, cv2.COLOR_RGB2BGR))
            print(f"Camera images saved: {cam_dir}/*_{stamp}.png")
        state["prev_c"] = cur_c

        # Camera follow
        cam.lookat[:] = data.xpos[base_body_id]
        qw, qx, qy, qz = data.xquat[base_body_id]
        yaw_deg = math.degrees(
            math.atan2(2.0 * (qw * qz + qx * qy),
                       1.0 - 2.0 * (qy * qy + qz * qz)))
        cam.azimuth = yaw_deg + 90

        # Render
        width, height = glfw.get_framebuffer_size(window)
        viewport = mujoco.MjrRect(0, 0, width, height)
        t_r0 = pc()
        mujoco.mjv_updateScene(
            model, data, opt, None, cam,
            mujoco.mjtCatBit.mjCAT_ALL, scene_vis)
        mujoco.mjr_render(viewport, scene_vis, context)
        t_r1 = pc()
        tm["render"] += t_r1 - t_r0

        if show_hud or show_insets:
            mujoco.mjr_overlay(
                mujoco.mjtFont.mjFONT_NORMAL,
                mujoco.mjtGridPos.mjGRID_TOPLEFT, viewport, " ", None, context)
        if show_hud:
            now = _time.time()
            dt_wall = now - hud_state["last"]
            hud_state["last"] = now
            # Smooth frame TIME, not fps: averaging 1/dt is dominated by the
            # fast frames between camera ticks and overstates the rate.
            hud_state["ms"] += 0.1 * (1000.0 * dt_wall - hud_state["ms"])
            ds = info["drive_state"]
            speed = math.hypot(base_vx, base_vy)
            teleop_status = info.get("teleop_status")
            hud = text_bitmap([
                ("sim time", f"{t:.2f} s"),
                ("base speed (m/s)", f"{speed:.2f}"),
                ("base vx, vy (m/s)", f"{base_vx:+.2f}, {base_vy:+.2f}"),
                ("yaw rate (rad/s)", f"{base_wz:+.2f}"),
                ("yaw (deg)", f"{yaw_deg:+.1f}"),
                ("position x, y, z (m)", f"{data.qpos[0]:.2f}, "
                 f"{data.qpos[1]:.2f}, {data.qpos[2]:.3f}"),
                ("frame (ms, fps)", f"{hud_state['ms']:.0f}, "
                 f"{1000.0 / max(hud_state['ms'], 1e-6):.1f}"),
                ("cmd lin, ang", f"{ds.get('linear', 0):+.2f}, "
                 f"{ds.get('angular', 0):+.2f}"),
                ("recording (F6)", "off" if not recorder.active else
                 f"REC {recorder.frames} frames, {recorder.frames / recorder.fps:.1f} s"),
            ] + ([("arms (F2 toggles)", teleop_status)] if teleop_status is not None else []),
                400, 180, hud_keys)
            blit(hud, 8, height - hud.shape[0] - 8)
        if show_insets:
            # One row of insets along the bottom: the simulated cameras, plus
            # the operator webcam in teleop runs. Each is scaled to fit the
            # window width (at most half size), with its name burned into the
            # top-left corner. Images are top-down; blit flips them.
            tiles = list(images.items())
            if info.get("teleop_status") is not None and info.get("preview"):
                pf = info.get("preview_frame")
                tiles.append(("operator_cam", None if pf is None else
                              cv2.cvtColor(pf, cv2.COLOR_BGR2RGB)))
            gap = 8
            iw = min(320, (width - gap * (len(tiles) + 1)) // len(tiles))
            ih = iw * 3 // 4
            x = gap
            for cname, img in tiles:
                # The simulated cameras only change on their render ticks, so
                # keep the scaled, labelled tile until the source array does.
                cached = inset_cache.get(cname)
                if img is not None and cached is not None \
                        and cached[0] is img and cached[1].shape[1] == iw:
                    small = cached[1]
                else:
                    if img is None:  # operator camera: no frame delivered yet
                        small = np.full((ih, iw, 3), 40, np.uint8)
                    else:
                        small = cv2.resize(img, (iw, ih),
                                           interpolation=cv2.INTER_AREA)
                    cv2.rectangle(small, (0, 0), (len(cname) * 9 + 10, 20),
                                  (45, 45, 45), -1)
                    cv2.putText(small, cname, (5, 15),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.5,
                                (255, 255, 255), 1, cv2.LINE_AA)
                    inset_cache[cname] = (img, small)
                blit(small, x, gap)
                x += iw + gap
        tm["hud_insets"] += pc() - t_r1
        p_now = held(glfw.KEY_F4)
        due = snapshot_every > 0 and \
            _time.time() - snap_state["last"] >= snapshot_every
        if (p_now and not snap_state["p_down"]) or due:
            snap_state["last"] = _time.time()
            rgb = np.zeros((height, width, 3), dtype=np.uint8)
            mujoco.mjr_readPixels(rgb, None, viewport, context)
            save_snapshot(rgb, info.get("preview_frame"))
        snap_state["p_down"] = p_now
        if vcfg.get("bench_snap_dir") and fr == vcfg["bench_snap_frame"]:
            sd = Path(vcfg["bench_snap_dir"]); sd.mkdir(parents=True, exist_ok=True)
            rgb = np.zeros((height, width, 3), dtype=np.uint8)
            mujoco.mjr_readPixels(rgb, None, viewport, context)
            cv2.imwrite(str(sd / "main.png"),
                        cv2.cvtColor(np.flipud(rgb), cv2.COLOR_RGB2BGR))
            for cname, img in images.items():
                cv2.imwrite(str(sd / f"{cname}.png"),
                            cv2.cvtColor(img, cv2.COLOR_RGB2BGR))
        if recorder.active:
            rgb = np.zeros((height, width, 3), dtype=np.uint8)
            mujoco.mjr_readPixels(rgb, None, viewport, context)
            recorder.write(rgb, [
                data.time, _time.time() - rec_t0[0],
                data.qpos[0], data.qpos[1], yaw_deg]
                + [data.qpos[qa] for _, qa, _ in rec_joints]
                + [hold_qpos_targets[aid] for _, _, aid in rec_joints])
        t_s0 = pc()
        glfw.swap_buffers(window)
        glfw.poll_events()
        if vcfg.get("finish"):
            mujoco.mjr_finish()
        tm["swap_poll"] += pc() - t_s0

        if vcfg["vsync"] == 0:
            # No vsync pacing: hold the viewer to VIEWER_HZ so sim time
            # never runs faster than wall time.
            slack = 1.0 / viewer_hz - (pc() - t_f0)
            if slack > 0:
                _time.sleep(slack)
        return {"quit": bool(glfw.window_should_close(window)), "yaw_deg": yaw_deg}

    def finish():
        if recorder.active:
            mp4, csv_path, n = recorder.stop()
            print(f"Recording stopped: {n} frames ({n / recorder.fps:.1f} s sim time)\n"
                  f"  video:  {mp4}\n  joints: {csv_path}")

    return {
        "name": "glfw", "window": window, "context": context, "timers": tm,
        "key_down": lambda code: glfw.get_key(window, code) == glfw.PRESS,
        "set_held": lambda fn: state.__setitem__("held", fn),
        "frame": frame, "finish": finish, "close": glfw.terminate,
        "should_close": lambda: glfw.window_should_close(window),
    }
