# Code generated by Claude
"""
Keyboard command source: the key handling of experiments/combined_controller.py (jog keys, pedestal keys, the
cruise-control drive ramp), moved here and turned into a source with step(obs) -> list of commands. No other logic.

    source = make_keyboard_source(model, held, drive_cfg, ped_step)
    commands = source["step"](obs)

`held(key_code)` says whether a GLFW key is down (real keyboard or the CC_BENCH_KEYS test injection); the launcher
supplies it. Every tick the source reads the key state and returns up to three commands (src/commands.py):
  base      the drive ramp (arrows / SPACE) as a Twist; emitted while the ramp is not at rest, so cruise control keeps
            the last speed after the keys are released, exactly as before
  pedestal  Page Up / Page Down: the applied height plus one step
  arms      jog keys: the applied joint / gripper targets plus one step for each key held
Targets are computed from obs["applied"] (what the loop currently holds), not from an internal integrator, so a command
that is held back by the hold rule does not wind up while it waits.
"""

import glfw
import numpy as np

JOG_JOINT_STEP = 0.05   # rad per viewer frame while a jog key is held
JOG_GRIP_STEP = 0.003   # m per viewer frame (finger travel is 0 closed .. 0.044 open)
GRIP_IDX = 7            # item 0-6 = joints 1-7, 7 = gripper

# One fixed key pair per joint, shoulder (j1) to wrist (j7) then gripper,
# left to right. The upper key increases, the lower key decreases (the
# gripper's upper key opens it). Left arm on the top two rows, right arm on
# the home and bottom rows.
JOG_KEYS = {
    "left":  {"plus":  ["1", "2", "3", "4", "5", "6", "7", "8"],
              "minus": ["Q", "W", "E", "R", "T", "Y", "U", "I"]},
    "right": {"plus":  ["A", "S", "D", "F", "G", "H", "J", "K"],
              "minus": ["Z", "X", "C", "V", "B", "N", "M", "COMMA"]},
}

# Pedestal lift (placeholder actuator, robot_specs.PEDESTAL_SPECS): Page Up raises, Page Down
# lowers while held. The command moves at jog_speed per second of SIM time, not per viewer
# frame, so it does not depend on the viewer's fps.
PEDESTAL_KEYS = {"up": "PAGE_UP", "down": "PAGE_DOWN"}

# Base drive keys and ramp (was CONTROL_GROUPS[0]["keys"] / ["drive_params"])
DRIVE_CFG = {
    "keys": {
        "forward":  ["UP"],
        "backward": ["DOWN"],
        "left":     ["LEFT"],
        "right":    ["RIGHT"],
        "stop":     ["SPACE"],
    },
    "drive_params": {
        "max_linear_vel":  1.5,   # m/s (real Tracer max ~1.6 m/s)
        "max_angular_vel": 2.0,   # rad/s
        "incr":            0.02,  # gentle ramp — fast incr flings the arms
                                   # because velocity control decouples
                                   # base from arm inertia
    },
}


def key_code(name: str) -> int:
    val = getattr(glfw, f"KEY_{name.upper()}", None)
    if val is None:
        raise ValueError(f"Unknown GLFW key: {name}")
    return val


def build_jog_tables(model, mujoco):
    """Per side, 8 selectable items: (actuator ids, (lo, hi), step).

    Items 0-6 are arm joints 1-7; item 7 is the gripper, whose two fingers
    move together (0 = closed, 0.044 m = open on both hands).
    """
    def aid(name):
        a = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_ACTUATOR, name)
        if a < 0:
            raise RuntimeError(f"Actuator '{name}' not in model.")
        return a

    def jrange(a):
        return tuple(model.jnt_range[model.actuator_trnid[a, 0]])

    tables = {}
    for side in ("left", "right"):
        items = []
        for i in range(1, 8):
            a = aid(f"{side}_joint{i}_ctrl")
            items.append(([a], jrange(a), JOG_JOINT_STEP))
        f = [aid(f"{side}_finger1_ctrl"), aid(f"{side}_finger2_ctrl")]
        items.append((f, jrange(f[0]), JOG_GRIP_STEP))
        tables[side] = items
    return tables


def make_keyboard_source(model, held, drive_cfg, ped_step, ped_range):
    """drive_cfg: DRIVE_CFG-shaped dict, or None for no base keys. ped_step: pedestal command change per tick [m].
    ped_range: (lo, hi)."""
    import mujoco
    drive_keys = {action: [key_code(k) for k in key_list] for action, key_list in (drive_cfg or {"keys": {}})["keys"].items()}
    for action in ("forward", "backward", "left", "right", "stop"):
        drive_keys.setdefault(action, [])
    dp = (drive_cfg or {}).get("drive_params", {})
    incr = dp.get("incr", 0.1)
    max_lin_vel = dp.get("max_linear_vel", 1.5)
    max_ang_vel = dp.get("max_angular_vel", 2.0)
    ds = {"linear": 0.0, "angular": 0.0}
    state = {"drive": ds, "was_moving": False}

    jog_tables = build_jog_tables(model, mujoco)
    jog_keymap = {side: list(zip([key_code(k) for k in kk["plus"]], [key_code(k) for k in kk["minus"]]))
                  for side, kk in JOG_KEYS.items()}
    ped_keys = {d: key_code(k) for d, k in PEDESTAL_KEYS.items()}
    ped_lo, ped_hi = ped_range

    def step(obs):
        applied = obs["applied"]
        cmds = []

        # --- Drive: ramp linear/angular commands (cruise control) ---
        drive_key_down = any(held(k) for ks in drive_keys.values() for k in ks)
        ds["linear"] += (incr if any(held(k) for k in drive_keys["forward"]) else 0.0) \
                      - (incr if any(held(k) for k in drive_keys["backward"]) else 0.0)
        ds["angular"] += (incr if any(held(k) for k in drive_keys["left"]) else 0.0) \
                       - (incr if any(held(k) for k in drive_keys["right"]) else 0.0)
        ds["linear"]  = max(-1.0, min(ds["linear"],  1.0))
        ds["angular"] = max(-1.0, min(ds["angular"], 1.0))

        if any(held(k) for k in drive_keys.get("stop", [])):
            # Ramp back to zero at the same rate as the accel
            # ramp (incr/step) instead of snapping instantly —
            # avoids a velocity discontinuity at stop, the same
            # kind of instant-stop artifact investigated for the
            # scripted test scenario (see
            # data/arm_swing_diagnostics/rampstop_*).
            if ds["linear"] > 0:
                ds["linear"] = max(0.0, ds["linear"] - incr)
            else:
                ds["linear"] = min(0.0, ds["linear"] + incr)
            if ds["angular"] > 0:
                ds["angular"] = max(0.0, ds["angular"] - incr)
            else:
                ds["angular"] = min(0.0, ds["angular"] + incr)

        # Convert normalized commands to velocities
        lin_vel = ds["linear"] * max_lin_vel
        ang_vel = ds["angular"] * max_ang_vel
        moving = ds["linear"] != 0.0 or ds["angular"] != 0.0
        if moving or state["was_moving"] or drive_key_down:     # the zero that ends a ramp is emitted once
            cmds.append({"mode": "base", "twist": (lin_vel, ang_vel)})
        state["was_moving"] = moving

        # --- Pedestal lift: Page Up raises, Page Down lowers ---
        direction = int(held(ped_keys["up"])) - int(held(ped_keys["down"]))
        if direction:
            h = np.clip(applied["pedestal"] + direction * ped_step, ped_lo, ped_hi)
            cmds.append({"mode": "pedestal", "height": float(h)})

        # --- Manual arm / gripper jogging: one fixed key pair per joint ---
        arm_targets, grip = {}, {}
        for side, pairs in jog_keymap.items():
            for idx, (k_plus, k_minus) in enumerate(pairs):
                d = int(held(k_plus)) - int(held(k_minus))
                if d == 0:
                    continue
                ids, (lo, hi), step_ = jog_tables[side][idx]
                if idx == GRIP_IDX:
                    grip[side] = float(np.clip(applied["gripper"][side] + d * step_, lo, hi))
                else:
                    q = arm_targets.setdefault(side, list(applied["arm_targets"][side]))
                    q[idx] = float(np.clip(applied["arm_targets"][side][idx] + d * step_, lo, hi))
        if arm_targets or grip:
            cmd = {"mode": "arms"}
            if arm_targets:
                cmd["arm_targets"] = arm_targets
            if grip:
                cmd["gripper"] = grip
            cmds.append(cmd)
        return cmds

    return {"name": "keyboard", "step": step, "state": state}
