"""Trajectory logger for simulation data.

Code generated by Claude
"""

import json
from pathlib import Path
from datetime import datetime
import numpy as np


class TrajectoryLogger:
    """Log simulation trajectories to disk."""
    
    def __init__(self, output_dir: str = "data"):
        """Initialize logger."""
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
        
        self.trajectory = []
        self.start_time = datetime.now()
    
    def record(self, observation: dict):
        """Record a single timestep.

        Logs whatever keys are present in the observation dict — robot state
        plus any tracked-body keys RobotSimulator was configured with
        (e.g. block_position, beaker_1_position) — instead of assuming
        'block' is always the tracked object.
        """
        # Convert numpy arrays to lists for JSON serialization
        record = {
            key: (value.tolist() if hasattr(value, "tolist") else value)
            for key, value in observation.items()
        }
        self.trajectory.append(record)
    
    def save(self, filename: str = None):
        """Save trajectory to file."""
        if filename is None:
            timestamp = self.start_time.strftime("%Y%m%d_%H%M%S")
            filename = f"trajectory_{timestamp}.json"
        
        filepath = self.output_dir / filename
        
        with open(filepath, 'w') as f:
            json.dump(self.trajectory, f, indent=2)
        
        print(f"✓ Saved trajectory: {filepath} ({len(self.trajectory)} steps)")
        return filepath