# Code generated by Claude
"""
Frame a set of world points with the neck camera.

    targets, report = frame_points(model, data, points, cfg=FRAMING_CFG)

Solves the neck's joint targets so that the eagle camera looks at the centre of the points (the centre of their bounding
box) and ALL points sit inside the image with at least cfg["margin"] (10 %) of the image width / height to every edge. If
they cannot all fit, the best attempt is returned and the report says which points are outside and by how much (fractions
of the image size beyond the margin line); nothing is cropped silently. The result is collision-checked: the neck's
geoms must be at least cfg["contact_margin"] from the rest of the robot and the scene; if the best pose touches
something, the next best collision-free one is used, and if there is none the best attempt is returned with its contacts
listed.

`points`: {name: (x, y, z)} in the world (or a list of xyz). Only kinematics are used (scratch MjData, `data` is not
modified), so it can run while the simulation runs. `start` = a joint vector (default: the current neck pose) and
local=True skip the coarse search and refine from `start` (cheap enough to run a few times per second).

Report keys: fits, worst_margin (smallest edge margin of any point, fraction of the image), aim_error_deg, camera_pos,
neck_targets, contacts, points: {name: {px, py, u, v, margin, inside, outside_by}} with the pixel position in the image
and the margin to the nearest edge (fraction of the image dimension; >= cfg["margin"] means inside).
"""

import itertools

import mujoco
import numpy as np
from scipy.optimize import minimize

from src import robot_specs
from src.neck import neck_ids

FRAMING_CFG = {
    "camera": "eagle_cam",
    "margin": 0.10,            # fraction of the image width / height kept free on every side
    "coarse_steps": 7,         # grid points per joint for the coarse search
    "n_refine": 6,             # best coarse candidates refined
    "refine_evals": 250,
    "contact_margin": 0.005,   # m, neck geoms stay this far from everything that is not the neck
    "aim_weight": 1.0,         # cost of the aim error (rad^2) next to the fit violation
    "move_weight": 1e-3,       # cost of moving away from the start pose (rad^2): no needless motion
    "near_depth": 0.05,        # m, points closer to the camera than this count as not visible
}


def _project(points, cam_pos, cam_R, fovy_deg, aspect):
    """NDC (u, v in [-1, 1] inside the image) and depth of world points for a MuJoCo camera (looks along its -z, +y up)."""
    pc = (points - cam_pos) @ cam_R                       # = R^T (p - pos), rows are points
    depth = -pc[:, 2]
    th = np.tan(np.radians(fovy_deg) / 2)
    safe = np.maximum(depth, 1e-6)
    return pc[:, 0] / safe / (th * aspect), pc[:, 1] / safe / th, depth


def _points_array(points):
    if isinstance(points, dict):
        names = list(points)
        return names, np.array([points[n] for n in names], float)
    arr = np.asarray(points, float)
    return [f"p{i}" for i in range(len(arr))], arr


class _Scratch:
    def __init__(self, model, data, cfg, neck_specs):
        self.model, self.cfg = model, cfg
        self.d = mujoco.MjData(model)
        self.d.qpos[:] = data.qpos
        self.ids = neck_ids(model, neck_specs)
        if self.ids is None:
            raise ValueError("the model has no neck")
        self.cam = model.camera(cfg["camera"]).id
        self.res = model.cam_resolution[self.cam]
        self.aspect = float(self.res[0]) / float(self.res[1])
        self.fovy = float(model.cam_fovy[self.cam])
        root = model.body(neck_specs["prefix"] + "base").id
        in_neck = lambda b: any(a == root for a in self._ancestors(b))
        self.neck_geoms = [g for g in range(model.ngeom) if in_neck(int(model.geom_bodyid[g])) and (model.geom_contype[g] or model.geom_conaffinity[g])]
        self.other_geoms = [g for g in range(model.ngeom) if not in_neck(int(model.geom_bodyid[g])) and int(model.geom_bodyid[g]) != 0
                            and (model.geom_contype[g] or model.geom_conaffinity[g])]
        self.root = root

    def _ancestors(self, b):
        while b > 0:
            yield b
            b = int(self.model.body_parentid[b])

    def pose(self, q):
        d = self.d
        for a, v in zip(self.ids["qadr"], q):
            d.qpos[a] = v
        mujoco.mj_kinematics(self.model, d)
        mujoco.mj_camlight(self.model, d)
        return d.cam_xpos[self.cam].copy(), d.cam_xmat[self.cam].reshape(3, 3).copy()

    def contacts(self, q):
        """Neck geoms closer than contact_margin to anything that is not the neck (names of the pairs)."""
        self.pose(q)
        d, m, ft, out = self.d, self.model, np.zeros(6), []
        base = d.xpos[self.root]
        near = [g for g in self.other_geoms if np.linalg.norm(d.geom_xpos[g] - base) < 1.5]
        for ng in self.neck_geoms:
            for og in near:
                if mujoco.mj_geomDistance(m, d, ng, og, self.cfg["contact_margin"], ft) < self.cfg["contact_margin"]:
                    out.append((m.geom(ng).name or m.body(m.geom_bodyid[ng]).name, m.body(m.geom_bodyid[og]).name))
        return out


def _evaluate(sc, q, pts, center, q0):
    cfg = sc.cfg
    pos, R = sc.pose(q)
    u, v, depth = _project(pts, pos, R, sc.fovy, sc.aspect)
    limit = 1.0 - 2.0 * cfg["margin"]                      # |u|, |v| <= 0.8 keeps 10 % free on every side
    ext = np.maximum(np.abs(u), np.abs(v))
    viol = np.where(depth < cfg["near_depth"], 10.0, np.maximum(0.0, ext - limit))
    axis = -R[:, 2]
    to_c = center - pos
    aim = float(np.arccos(np.clip(axis @ to_c / max(np.linalg.norm(to_c), 1e-9), -1, 1)))
    cost = 100.0 * float(viol.max()) + 10.0 * float(viol.sum()) + cfg["aim_weight"] * aim ** 2 + cfg["move_weight"] * float(np.sum((q - q0) ** 2))
    return cost, (pos, R, u, v, depth, aim)


def frame_points(model, data, points, cfg=FRAMING_CFG, neck_specs=robot_specs.NECK_SPECS, start=None, local=False):
    cfg = {**FRAMING_CFG, **cfg}
    names, pts = _points_array(points)
    sc = _Scratch(model, data, cfg, neck_specs)
    ids = sc.ids
    lo, hi = ids["lo"], ids["hi"]
    q_now = np.array([data.qpos[a] for a in ids["qadr"]])
    q0 = q_now if start is None else np.asarray(start, float)
    center = 0.5 * (pts.min(axis=0) + pts.max(axis=0))
    f = lambda q: _evaluate(sc, np.clip(q, lo, hi), pts, center, q0)[0]

    cands = []
    if not local:
        grids = [np.linspace(l, h, cfg["coarse_steps"]) for l, h in zip(lo, hi)]
        scored = sorted(((f(np.array(q)), tuple(q)) for q in itertools.product(*grids)), key=lambda t: t[0])
        starts = [np.array(q) for _, q in scored[:cfg["n_refine"]]]
    else:
        starts = [q0]
    for s in starts + ([q0] if not local else []):
        r = minimize(f, s, method="Nelder-Mead", bounds=list(zip(lo, hi)), options={"maxfev": cfg["refine_evals"], "xatol": 1e-4, "fatol": 1e-8})
        cands.append((float(r.fun), np.clip(r.x, lo, hi)))
    cands.sort(key=lambda t: t[0])

    chosen, contacts = None, []
    for cost, q in cands:
        c = sc.contacts(q)
        if not c:
            chosen, contacts = (cost, q), []
            break
        if chosen is None:
            chosen, contacts = (cost, q), c                 # best attempt so far, kept if nothing is clear
    cost, q = chosen
    _, (pos, R, u, v, depth, aim) = _evaluate(sc, q, pts, center, q0)
    W, H = float(sc.res[0]), float(sc.res[1])
    margin = np.minimum((1 - np.abs(u)) / 2, (1 - np.abs(v)) / 2)          # to the nearest edge, fraction of the dimension
    margin = np.where(depth < cfg["near_depth"], -1.0, margin)
    report = {
        "fits": bool(np.all(margin >= cfg["margin"] - 1e-9)), "worst_margin": float(margin.min()), "aim_error_deg": float(np.degrees(aim)),
        "camera_pos": pos.round(4).tolist(), "contacts": contacts, "cost": cost,
        "neck_targets": {n: float(v_) for n, v_ in zip(ids["names"], q)},
        "points": {n: {"px": float((u[i] + 1) / 2 * W), "py": float((1 - v[i]) / 2 * H), "u": float(u[i]), "v": float(v[i]), "depth": float(depth[i]),
                       "margin": float(margin[i]), "inside": bool(margin[i] >= cfg["margin"] - 1e-9),
                       "outside_by": float(max(0.0, cfg["margin"] - margin[i]))} for i, n in enumerate(names)},
    }
    return report["neck_targets"], report


def summarize(report):
    """One screen of text for a framing report."""
    lines = [f"framing: {'all points inside with the margin' if report['fits'] else 'DOES NOT FIT'}; worst margin {100 * report['worst_margin']:.1f}% "
             f"of the image, aim error {report['aim_error_deg']:.1f} deg, camera at {report['camera_pos']}"]
    if report["contacts"]:
        lines.append(f"  neck contacts: {report['contacts'][:4]}")
    out = sorted(((n, p) for n, p in report["points"].items() if not p["inside"]), key=lambda t: t[1]["margin"])
    for n, p in out[:6]:
        lines.append(f"  outside: {n} at ({p['px']:.0f}, {p['py']:.0f}) px, margin {100 * p['margin']:.1f}% (needs {100 * (p['margin'] + p['outside_by']):.0f}%)")
    if len(out) > 6:
        lines.append(f"  ... and {len(out) - 6} more points outside (worst first above)")
    return "\n".join(lines)
