# Code generated by Claude
"""
Automatic neck source: follows the grippers while the arms are on the webcam operator (teleop), and looks ahead while
the base is driving. Settings: robot_specs.NECK_AUTO_SPECS.

    source = make_neck_auto_source(model, data, teleop_source, keyboard_source)

Behavior while active (mode "teleop": the teleop source is on; "always": always):
  * base driving (commanded Twist above the thresholds): the neck goes to the drive pose (looks ahead, 30 degrees down)
    and stays there
  * base at rest for resume_delay: every follow_period seconds the gripper points are framed with
    src/neck_framing.frame_points (local search from the current neck goal, so it is cheap) and a neck command is sent if
    the targets moved more than the deadband
  * a neck key press (the keyboard source records its time) pauses all of this for pause_after_key seconds, so the
    keyboard always wins
The loop's neck speed limit smooths whatever this sends. It only produces neck commands (exempt from exclusivity).
"""

import numpy as np

from src import robot_specs
from src.neck_framing import frame_points


def make_neck_auto_source(model, data, teleop, keyboard, specs=robot_specs.NECK_AUTO_SPECS, neck_specs=robot_specs.NECK_SPECS):
    st = {"looking_ahead": False, "stopped_since": None, "last_follow": -1e9, "last_report": None}
    drive = dict(zip(neck_specs["active_joints"], neck_specs["drive_pose"]))
    sides = [s for s in ("left", "right")]

    def active():
        if specs["mode"] == "always":
            return True
        return specs["mode"] == "teleop" and teleop is not None and teleop["state"]["on"]

    def step(obs):
        if not active():
            st["looking_ahead"], st["stopped_since"] = False, None
            return []
        t = obs["time"]
        if t - keyboard["state"].get("neck_active_t", -1e9) < specs["pause_after_key"]:
            return []
        lin, ang = obs["applied"]["twist"]
        if abs(lin) > specs["drive_lin"] or abs(ang) > specs["drive_ang"]:
            st["stopped_since"] = None
            if not st["looking_ahead"]:
                st["looking_ahead"] = True
                return [{"mode": "neck", "neck_targets": dict(drive)}]
            return []
        if st["stopped_since"] is None:
            st["stopped_since"] = t
        if st["looking_ahead"] and t - st["stopped_since"] < specs["resume_delay"]:
            return []
        st["looking_ahead"] = False
        if t - st["last_follow"] < specs["follow_period"]:
            return []
        st["last_follow"] = t
        points = {}
        for side in sides:
            points[f"{side}_tcp"] = data.body(f"openarm_{side}_hand_tcp").xpos.copy()
            points[f"{side}_hand"] = data.body(f"openarm_{side}_hand").xpos.copy()
        goal = obs["applied"]["neck_goal"]
        start = np.array([goal[n] for n in neck_specs["active_joints"]])
        targets, report = frame_points(model, data, points, {}, neck_specs=neck_specs, start=start, local=True)
        st["last_report"] = report
        if max(abs(targets[n] - goal[n]) for n in targets) < specs["deadband"]:
            return []
        return [{"mode": "neck", "neck_targets": targets}]

    return {"name": "neck_auto", "step": step, "state": st}
