# Code generated by Claude
"""
The camera neck: an SO-101 arm attached to the OpenArm torso at load time, carrying the eagle camera.

Same pattern as src/cameras.py and src/pedestal.py: the robot XML in deps/ is not touched. add_neck(spec, NECK_SPECS)
loads the vendored SO-101 model (models/so101, see PROVENANCE.md there), removes what is not wanted (the joints that are
not in NECK_SPECS["active_joints"] together with their actuators, and the bodies in "removed_bodies"; the wrist-roll
link stays as a rigid part), makes the mesh paths absolute and attaches the result to the mount body under a name prefix.
RobotSimulator calls it after the pedestal lift, so the pedestal actuator keeps its index (20) and the neck's actuators
come right after it.

    neck_ids(model, NECK_SPECS)  ->  {"names", "act", "qadr", "vadr", "lo", "hi"} for the active joints, in order
"""

from pathlib import Path

import mujoco
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def add_neck(spec, neck_specs):
    """Attach the SO-101 neck to `spec` (an MjSpec of the robot)."""
    xml = PROJECT_ROOT / neck_specs["model_xml"]
    child = mujoco.MjSpec.from_file(str(xml))
    assets = xml.parent / child.meshdir
    for me in child.meshes:                   # absolute paths: the parent's meshdir must not matter
        me.file = str(assets / Path(me.file).name)
    active = set(neck_specs["active_joints"])
    all_joints = [j.name for j in child.joints]
    missing = active - set(all_joints)
    if missing:
        raise ValueError(f"neck active joints not in the SO-101 model: {sorted(missing)}")
    for name in all_joints:
        if name in active:
            continue
        act = child.actuator(name)            # SO-101 actuators carry their joint's name
        if act is not None:
            child.delete(act)
        child.delete(child.joint(name))
    for name in neck_specs.get("removed_bodies", ()):
        child.delete(child.body(name))

    mount = spec.body(neck_specs["mount_body"])
    if mount is None:
        raise ValueError(f"neck mount body '{neck_specs['mount_body']}' not found in the robot model")
    frame = mount.add_frame()
    frame.pos = list(neck_specs["mount_pos"])
    frame.quat = list(neck_specs["mount_quat"])
    frame.attach_body(child.body("base"), neck_specs["prefix"], "")


def neck_ids(model, neck_specs):
    """Actuator ids, qpos / dof addresses and limits of the neck's active joints, in the order of active_joints."""
    names = [neck_specs["prefix"] + j for j in neck_specs["active_joints"]]
    act = [mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_ACTUATOR, n) for n in names]
    if min(act) < 0:
        return None
    jid = [int(model.actuator_trnid[a, 0]) for a in act]
    return {"names": list(neck_specs["active_joints"]), "act": act,
            "qadr": [int(model.jnt_qposadr[j]) for j in jid], "vadr": [int(model.jnt_dofadr[j]) for j in jid],
            "lo": np.array([model.jnt_range[j, 0] for j in jid]), "hi": np.array([model.jnt_range[j, 1] for j in jid])}


def set_neck_pose(model, data, neck_specs, q=None):
    """Put the neck's joints at q (default: the drive pose) in qpos and update the kinematics. No stepping."""
    ids = neck_ids(model, neck_specs)
    if ids is None:
        return None
    q = neck_specs["drive_pose"] if q is None else q
    for a, v in zip(ids["qadr"], q):
        data.qpos[a] = v
    mujoco.mj_forward(model, data)
    return ids
