"""Placeholder pedestal lift actuator, added to the model at load time.

Code generated by Claude

PLACEHOLDER: the real lift hardware is unconfirmed (see robot_specs.PEDESTAL_SPECS).
Same pattern as src/cameras.py: the XML stays untouched and the extra elements are
added through MjSpec before compiling.
"""

import mujoco
import numpy as np

G = 9.81


def add_pedestal_lift(spec, pedestal_specs):
    """Couple the two pedestal stages and add one position actuator on the lower stage."""
    lower, upper = pedestal_specs["joints"]
    hi = pedestal_specs["stage_range"][1]
    lowest = pedestal_specs["lowest_command"]
    for name in (lower, upper):
        if spec.joint(name) is None:
            raise ValueError(f"Pedestal joint '{name}' not found in model")

    # upper stage = lower stage (joint equality: q_upper = 0 + 1 * q_lower), so both
    # stages move together. Solver parameters are the model's own "collision" equality
    # defaults (stiff), so the load does not stretch the coupling.
    eq = spec.add_equality()
    eq.name = "pedestal_stages_coupled"
    eq.type = mujoco.mjtEq.mjEQ_JOINT
    eq.name1, eq.name2 = upper, lower
    eq.data[:5] = [0.0, 1.0, 0.0, 0.0, 0.0]
    eq.solref = [0.005, 1.0]
    eq.solimp = [0.99, 0.999, 1e-5, 0.5, 2.0]

    # The telescoping sections nest inside each other on the real pedestal, but MuJoCo collides
    # their convex hulls, which overlap and would stop the lift at half travel. The XML already
    # excludes the adjacent pairs (Bottom/Middle, Middle/Top); this adds Bottom/Top.
    bottom_body, top_body = pedestal_specs["nested_bodies"]
    exc = spec.add_exclude()
    exc.name = "pedestal_Bottom_Top"
    exc.bodyname1, exc.bodyname2 = bottom_body, top_body

    kp, kv, fmax = (pedestal_specs[k] for k in ("kp", "kv", "force_limit"))
    act = spec.add_actuator()
    act.name = pedestal_specs["actuator_name"]
    act.target = lower
    act.trntype = mujoco.mjtTrn.mjTRN_JOINT
    act.gaintype = mujoco.mjtGain.mjGAIN_FIXED
    act.biastype = mujoco.mjtBias.mjBIAS_AFFINE
    act.gainprm[0] = kp
    act.biasprm[:3] = [0.0, -kp, -kv]            # force = kp * (ctrl - q) - kv * qdot
    act.ctrllimited = mujoco.mjtLimited.mjLIMITED_TRUE
    # Lower bound = the reachable limit (torso / pedestal_Bottom contact), not the joint range, so the
    # actuator never pushes into that contact. The real minimum height is pending Dan.
    act.ctrlrange = [lowest, hi]
    act.forcelimited = mujoco.mjtLimited.mjLIMITED_TRUE
    act.forcerange = [-fmax, fmax]


def pedestal_load(model, pedestal_specs):
    """Weight the lift carries, from the compiled model's body masses.

    Returns masses above each stage (everything attached above the joint: later
    stages, the robot body, both arms) and the force the one actuator must hold
    with the stages coupled: moving the lower stage by dq moves the upper stage by dq
    as well, so by virtual work the actuator carries both weights.
    """
    lower, upper = pedestal_specs["joints"]
    body_of = lambda j: model.joint(j).bodyid[0]
    m_lower = float(model.body_subtreemass[body_of(lower)])
    m_upper = float(model.body_subtreemass[body_of(upper)])
    return dict(mass_above_lower_kg=m_lower, mass_above_upper_kg=m_upper,
                hold_force_n=(m_lower + m_upper) * G,
                static_sag_mm=1000.0 * (m_lower + m_upper) * G / pedestal_specs["kp"])
