# Code generated by Claude
"""
Policy command source: a callable policy(obs, t) -> array of actuator targets indexed by actuator id (the interface
of models/policies/*.py), restricted to the actuators of the "auto" control groups, as in the old
experiments/combined_controller.py. The array is turned into commands:
  arm joint actuators  -> an arms command (arm_targets per side; joints the policy does not cover keep the applied value)
  finger actuators     -> gripper (both fingers of a side take the first finger's value)
  the pedestal         -> a pedestal command
  the wheel motors     -> ignored (the base is velocity-driven, as before)

    source = make_policy_source(model, policy, ids)
    source["claims"]   the actuator ids the policy owns (they are not "unclaimed" hold actuators)
    source["routes"]   the router entries to hand to the loop: {"arms.right": "policy", ...}
"""

import re

import numpy as np

from src import robot_specs


def make_policy_source(model, policy, ids):
    ped_name = robot_specs.PEDESTAL_SPECS["actuator_name"]
    arm_ids = {"left": {}, "right": {}}      # side -> {joint index 0-6: actuator id}
    finger_ids = {"left": [], "right": []}
    ped_id = None
    for aid in ids:
        name = model.actuator(aid).name
        m = re.fullmatch(r"(left|right)_joint([1-7])_ctrl", name)
        f = re.fullmatch(r"(left|right)_finger([12])_ctrl", name)
        if m:
            arm_ids[m.group(1)][int(m.group(2)) - 1] = aid
        elif f:
            finger_ids[f.group(1)].append(aid)
        elif name == ped_name:
            ped_id = aid
    routes = {}
    for side in ("left", "right"):
        if arm_ids[side]:
            routes[f"arms.{side}"] = "policy"
        if finger_ids[side]:
            routes[f"gripper.{side}"] = "policy"
    if ped_id is not None:
        routes["pedestal"] = "policy"

    def step(obs):
        pt = policy(obs, obs["time"])
        cmds = []
        arm_targets, grip = {}, {}
        for side in ("left", "right"):
            if arm_ids[side]:
                q = list(obs["applied"]["arm_targets"][side])
                for j, aid in arm_ids[side].items():
                    q[j] = float(pt[aid])
                arm_targets[side] = q
            if finger_ids[side]:
                grip[side] = float(pt[finger_ids[side][0]])
        if arm_targets or grip:
            cmd = {"mode": "arms"}
            if arm_targets:
                cmd["arm_targets"] = arm_targets
            if grip:
                cmd["gripper"] = grip
            cmds.append(cmd)
        if ped_id is not None:
            cmds.append({"mode": "pedestal", "height": float(pt[ped_id])})
        return cmds

    return {"name": "policy", "step": step, "claims": sorted(ids), "routes": routes}
