# Code generated by Claude
"""
Rate-limiting of joint targets, for snap-back safety.

    q = rate_limit(current, goal, max_speed, dt)

Returns the targets one tick of `dt` seconds toward `goal`, starting from `current`, so that no joint moves faster than `max_speed` rad/s. If
the goal is within reach it is returned unchanged (exactly), so a policy that always commands through this keeps its normal behaviour whenever it
is already close to where it left off. If not (the operator moved the arm while the policy was paused) the step is the straight line in joint
space toward the goal, scaled so the fastest joint moves `max_speed * dt`; the arm then glides back instead of jumping.

A policy calls it with the arm's CURRENT APPLIED targets (obs["applied"]["arm_targets"][side]) as `current`, not with its own last command.
"""

import numpy as np


def rate_limit(current, goal, max_speed, dt):
    current = np.asarray(current, float)
    goal = np.asarray(goal, float)
    delta = goal - current
    biggest = float(np.abs(delta).max()) if delta.size else 0.0
    step = max_speed * dt
    if biggest <= step:
        return goal
    return current + delta * (step / biggest)
