# Code generated by Claude
"""
Replay a recorded run (src/run_record.py): verify that the states match the live run exactly and render its cameras offline.

    from src.replay import replay_run
    report = replay_run("data/runs/run1", out_dir="data/runs/run1/replay", cameras=["eagle_cam"], hz=15)

The replay rebuilds the model from the recording's recipe (and checks its SHA-256), then runs src/control_loop.run_loop with
cfg["replay"]: the same spawn and settle, the same physics step, but the recorded ctrl and base velocity instead of sources. The
state after the settle and the state hash after every tick must equal the live run's, bit for bit; the first mismatch stops the
replay and reports the tick and which parts of the state differ (at the next 1 s checkpoint). Bit-exact reproduction is only
guaranteed on the same machine, MuJoCo version and CPU; on another one the replay says so and reports the mismatch.

Cameras: every `hz` (30 by default; a whole divisor of the physics rate) all selected cameras (default: all recorded) are rendered from the
state at that physics step, with the policy cameras' own settings by default (each camera's "shadows" flag as in robot_specs.CAMERA_SPECS).
`video` says what is written:
    "none"      verify only: no rendering, no GL, no output files (faster)
    "preview"   lossy MP4 (OpenCV, MPEG-4 part 2), one video per camera, out_dir/<camera>.mp4, playing at `hz` frames per second of sim time
    "training"  lossless PNG frames, one folder per camera, out_dir/<camera>/<tick:06d>.png (the control tick the frame was rendered in)
plus out_dir/frames.csv (frame, tick, sim_time) and out_dir/replay_report.json.
"""

import csv
import json
import time
from pathlib import Path

import cv2
import mujoco
import numpy as np

from src import robot_specs
from src.cameras import CameraRig
from src.control_loop import _headless_context, run_loop
from src.run_record import (describe_state_diff, get_state, jsonable, load_recording, model_hash, new_state_buffer, specs_snapshot,
                            state_hash)
from src.simulator import RobotSimulator
from src.task_beaker_hotplate import apply_task_poses, load_task

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def build_model(meta):
    """(model, data, reset) from the recording's recipe. `reset` repeats what the live run did to `data` before run_loop."""
    recipe = meta["model"]
    cams = meta["robot_specs"]["CAMERA_SPECS"]
    if recipe["kind"] == "task":
        task_cfg = recipe["task_cfg"]
        sim = load_task(cfg=task_cfg, cameras=cams)

        def reset(model, data):
            mujoco.mj_resetData(model, data)
            apply_task_poses(model, data, task_cfg)
    elif recipe["kind"] == "scene":
        sim = RobotSimulator(model_path=str(PROJECT_ROOT / recipe["scene"]), cameras=cams, pedestal_lift=robot_specs.PEDESTAL_SPECS)
        reset = lambda model, data: None
    else:
        raise ValueError(f"unknown model recipe {recipe!r}")
    return sim.model, sim.data, reset


CONTAINER = {"mp4v": ".mp4", "avc1": ".mp4", "VP90": ".webm", "VP80": ".webm", "MJPG": ".avi", "XVID": ".avi"}   # file extension per fourcc


def open_video(path, fps, size, codec="mp4v", quality=None):
    w = cv2.VideoWriter(str(path), cv2.VideoWriter_fourcc(*codec), fps, size)
    if not w.isOpened():
        raise RuntimeError(f"could not open a '{codec}' video writer for {path}")
    if quality is not None:
        w.set(cv2.VIDEOWRITER_PROP_QUALITY, quality)
    return w


class ReplayMismatch(RuntimeError):
    pass


class PngFrames:
    """Writes each frame as out/<camera>/<tick:06d>.png (lossless); same write / release interface as a cv2.VideoWriter."""

    def __init__(self, folder):
        self.folder = Path(folder)
        self.folder.mkdir(parents=True, exist_ok=True)

    def write(self, frame_bgr, tick):
        if not cv2.imwrite(str(self.folder / f"{tick:06d}.png"), frame_bgr):
            raise RuntimeError(f"could not write a PNG to {self.folder}")

    def release(self):
        pass


def replay_run(run_dir, out_dir=None, cameras=None, video="preview", hz=30.0, size=None, shadows="policy", codec="mp4v", quality=None,
               verify=True, max_ticks=None, render_ticks=None, quiet=False):
    """Replay `run_dir`. video: "none" | "preview" | "training" (see the module doc); cameras: names to render (None = all recorded); size: (w, h) override of the camera resolution;
    shadows: "policy" (per camera, as recorded), "on" or "off"; codec / quality: OpenCV fourcc and 0-100 quality (None = default).
    render_ticks: (first, last) tick range to render (None = all); the states are verified over the whole run, or up to max_ticks.
    Returns a report dict (also written to out_dir/replay_report.json): {"ok", "ticks", "mismatch", "videos", ...}."""
    wall0 = time.perf_counter()
    rec = load_recording(run_dir)
    meta = rec["meta"]
    n_ticks = len(rec["ctrl"]) if max_ticks is None else min(len(rec["ctrl"]), max_ticks)
    report = {"run": str(run_dir), "ok": None, "ticks": 0, "n_ticks_recorded": len(rec["ctrl"]), "mismatch": None, "warnings": [], "videos": {}}

    if specs_snapshot() != meta["robot_specs"]:
        report["warnings"].append("robot_specs differ from the recording's (the model hash below says whether the model changed)")
    model, data, reset = build_model(meta)
    if model_hash(model) != meta["model_sha256"]:
        raise ReplayMismatch("the rebuilt model differs from the recorded one (model_sha256): the scene, robot specs or MuJoCo changed")
    if mujoco.__version__ != meta["mujoco"] or meta["machine"] != __import__("platform").machine():
        report["warnings"].append(f"recorded with MuJoCo {meta['mujoco']} on {meta['machine']}; bit-exact replay is not guaranteed here")
    reset(model, data)

    spt = meta["steps_per_tick"]
    physics_hz = 1.0 / model.opt.timestep
    every = physics_hz / hz
    if abs(every - round(every)) > 1e-6:
        raise ValueError(f"camera rate {hz} Hz is not a whole divisor of the physics rate {physics_hz:.0f} Hz")
    every = int(round(every))

    # --- cameras and videos ---
    rig, specs, writers, frames_csv, gl_keepalive = None, [], {}, None, None
    out = Path(out_dir) if out_dir else None
    if video not in ("none", "preview", "training"):
        raise ValueError(f"video must be none, preview or training, not {video!r}")
    if video == "training" and hz > meta["source_hz"] + 1e-9:
        raise ValueError(f"training frames are named by tick: --hz must be at most the tick rate ({meta['source_hz']:g} Hz)")
    if video != "none":
        if out is None:
            raise ValueError(f"video={video!r} needs an out_dir")
        out.mkdir(parents=True, exist_ok=True)
        known = {cs["name"]: cs for cs in meta["robot_specs"]["CAMERA_SPECS"]}
        for name in (cameras if cameras else list(known)):
            if name not in known:
                raise ValueError(f"camera '{name}' not in the recording; has {sorted(known)}")
            cs = dict(known[name])
            if size:
                cs["resolution"] = tuple(size)
            else:
                cs["resolution"] = tuple(cs["resolution"])
            if shadows != "policy":
                cs["shadows"] = shadows == "on"
            if cs["resolution"][0] > model.vis.global_.offwidth or cs["resolution"][1] > model.vis.global_.offheight:
                raise ValueError(f"{cs['resolution']} is larger than the offscreen buffer "
                                 f"{model.vis.global_.offwidth}x{model.vis.global_.offheight} of the recorded cameras")
            specs.append(cs)
        gl_keepalive, context = _headless_context(model)
        rig = CameraRig(model, specs, context, shadows=bool(meta["loop_cfg"].get("camera_shadows", True)))
        for cs in specs:
            if video == "preview":
                path = out / f"{cs['name']}{CONTAINER.get(codec, '.mp4')}"
                writers[cs["name"]] = open_video(path, hz, tuple(cs["resolution"]), codec, quality)
            else:
                path = out / cs["name"]
                writers[cs["name"]] = PngFrames(path)
            report["videos"][cs["name"]] = str(path)
        frames_csv = open(out / "frames.csv", "w", newline="")
        fw = csv.writer(frames_csv)
        fw.writerow(["frame", "tick", "sim_time"])

    # --- verification state ---
    buf = new_state_buffer(model)
    st = {"mismatch": None, "pending": None, "frames": 0, "stop": False}

    def on_start(model_, data_):
        get_state(model_, data_, buf)
        if verify and not np.array_equal(buf, rec["initial_state"]):
            raise ReplayMismatch("the state after the settle differs from the live run's: " + "; ".join(describe_state_diff(model_, buf, rec["initial_state"])))

    def on_step(step_count, data_):
        if rig is not None and step_count % every == 0 and (render_ticks is None or render_ticks[0] <= (step_count - 1) // spt <= render_ticks[1]):
            rig.render(data_)
            tick = (step_count - 1) // spt
            for cs in specs:
                bgr = cv2.cvtColor(rig.images[cs["name"]], cv2.COLOR_RGB2BGR)
                writers[cs["name"]].write(bgr, tick) if video == "training" else writers[cs["name"]].write(bgr)
            fw.writerow([st["frames"], tick, f"{data_.time:.6f}"])
            st["frames"] += 1

    def on_tick_end(frame, data_):
        if not verify:
            return
        get_state(model, data_, buf)
        if st["mismatch"] is None and state_hash(buf) != int(rec["hashes"][frame]):
            st["mismatch"] = {"tick": frame, "sim_time": data_.time}
            if frame in rec["checkpoints"]:
                st["mismatch"]["differs"] = describe_state_diff(model, buf, rec["checkpoints"][frame])
                st["stop"] = True
            else:
                st["pending"] = True
        elif st["pending"] and frame in rec["checkpoints"]:
            st["mismatch"]["differs"] = [f"at checkpoint tick {frame}: " + s for s in describe_state_diff(model, buf, rec["checkpoints"][frame])]
            st["stop"] = True

    cfg = {**meta["loop_cfg"], "cameras": False, "inset_cameras": False, "record_run": None, "mode": "teleop", "auto_source": None, "on_tick": None, "held": None, "tick_ref": None,
           "bench_frames": 0, "bench_log": None, "hotkeys": {}, "routes": {},
           "replay": {"ctrl": rec["ctrl"], "basevel": rec["basevel"], "n_ticks": n_ticks, "on_start": on_start, "on_step": on_step,
                      "on_tick_end": on_tick_end, "stop": lambda: st["stop"]}}
    cfg["claimed_ids"] = list(cfg.get("claimed_ids") or ())
    try:
        result = run_loop(model, data, {}, cfg, viewer=None)
    finally:
        for w in writers.values():
            w.release()
        if frames_csv is not None:
            frames_csv.close()
        if gl_keepalive is not None:
            try:
                gl_keepalive.free()
            except Exception:
                pass

    report["ticks"] = result["frames"]
    report["mismatch"] = st["mismatch"]
    report["frames_rendered"] = st["frames"]
    report["ok"] = (st["mismatch"] is None and result["frames"] == n_ticks) if verify else None
    report["wall_seconds"] = time.perf_counter() - wall0
    if writers:
        report["video_bytes"] = {k: (sum(f.stat().st_size for f in Path(v).glob("*.png")) if Path(v).is_dir() else Path(v).stat().st_size)
                                 for k, v in report["videos"].items() if Path(v).exists()}
    if video != "none":
        (out / "replay_report.json").write_text(json.dumps(jsonable(report), indent=1))
    if not quiet:
        if verify:
            print(("VERIFIED: " + f"{report['ticks']} ticks ({report['ticks'] / meta['source_hz']:.1f} s sim), every state bit-identical to the live run")
                  if report["ok"] else f"MISMATCH: {report['mismatch']}")
        for w in report["warnings"]:
            print("warning:", w)
        if writers:
            print(f"{video}: rendered {st['frames']} frames per camera at {hz:g} Hz: " + ", ".join(f"{k} {v / 1e6:.1f} MB" for k, v in report["video_bytes"].items())
                  + f"  ({report['wall_seconds']:.0f} s wall)")
    return report
