"""
Code generated by Claude

Robot hardware specifications extracted from Tracer_Pedestal.xml

These values are currently used in the MuJoCo simulation.
They will be calibrated/updated when physical hardware is available.
"""

# Simulation rates
# 750 Hz is the OpenArm ros2_control low level loop (Luke Chen).
# 30 fps is the Orbbec cameras (Luke Chen).
# Teleop targets are NOT clocked here: SEW-Mimic computes faster (retargeting
# 60 kHz, safety filter 3 kHz per Kong), but on hardware the 750 Hz loop is
# the ceiling, so the sim uses the latest target on each PD step.
PHYSICS_HZ = 750
PD_HZ = 750
CAMERA_HZ = 30
SIMULATION_TIMESTEP = 1 / PHYSICS_HZ  # seconds (sim choice: one physics step per PD step)
SIMULATION_FREQUENCY = PHYSICS_HZ

# Tracer Mobile Base
TRACER_SPECS = {
    "name": "Agilex Tracer X2",
    "control_frequency": PD_HZ,  # Hz
    
    # Wheels
    "drive_wheels": {
        "friction": 1.5,  # High grip
        "gear_ratio": 10,  # Motor:wheel
        "max_torque": 10,  # N·m (estimated from gearing)
    },
    
    "caster_wheels": {
        "friction": 0.1,  # Low friction for turning
    },
    
    # Pedestal (arm mounting)
    "pedestal": {
        "bottom_joint_damping": 800,  # Stiff
        "top_joint_damping": 50000,   # Very stiff
        "max_height_range": 0.5,      # ±0.25 m each joint
    },
}

# OpenArm Bimanual Manipulator
OPENARM_SPECS = {
    "name": "OpenArm Bimanual",
    "arms": 2,  # Left and right
    "dof_per_arm": 7,  # Joints
    
    # Motors by joint type
    "motors": {
        "shoulder_elbow": {
            "model": "DM8009",
            "torque_nm": 40,
            "kp": 100,  # Restored from 10 — at Kp=10, shoulder needs 4 rad
            "kd": 10,   # error to reach max torque, can't overcome gravity
            "damping": 0.4,
        },
        "wrist": {
            "model": "DM4340",
            "torque_nm": 27,
            "kp": 80,
            "kd": 8,
            "damping": 0.4,
        },
        "wrist_fine": {
            "model": "DM4310",
            "torque_nm": 7,
            "kp": 50,
            "kd": 5,
            "damping": 0.4,
        },
    },
    
    # Gripper
    "gripper": {
        "model": "DM4310",
        "motor_type": "position_control",  # Right arm
        "motor_type_left": "motor_control",  # Left arm (asymmetry)
        "max_opening": 0.044,  # meters
    },
}

# Cameras
# PLACEHOLDER: exact Orbbec model unknown, so resolution and FOV are guesses.
ORBBEC_RESOLUTION = (640, 480)  # (width, height)
ORBBEC_FOVY_DEG = 58.0

# All camera poses are PLACEHOLDERS until mounting info arrives.
# - The eagle cam is confirmed robot mounted. Parent openarm_body_link0 is a
#   placeholder: the exact mounting body (torso/pedestal top vs. Tracer base)
#   is unconfirmed.
# - pos / look_at / up are in the parent body's frame.
# - The hand frame has the gripper along +Z (TCP at 0.08) and fingers along Y,
#   so the wrist cam sits off to +X and set back so the fingertips are in view.
CAMERA_SPECS = [
    {
        "name": "eagle_cam",
        "parent": "openarm_body_link0",
        "pos": [0.05, 0.0, 0.45],
        "look_at": [0.60, 0.0, -0.40],
        "up": [0.0, 0.0, 1.0],
        "fovy": ORBBEC_FOVY_DEG,
        "resolution": ORBBEC_RESOLUTION,
    },
    {
        "name": "right_wrist_cam",
        "parent": "openarm_right_hand",
        "pos": [0.06, 0.0, -0.03],
        "look_at": [0.0, 0.0, 0.12],
        "up": [1.0, 0.0, 0.0],
        "fovy": ORBBEC_FOVY_DEG,
        "resolution": ORBBEC_RESOLUTION,
    },
    {
        "name": "left_wrist_cam",
        "parent": "openarm_left_hand",
        "pos": [0.06, 0.0, -0.03],
        "look_at": [0.0, 0.0, 0.12],
        "up": [1.0, 0.0, 0.0],
        "fovy": ORBBEC_FOVY_DEG,
        "resolution": ORBBEC_RESOLUTION,
    },
]

# Global joint damping (prevents infinite spinning)
GLOBAL_DAMPING = 0.4

# Status of calibration
CALIBRATION_STATUS = {
    "inertia_matrices": "ESTIMATED (from CAD, need real measurement)",
    "friction_coefficients": "ROUGH ESTIMATE (need measurement)",
    "control_latency": "MODELED AS 0.002s (actual ROS latency unknown)",
    "backlash_deadband": "NOT MODELED (need measurement when hardware available)",
    "motor_response": "MODELED FROM SPECS (need tuning)",
    "camera_intrinsics": "PLACEHOLDER (Orbbec model unknown; resolution/FOV guessed)",
    "camera_mounting": "PLACEHOLDER (poses guessed until mounting info arrives)",
}

# When hardware arrives, update these
CALIBRATION_TODO = """
PRIORITY 1 (Critical for sim-to-real):
- [ ] Measure actual motor torque constants
- [ ] Measure joint friction and damping
- [ ] Measure control latency with ROS overhead
- [ ] Measure backlash/deadbands

PRIORITY 2 (Important):
- [ ] Verify inertia matrices from CAD
- [ ] Measure gripper grip force
- [ ] Characterize wheel slip/friction

PRIORITY 3 (Nice-to-have):
- [ ] Electromagnetic noise/ripple
- [ ] Temperature effects on motors
- [ ] Wear patterns over time
"""