"""
Code generated by Claude

Robot hardware specifications extracted from Tracer_Pedestal.xml

These values are currently used in the MuJoCo simulation.
They will be calibrated/updated when physical hardware is available.
"""

# Simulation rates
# 750 Hz is the OpenArm ros2_control low level loop (Luke Chen).
# 30 fps is the Orbbec cameras (Luke Chen).
# Teleop targets are NOT clocked here: SEW-Mimic computes faster (retargeting
# 60 kHz, safety filter 3 kHz per Kong), but on hardware the 750 Hz loop is
# the ceiling, so the sim uses the latest target on each PD step.
PHYSICS_HZ = 750
PD_HZ = 750
CAMERA_HZ = 30  # camera tick rate; set CC_ROUNDROBIN=0 in the viewer so every camera updates at this rate
SIMULATION_TIMESTEP = 1 / PHYSICS_HZ  # seconds (sim choice: one physics step per PD step)
SIMULATION_FREQUENCY = PHYSICS_HZ

# Tracer Mobile Base
TRACER_SPECS = {
    "name": "Agilex Tracer X2",
    "control_frequency": PD_HZ,  # Hz
    
    # Wheels
    "drive_wheels": {
        "friction": 1.5,  # High grip
        "gear_ratio": 10,  # Motor:wheel
        "max_torque": 10,  # N·m (estimated from gearing)
    },
    
    "caster_wheels": {
        "friction": 0.1,  # Low friction for turning
    },
    
    # Pedestal (arm mounting)
    "pedestal": {
        "bottom_joint_damping": 800,  # Stiff
        "top_joint_damping": 50000,   # Very stiff
        "max_height_range": 0.5,      # ±0.25 m each joint
    },
}

# Pedestal lift actuator -- PLACEHOLDER
# The real lift hardware is unconfirmed (waiting on Dan's answer), and the pedestal model
# itself is marked "estimated" in the OpenArm-Combined README (Telescoping_Pedestal.xml).
# Until then the sim gets one stand-in position actuator, added at load time by
# src/pedestal.add_pedestal_lift(): the two sliding stages are coupled (TopMiddle follows
# MiddleBottom) and a single height command drives MiddleBottom, like a single lift motor.
# Every number here is a guess to be replaced when the hardware is known.
PEDESTAL_SPECS = {
    "actuator_name": "pedestal_lift",
    "joints": ("MiddleBottom", "TopMiddle"),      # lower stage, upper stage
    # Per-stage slide, m, from the XML joint range: 0 = fully raised, -0.25 = XML limit. The
    # stages stack, so the top of the pedestal moves twice this.
    "stage_range": (-0.25, 0.0),
    # Lowest command (also the Page Down clamp). The robot's torso collision mesh first touches
    # pedestal_Bottom at -0.2290 per stage (458 mm of total drop; measured with mj_geomDistance),
    # and that contact is kept as the lower stop. -0.228 leaves room for the ~1 mm the stage sags
    # under load (kp below), so the actuator settles at the touch point and never pushes into it.
    # The real minimum height is pending Dan.
    "lowest_command": -0.228,
    "target_height": 0.0,                         # default command: fully raised
    # Bodies whose collision hulls are excluded from each other, see src/pedestal.py.
    "nested_bodies": ("pedestal_Bottom", "pedestal_Top"),
    # Stand-in position servo on MiddleBottom. Load it must hold (from the body masses,
    # see src/pedestal.pedestal_load): 56.0 kg above MiddleBottom + 45.0 kg above TopMiddle;
    # with the stages coupled both loads act on the one actuator, 991 N. kp = 1e6 N/m
    # sags ~1 mm under that. forcerange is ~5x the hold force: the XML joint damping (800 and
    # 50000 N s/m on the two stages, not ours to change) makes the lift speed ~ force / 51 kN s/m.
    "kp": 1.0e6,                                  # N/m
    "kv": 0.0,                                    # N s/m (joint damping already dominates)
    "force_limit": 5000.0,                        # N
    "jog_speed": 0.05,                            # m/s of stage travel while a key is held
}

# OpenArm Bimanual Manipulator
OPENARM_SPECS = {
    "name": "OpenArm Bimanual",
    "arms": 2,  # Left and right
    "dof_per_arm": 7,  # Joints
    
    # Motors by joint type
    "motors": {
        "shoulder_elbow": {
            "model": "DM8009",
            "torque_nm": 40,
            "kp": 100,  # Restored from 10 — at Kp=10, shoulder needs 4 rad
            "kd": 10,   # error to reach max torque, can't overcome gravity
            "damping": 0.4,
        },
        "wrist": {
            "model": "DM4340",
            "torque_nm": 27,
            "kp": 80,
            "kd": 8,
            "damping": 0.4,
        },
        "wrist_fine": {
            "model": "DM4310",
            "torque_nm": 7,
            "kp": 50,
            "kd": 5,
            "damping": 0.4,
        },
    },
    
    # Gripper
    "gripper": {
        "model": "DM4310",
        "motor_type": "position_control",  # Right arm
        "motor_type_left": "motor_control",  # Left arm (asymmetry)
        "max_opening": 0.044,  # meters
    },
}

# Cameras
# PLACEHOLDER: exact Orbbec model unknown, so resolution and FOV are guesses.
ORBBEC_RESOLUTION = (640, 480)  # (width, height)
ORBBEC_FOVY_DEG = 58.0

# All camera poses are PLACEHOLDERS until mounting info arrives.
# - The eagle cam is confirmed robot mounted. Parent openarm_body_link0 is a
#   placeholder: the exact mounting body (torso/pedestal top vs. Tracer base)
#   is unconfirmed.
# - pos / look_at / up are in the parent body's frame.
# - The hand frame has the gripper along +Z (TCP at 0.08) and fingers along Y,
#   so the wrist cam sits off to +X and set back so the fingertips are in view.
CAMERA_SPECS = [
    {
        "name": "eagle_cam",
        "parent": "openarm_body_link0",
        "pos": [0.05, 0.0, 0.45],
        "look_at": [1.0, 0.0, 0.45],
        "up": [0.0, 0.0, 1.0],
        "fovy": ORBBEC_FOVY_DEG,
        "resolution": ORBBEC_RESOLUTION,
        # Shadows make no visible difference in this view but cost ~10x the
        # render time on the VM; the wrist cams need them for finger contrast.
        "shadows": False,
    },
    {
        "name": "right_wrist_cam",
        "parent": "openarm_right_hand",
        "pos": [0.06, 0.0, -0.03],
        "look_at": [0.0, 0.0, 0.12],
        "up": [1.0, 0.0, 0.0],
        "fovy": ORBBEC_FOVY_DEG,
        "resolution": ORBBEC_RESOLUTION,
    },
    {
        "name": "left_wrist_cam",
        "parent": "openarm_left_hand",
        "pos": [0.06, 0.0, -0.03],
        "look_at": [0.0, 0.0, 0.12],
        "up": [1.0, 0.0, 0.0],
        "fovy": ORBBEC_FOVY_DEG,
        "resolution": ORBBEC_RESOLUTION,
    },
]

# Global joint damping (prevents infinite spinning)
GLOBAL_DAMPING = 0.4

# Status of calibration
CALIBRATION_STATUS = {
    "inertia_matrices": "ESTIMATED (from CAD, need real measurement)",
    "friction_coefficients": "ROUGH ESTIMATE (need measurement)",
    "control_latency": "MODELED AS 0.002s (actual ROS latency unknown)",
    "backlash_deadband": "NOT MODELED (need measurement when hardware available)",
    "motor_response": "MODELED FROM SPECS (need tuning)",
    "camera_intrinsics": "PLACEHOLDER (Orbbec model unknown; resolution/FOV guessed)",
    "camera_mounting": "PLACEHOLDER (poses guessed until mounting info arrives)",
}

# When hardware arrives, update these
CALIBRATION_TODO = """
PRIORITY 1 (Critical for sim-to-real):
- [ ] Measure actual motor torque constants
- [ ] Measure joint friction and damping
- [ ] Measure control latency with ROS overhead
- [ ] Measure backlash/deadbands

PRIORITY 2 (Important):
- [ ] Verify inertia matrices from CAD
- [ ] Measure gripper grip force
- [ ] Characterize wheel slip/friction

PRIORITY 3 (Nice-to-have):
- [ ] Electromagnetic noise/ripple
- [ ] Temperature effects on motors
- [ ] Wear patterns over time
"""