# Code generated by Claude
"""
Record a live run so it can be replayed exactly (src/replay.py renders its cameras offline and verifies the states).

What is recorded is what the physics received, not what the sources decided, so a keyboard, teleop, policy or scripted run all
replay the same way. Per control tick (62.5 Hz): the full ctrl vector written for the tick and the world-frame base velocity
(vx, vy, wz) written before each of the tick's physics steps, both as exact float64. Verification data: the integration state
right after the settle, a hash of the state after every tick, and a full state checkpoint every `checkpoint_every` ticks (to say
what differs when a hash does not match).

    run_dir/
        meta.json              recipe to rebuild the model, loop config, camera specs, rates, spawn, git commit, MuJoCo version, labels
        initial_state.npy      the state after the settle (the replay compares its own settle against it)
        chunks/chunk_00000.npz ... ticks [start, start + n): ctrl[n, nu], basevel[n, 3], hashes[n] (uint64), checkpoint ticks and states

Chunks are written every `chunk_ticks` ticks while the run goes, so a crash loses at most the last chunk. About 13 KB per sim second.
"""

import hashlib
import json
import platform
import subprocess
import time
from pathlib import Path

import mujoco
import numpy as np

from src import robot_specs

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# State vector compared by the replay: time, positions, velocities, actuator activations, the solver warm start and ctrl.
STATE_SPEC = (mujoco.mjtState.mjSTATE_TIME | mujoco.mjtState.mjSTATE_QPOS | mujoco.mjtState.mjSTATE_QVEL
              | mujoco.mjtState.mjSTATE_ACT | mujoco.mjtState.mjSTATE_WARMSTART | mujoco.mjtState.mjSTATE_CTRL)


def state_layout(model):
    """[(name, size)] of the pieces of the state vector, in order."""
    return [("time", 1), ("qpos", model.nq), ("qvel", model.nv), ("act", model.na), ("qacc_warmstart", model.nv), ("ctrl", model.nu)]


def new_state_buffer(model):
    return np.zeros(mujoco.mj_stateSize(model, STATE_SPEC))


def get_state(model, data, buf):
    mujoco.mj_getState(model, data, buf, STATE_SPEC)
    return buf


def state_hash(buf):
    return int.from_bytes(hashlib.blake2b(buf.tobytes(), digest_size=8).digest(), "little")


def describe_state_diff(model, a, b):
    """Which pieces of two state vectors differ, and by how much."""
    out, i = [], 0
    for name, n in state_layout(model):
        d = np.abs(a[i:i + n] - b[i:i + n])
        if n and d.max() > 0:
            out.append(f"{name}: max |diff| {d.max():.3e} (index {int(d.argmax())})")
        i += n
    return out or ["identical"]


def model_hash(model):
    """SHA-256 of the compiled model's arrays, counts and solver options (so a different scene, camera set or edit shows).

    Not the display settings (model.vis: field of view, shadow size...): the GLFW viewer changes those after loading, and they
    do not affect the physics."""
    h = hashlib.sha256()

    def add(name, v):
        h.update(name.encode())
        h.update(np.ascontiguousarray(v).tobytes() if isinstance(v, np.ndarray) else repr(v).encode())
    for name in sorted(dir(model)):
        if name.startswith("_") or name in ("vis", "opt", "stat"):
            continue
        v = getattr(model, name)
        if isinstance(v, np.ndarray) or (name.startswith("n") and isinstance(v, int)):
            add(name, v)
    for name in sorted(dir(model.opt)):
        if not name.startswith("_") and not callable(getattr(model.opt, name)):
            add("opt." + name, getattr(model.opt, name))
    return h.hexdigest()


def jsonable(obj):
    """`obj` with callables dropped and numpy / tuples turned into JSON types."""
    if isinstance(obj, dict):
        return {str(k): jsonable(v) for k, v in obj.items() if not callable(v)}
    if isinstance(obj, (list, tuple, set)):
        return [jsonable(v) for v in obj if not callable(v)]
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, (np.floating, np.integer, np.bool_)):
        return obj.item()
    if obj is None or isinstance(obj, (bool, int, float, str)):
        return obj
    return str(obj)


def specs_snapshot():
    """The robot_specs values a replay needs or should notice a change in."""
    return jsonable({"CAMERA_SPECS": robot_specs.CAMERA_SPECS, "PEDESTAL_SPECS": robot_specs.PEDESTAL_SPECS,
                     "NECK_SPECS": robot_specs.NECK_SPECS, "CAMERA_HZ": robot_specs.CAMERA_HZ, "PHYSICS_HZ": robot_specs.PHYSICS_HZ})


def _git_info():
    try:
        run = lambda *a: subprocess.run(["git", *a], cwd=PROJECT_ROOT, capture_output=True, text=True, timeout=10).stdout.strip()
        return {"commit": run("rev-parse", "HEAD"), "dirty": bool(run("status", "--porcelain", "--untracked-files=no"))}
    except Exception:
        return {"commit": None, "dirty": None}


class RunRecorder:
    """Created by control_loop.run_loop after the settle when cfg["record_run"] is set."""

    def __init__(self, run_dir, model, data, loop_cfg, meta_extra, source_hz, steps_per_tick, chunk_ticks=1000, checkpoint_every=62):
        if not (meta_extra or {}).get("model"):
            raise ValueError('recording a run needs cfg["record_meta"]["model"]: the recipe to rebuild the model '
                             '({"kind": "scene", "scene": path} or {"kind": "task", "task_cfg": {...}})')
        self.dir = Path(run_dir)
        (self.dir / "chunks").mkdir(parents=True, exist_ok=True)
        self.model, self.data = model, data
        self.chunk_ticks, self.checkpoint_every = chunk_ticks, checkpoint_every
        self.buf = new_state_buffer(model)
        self.ctrl, self.basevel, self.hashes = [], [], []
        self.ck_ticks, self.ck_states = [], []
        self.start_tick, self.n_chunks, self.n_ticks = 0, 0, 0
        self.labels = []
        np.save(self.dir / "initial_state.npy", get_state(model, data, self.buf).copy())
        self.meta = {
            "format": 1, "complete": False, "started": time.strftime("%Y-%m-%d %H:%M:%S"),
            "model_sha256": model_hash(model), "nq": model.nq, "nv": model.nv, "nu": model.nu,
            "timestep": model.opt.timestep, "steps_per_tick": steps_per_tick, "source_hz": source_hz,
            "loop_cfg": jsonable(loop_cfg), "mujoco": mujoco.__version__, "platform": platform.platform(),
            "machine": platform.machine(), "python": platform.python_version(), "git": _git_info(),
            "checkpoint_every": checkpoint_every, "seed": None, "robot_specs": specs_snapshot(), **jsonable(meta_extra or {}),
        }
        self._write_meta()

    def _write_meta(self):
        (self.dir / "meta.json").write_text(json.dumps({**self.meta, "labels": self.labels, "n_ticks": self.n_ticks}, indent=1))

    def tick(self, frame, ctrl, basevel):
        """Inputs of tick `frame`, called after ctrl is written and before the physics steps."""
        self.ctrl.append(np.array(ctrl, dtype=np.float64))
        self.basevel.append(np.array(basevel, dtype=np.float64))

    def label(self, frame, text):
        if text and (not self.labels or self.labels[-1]["label"] != text):
            self.labels.append({"tick": frame, "label": text})

    def end_tick(self, frame, data):
        """State after tick `frame`'s physics steps."""
        get_state(self.model, data, self.buf)
        self.hashes.append(state_hash(self.buf))
        if frame % self.checkpoint_every == 0:
            self.ck_ticks.append(frame)
            self.ck_states.append(self.buf.copy())
        self.n_ticks = frame + 1
        if len(self.ctrl) >= self.chunk_ticks:
            self._flush()

    def _flush(self):
        if not self.hashes:
            return
        n = len(self.hashes)                        # a tick whose physics did not finish has inputs but no hash: dropped
        np.savez(self.dir / "chunks" / f"chunk_{self.n_chunks:05d}.npz", start=self.start_tick, ctrl=np.array(self.ctrl[:n]),
                 basevel=np.array(self.basevel[:n]), hashes=np.array(self.hashes, dtype=np.uint64), ck_ticks=np.array(self.ck_ticks, dtype=np.int64),
                 ck_states=np.array(self.ck_states).reshape(len(self.ck_states), -1))
        self.start_tick += n
        self.n_chunks += 1
        self.ctrl, self.basevel, self.hashes, self.ck_ticks, self.ck_states = [], [], [], [], []
        self._write_meta()

    def close(self, extra=None):
        self._flush()
        self.meta.update(complete=True, finished=time.strftime("%Y-%m-%d %H:%M:%S"), **jsonable(extra or {}))
        self._write_meta()
        print(f"Run recorded: {self.dir}  ({self.n_ticks} ticks, {self.n_ticks / self.meta['source_hz']:.1f} s sim time)")


def load_recording(run_dir):
    """meta, initial_state, ctrl[T, nu], basevel[T, 3], hashes[T] (uint64), checkpoints {tick: state}."""
    run_dir = Path(run_dir)
    meta = json.loads((run_dir / "meta.json").read_text())
    files = sorted((run_dir / "chunks").glob("chunk_*.npz"))
    if not files:
        raise ValueError(f"{run_dir}: no recorded ticks")
    parts = [np.load(f) for f in files]
    ctrl = np.concatenate([p["ctrl"] for p in parts])
    basevel = np.concatenate([p["basevel"] for p in parts])
    hashes = np.concatenate([p["hashes"] for p in parts])
    ck = {int(t): s for p in parts for t, s in zip(p["ck_ticks"], p["ck_states"])}
    if int(parts[0]["start"]) != 0:
        raise ValueError(f"{run_dir}: the first chunk does not start at tick 0")
    if not meta.get("complete"):
        print(f"WARNING: {run_dir} was not closed cleanly (crash?); using the {len(ctrl)} ticks that were written")
    return {"meta": meta, "initial_state": np.load(run_dir / "initial_state.npy"), "ctrl": ctrl, "basevel": basevel,
            "hashes": hashes, "checkpoints": ck}
