# Code generated by Claude
"""
Run geo_kin's SEW-Mimic collision filter on ROBOT joint angles.

The filter lives inside the teleop solver, whose input is a human pose, so it
normally only runs inside teleop's solve(). This module lets manual and policy
code use it too: give it arm joint angles, get back collision-free arm joint
angles.

THE ROUND TRIP
    joint angles --robot FK--> S, E, W points + wrist rotation
                 --> RetargetFrame ("human" input that is really the robot)
                 --> session.solve()  (SEW filter + IK, collision_avoidance=True)
                 --> filtered joint angles

  * S, E, W are the solver's own robot-side forward kinematics,
    session.robot_fk_at(), in the solver frame (origin at the arm base link
    + (0, 0, 0.698), axes x forward / y left / z up). S is the shoulder
    (joint 1-3 axes intersection), E is the elbow point on the arm's centre
    line (joint-4 origin shifted 0.0315 m along its axis) and W is the wrist
    centre (joint 7 origin). They agree with an independent MuJoCo-geometry
    computation to ~1e-16 m (see experiments/safety_filter_roundtrip.py,
    which keeps that computation as a cross-check).
  * robot_fk_at() is documented as Vega-only but works for OpenArm in
    geo_kin 0.1.0. That is undocumented behaviour: re-check after upgrading
    geo_kin (the cross-check in safety_filter_roundtrip.py will catch a change).
  * The wrist rotation sent to the solver is  R_0_7 @ C , where R_0_7 is the
    robot's link-7 rotation from robot_fk_at() and C is a fixed rotation that
    maps the robot's link-7 frame onto the human hand frame the solver expects
    as input (x toward the fingers, y palm normal):
        C = [[0, 0, 1], [0, -1, 0], [1, 0, 0]]
    C was found by trying all 24 axis-aligned rotations against the solver; it
    is the only one that works (exactly zero round-trip error with the filter
    off), for both arms.
  * The session is built with functional_offset=False and retarget_mode="pose"
    so the solver adds no human-to-robot adjustments, and
    collision_avoidance=True (the safety filter; the application never turns
    it off. collision_avoidance=False exists only for tests that need a control).

CAVEATS (measured with experiments/safety_filter_roundtrip.py)
  * The filter is conservative: it also changes some poses MuJoCo finds
    contact-free, and it re-solves IK, so joint changes can be much larger
    than the point changes (the wrist especially).
  * Near joint limits the IK can return a DIFFERENT valid arm solution than the
    input even with the filter off (joints 3 and 5 jump by up to ~1.6 rad). See
    experiments/branch_jump_demo.py.
  * The filter does not clip to joint limits (solver option `limited` is off).
  * A solve takes about 0.05 ms.

Usage
    from src.safety_filter import SafetyFilter, filter_joints
    q_left, q_right = filter_joints(q_left, q_right)         # shared instance
    sf = SafetyFilter(); ql, qr = sf.filter(ql, qr, q_current_left=..., reset=False)
"""

import numpy as np

# Fixed rotation: robot link-7 frame -> human hand frame (see module docstring).
C_HAND = np.array([[0.0, 0.0, 1.0],
                   [0.0, -1.0, 0.0],
                   [1.0, 0.0, 0.0]])
SIDES = ("left", "right")
N_ARM_JOINTS = 7


def _arm(q, name):
    q = np.asarray(q, dtype=float)
    if q.shape != (N_ARM_JOINTS,) or not np.isfinite(q).all():
        raise ValueError(f"{name}: expected 7 finite joint angles, got {q!r}")
    return q


class SafetyFilter:
    """A geo_kin OpenArm session used as a joint-angle collision filter."""

    def __init__(self, collision_avoidance: bool = True):
        # Imported here so `import src.safety_filter` needs neither package
        # until a filter is actually built.
        from openarm_teleop.session import make_session
        self.collision_avoidance = collision_avoidance
        self.session = make_session(
            collision_avoidance=collision_avoidance,
            functional_offset=False, retarget_mode="pose")
        self.default_q = {s: np.asarray(self.session.default_q[s], dtype=float)
                          for s in SIDES}

    def frame(self, q_left, q_right):
        """RetargetFrame whose arms are exactly the given joint angles."""
        from geo_kin_core.types import RetargetFrame, SEWPose
        q_left, q_right = _arm(q_left, "q_left"), _arm(q_right, "q_right")
        fk = self.session.robot_fk_at(q_right=q_right, q_left=q_left)
        poses = {}
        for side in SIDES:
            f = fk[side]
            poses[side] = SEWPose(
                S=np.asarray(f["S"], dtype=float), E=np.asarray(f["E"], dtype=float),
                W=np.asarray(f["W"], dtype=float),
                R_world_wrist=np.asarray(f["R_0_7"], dtype=float) @ C_HAND)
        return RetargetFrame(
            left_sew=poses["left"], right_sew=poses["right"],
            R_world_upper_body=np.asarray(fk["R_base_body"], dtype=float),
            p_world_upper_body=np.asarray(fk["p_base_body"], dtype=float))

    def solve(self, frame, q_current_left, q_current_right, reset=False,
              q_reset=None):
        """Run the solver on a frame; returns (q_left, q_right) as new arrays."""
        if reset:
            ql, qr = q_reset if q_reset is not None else (q_current_left, q_current_right)
            self.session.reset(_arm(qr, "reset right"), _arm(ql, "reset left"))
        out = self.session.solve(
            frame, engaged=True,
            q_current_right=_arm(q_current_right, "q_current_right"),
            q_current_left=_arm(q_current_left, "q_current_left"))
        if out.q_goal_left is None or out.q_goal_right is None:
            raise RuntimeError("solver returned no goal for an arm")
        return np.array(out.q_goal_left, dtype=float), np.array(out.q_goal_right, dtype=float)

    def filter(self, q_left, q_right, q_current_left=None, q_current_right=None,
               reset=True):
        """Filter a pair of 7-joint arm configs; returns (q_left, q_right).

        q_current_*  The robot's current joints, used to seed the IK. Defaults
                     to the input angles.
        reset        Reset the solver to the seed first (the default; every
                     call independent). Use False to stream, feeding the
                     previous output (or the robot's measured joints) back
                     as q_current_*.
        """
        q_left, q_right = _arm(q_left, "q_left"), _arm(q_right, "q_right")
        cl = q_left if q_current_left is None else q_current_left
        cr = q_right if q_current_right is None else q_current_right
        return self.solve(self.frame(q_left, q_right), cl, cr, reset=reset)

    __call__ = filter


_shared = None


def filter_joints(q_left, q_right, **kwargs):
    """Filter arm joint angles with a lazily created shared SafetyFilter."""
    global _shared
    if _shared is None:
        _shared = SafetyFilter(collision_avoidance=True)
    return _shared.filter(q_left, q_right, **kwargs)
