"""Generic MuJoCo robot simulator — single environment controller for any scene.

Code generated by Claude
"""

from pathlib import Path
import mujoco
import numpy as np
from src import robot_specs
from src.arm_actuators import add_arm_actuators
from src.cameras import add_cameras, make_offscreen_big_enough
from src.neck import add_neck
from src.pedestal import add_pedestal_lift


class RobotSimulator:
    """Generic simulation controller for the Tracer + OpenArm robot in any scene.

    Works with whatever scene XML you point it at (single_block.xml,
    chemistry_lab.xml, a bare robot, etc.) — nothing here is tied to a
    specific scene's object names. If a scene has objects you want to track
    each step (a block, a beaker, a workbench), name them via `track_bodies`
    instead of adding new methods or subclasses per scene.
    """

    def __init__(self, model_path: str = None, track_bodies: list[str] = None,
                 cameras: list[dict] = None, pedestal_lift: dict = None,
                 neck=True):
        """
        Initialize simulator.

        Args:
            model_path: Path to MJCF model/scene file. A scene file should
                <include> the robot model at the top level (see
                learnings-and-workflow notes on <include> placement).
                Defaults to the bare combined robot with no scene objects.
            track_bodies: Names of bodies in the scene whose position/velocity
                should be included in get_observation() (e.g. ["block"], or
                ["beaker_1", "beaker_2"] for a chemistry scene). Optional —
                you can always query any body on demand with get_body_state(),
                whether or not it's in this list.
            cameras: Optional list of camera spec dicts (robot_specs.CAMERA_SPECS).
                If given, the cameras are injected into the model via MjSpec
                before compiling, and the offscreen buffer is sized to fit them.
            pedestal_lift: Optional robot_specs.PEDESTAL_SPECS. If given, the
                placeholder pedestal lift (stage coupling + one position
                actuator, appended as the last actuator) is added via MjSpec.
                Off by default: it changes the actuator count from 20 to 21.
            neck: the SO-101 camera neck (src/neck.py, robot_specs.NECK_SPECS), attached to the torso after the pedestal
                lift, before the cameras (the eagle camera is on the neck). True = robot_specs.NECK_SPECS, a dict = those
                specs, None / False = no neck (then the eagle camera has no body to sit on: pass cameras without it).
        """
        if model_path is None:
            project_root = Path(__file__).parent.parent
            model_path = project_root / "deps/OpenArm-Combined/combined_robot.xml"

        # Sim choice: resolve to an absolute path because MjSpec mesh loading
        # fails on relative paths.
        model_path = Path(model_path).resolve()
        if not model_path.exists():
            raise FileNotFoundError(f"Model not found: {model_path}")

        # Sim choice: the arm/finger position actuators (always), cameras and the pedestal lift
        # are added programmatically so the scene XMLs stay free of them and their numbers live
        # in robot_specs.
        spec = mujoco.MjSpec.from_file(str(model_path))
        add_arm_actuators(spec)
        if pedestal_lift:
            add_pedestal_lift(spec, pedestal_lift)
        if neck:
            add_neck(spec, robot_specs.NECK_SPECS if neck is True else neck)
        if cameras:
            add_cameras(spec, cameras)
        self.model = spec.compile()
        if cameras:
            make_offscreen_big_enough(self.model, cameras)
            # Sim choice: MuJoCo's near clip plane is znear * scene extent, and
            # this scene's extent is ~24 m (-> ~0.24 m near plane), which clips
            # the fingertips ~0.1 m from the wrist cams. Pull it in to ~1 cm.
            self.model.vis.map.znear = 0.0005

        # Sim choice: robot_specs is the single source of truth for the physics
        # rate, whatever the XML says.
        xml_dt = self.model.opt.timestep
        self.model.opt.timestep = robot_specs.SIMULATION_TIMESTEP
        if not np.isclose(xml_dt, robot_specs.SIMULATION_TIMESTEP):
            print(f"  Note: overriding XML timestep {xml_dt:.6g} s with "
                  f"{robot_specs.SIMULATION_TIMESTEP:.6g} s "
                  f"({robot_specs.PHYSICS_HZ} Hz) from robot_specs")
        self.data = mujoco.MjData(self.model)
        self.model_path = model_path
        self.track_bodies = track_bodies or []

        print(f"✓ Loaded model: {model_path.name}")
        print(f"  Bodies: {self.model.nbody}")
        print(f"  Joints: {self.model.njnt}")
        print(f"  Actuators: {self.model.nu}")
        print(f"  Cameras: {self.model.ncam}")

    def step(self):
        """Step physics simulation forward."""
        mujoco.mj_step(self.model, self.data)

    def reset(self):
        """Reset environment to initial state."""
        mujoco.mj_resetData(self.model, self.data)

    def close(self):
        """Clean up."""
        pass

    def get_time(self) -> float:
        """Get current simulation time."""
        return self.data.time

    def get_body_state(self, body_name: str) -> dict:
        """Get position and velocity for any named body in the loaded scene.

        This is the generic replacement for the old scene-specific
        get_block_position() / get_block_velocity(). It works for any body
        present in whichever model_path was loaded — a block, a beaker, a
        workbench, anything. If the name isn't in the current scene, MuJoCo
        raises a KeyError, which is the correct failure mode (better than
        silently returning garbage for a body that doesn't exist here).
        """
        body = self.data.body(body_name)
        return {
            "position": body.xpos.copy(),
            "velocity": body.cvel.copy(),
        }

    def get_observation(self) -> dict:
        """Get full observation: robot state + state of any tracked bodies.

        Which extra bodies show up here depends entirely on `track_bodies`
        passed at construction, so the same method works unchanged whether
        the scene has a block, a beaker, several objects, or nothing extra
        at all. Scene-specific task-completion logic (e.g. "is the block on
        the target") belongs in a Task object that consumes this
        observation, not here.
        """
        obs = {
            "time": self.data.time,
            "joint_angles": self.data.qpos.copy(),
            "joint_velocities": self.data.qvel.copy(),
            # actual actuator force (N m for rotary joints, N for slides and the pedestal lift), as
            # the servo applied it; "ctrl" is what was commanded (target angles/heights for position
            # actuators, wheel torque commands for the motors)
            "joint_torques": self.data.actuator_force.copy(),
            "ctrl": self.data.ctrl.copy(),
        }
        for name in self.track_bodies:
            state = self.get_body_state(name)
            obs[f"{name}_position"] = state["position"]
            obs[f"{name}_velocity"] = state["velocity"]
        return obs