"""Generic MuJoCo robot simulator — single environment controller for any scene.

Code generated by Claude
"""

from pathlib import Path
import mujoco
from src import robot_specs


class RobotSimulator:
    """Generic simulation controller for the Tracer + OpenArm robot in any scene.

    Works with whatever scene XML you point it at (single_block.xml,
    chemistry_lab.xml, a bare robot, etc.) — nothing here is tied to a
    specific scene's object names. If a scene has objects you want to track
    each step (a block, a beaker, a workbench), name them via `track_bodies`
    instead of adding new methods or subclasses per scene.
    """

    def __init__(self, model_path: str = None, track_bodies: list[str] = None):
        """
        Initialize simulator.

        Args:
            model_path: Path to MJCF model/scene file. A scene file should
                <include> the robot model at the top level (see
                learnings-and-workflow notes on <include> placement).
                Defaults to the bare combined robot with no scene objects.
            track_bodies: Names of bodies in the scene whose position/velocity
                should be included in get_observation() (e.g. ["block"], or
                ["beaker_1", "beaker_2"] for a chemistry scene). Optional —
                you can always query any body on demand with get_body_state(),
                whether or not it's in this list.
        """
        if model_path is None:
            project_root = Path(__file__).parent.parent
            model_path = project_root / "deps/OpenArm-Combined/combined_robot.xml"

        model_path = Path(model_path)
        if not model_path.exists():
            raise FileNotFoundError(f"Model not found: {model_path}")

        self.model = mujoco.MjModel.from_xml_path(str(model_path))
        self.data = mujoco.MjData(self.model)
        self.model_path = model_path
        self.track_bodies = track_bodies or []

        print(f"✓ Loaded model: {model_path.name}")
        print(f"  Bodies: {self.model.nbody}")
        print(f"  Joints: {self.model.njnt}")
        print(f"  Actuators: {self.model.nu}")

    def step(self):
        """Step physics simulation forward."""
        mujoco.mj_step(self.model, self.data)

    def reset(self):
        """Reset environment to initial state."""
        mujoco.mj_resetData(self.model, self.data)

    def close(self):
        """Clean up."""
        pass

    def get_time(self) -> float:
        """Get current simulation time."""
        return self.data.time

    def get_body_state(self, body_name: str) -> dict:
        """Get position and velocity for any named body in the loaded scene.

        This is the generic replacement for the old scene-specific
        get_block_position() / get_block_velocity(). It works for any body
        present in whichever model_path was loaded — a block, a beaker, a
        workbench, anything. If the name isn't in the current scene, MuJoCo
        raises a KeyError, which is the correct failure mode (better than
        silently returning garbage for a body that doesn't exist here).
        """
        body = self.data.body(body_name)
        return {
            "position": body.xpos.copy(),
            "velocity": body.cvel.copy(),
        }

    def get_observation(self) -> dict:
        """Get full observation: robot state + state of any tracked bodies.

        Which extra bodies show up here depends entirely on `track_bodies`
        passed at construction, so the same method works unchanged whether
        the scene has a block, a beaker, several objects, or nothing extra
        at all. Scene-specific task-completion logic (e.g. "is the block on
        the target") belongs in a Task object that consumes this
        observation, not here.
        """
        obs = {
            "time": self.data.time,
            "joint_angles": self.data.qpos.copy(),
            "joint_velocities": self.data.qvel.copy(),
            "joint_torques": self.data.ctrl.copy(),
        }
        for name in self.track_bodies:
            state = self.get_body_state(name)
            obs[f"{name}_position"] = state["position"]
            obs[f"{name}_velocity"] = state["velocity"]
        return obs