# Code generated by Claude
"""
Scripted staging source: brings the robot from the spawn state to HANDOFF for the beaker-on-hotplate task. A placeholder for a
future planner: simple, and every task-specific number comes from src/task_config.py (TASK_CFG poses, STAGING_CFG speeds, ramps and
tolerances), none from this file.

    source = make_staging_source(model, data, task_cfg=TASK_CFG, cfg=STAGING_CFG, points_fn=framing_points)
    source["step"](obs) -> commands          (the loop calls it every tick)
    source["state"]     phase, done, error, phases {name: {start, end}}, arrival, final_turn_deg, framing_report, ...

Phases, in order (one subsystem moves at a time; the neck is exempt and stays at its look-ahead aim while driving):
  DRIVE     turn in place toward the staging xy, drive straight, turn to the staging yaw, with the ground-truth base pose. Speeds
            ramp gently (STAGING_CFG). The straight leg follows the line from where it started to the goal (heading plus cross-track
            correction, so it stays accurate right up to the goal; steering at the bearing to the goal is ill-conditioned near it). Arrival = within drive_pos_tol and drive_yaw_tol with the base at rest for drive_settle_s;
            the tolerances are never loosened. If the pose is not held after drive_max_reapproach corrective re-approaches (or on
            the timeout) state["error"] is set and the source stops commanding; the runner ends the episode as STAGING_FAILED.
            On arrival the base gets a zero Twist.
  PEDESTAL  the pedestal command ramps to task_cfg["pedestal_q"].
  ARMS      the task arm moves (minimum jerk, arms_move_s) rest -> ready_via_q -> ready_q, the gripper opening on the way.
  NECK      frame_points() on points_fn(model, data) (beaker, hotplate, the gripper at its ready pose), the result is commanded, then held.
  DONE      state["done"] = True. The source stops commanding.
Phase end = the target reached, with the moving joints below the settle velocity for the settle time (so each phase also waits
for its own motion to die out). state["final_turn_deg"] is the in-place turn done at the staging pose (the staging search's swept
clearance assumed a small one); state["planned_final_turn_deg"] is what the straight approach from the spawn implies.
"""

import math

import numpy as np

from src import robot_specs
from src.neck import neck_ids
from src.neck_framing import frame_points
from src.task_beaker_hotplate import arm_ids, framing_points, wrap
from src.task_config import STAGING_CFG, TASK_CFG


def _slew(cur, target, up, down, dt):
    """Move cur toward target by at most up*dt when speeding up (|target| > |cur|, same sign), else down*dt."""
    speeding = abs(target) > abs(cur) and (cur == 0 or target * cur > 0)
    lim = (up if speeding else down) * dt
    return cur + max(-lim, min(lim, target - cur))


def _min_jerk(u):
    u = min(max(u, 0.0), 1.0)
    return 10 * u ** 3 - 15 * u ** 4 + 6 * u ** 5


def make_staging_source(model, data, task_cfg=TASK_CFG, cfg=STAGING_CFG, points_fn=framing_points):
    arm = task_cfg["arm"]
    arm_idx = arm_ids(model, arm)
    ped_vadr = int(model.joint(robot_specs.PEDESTAL_SPECS["joints"][0]).dofadr[0])
    neck = neck_ids(model, robot_specs.NECK_SPECS)
    gx, gy = task_cfg["staging_xy"]
    gyaw = task_cfg["staging_yaw"]
    spawn = task_cfg["spawn_xy"]
    planned_heading = math.atan2(gy - spawn[1], gx - spawn[0])
    state = {"phase": "DRIVE", "done": False, "error": None, "phases": {}, "arrival": None, "final_turn_deg": None,
             "planned_final_turn_deg": math.degrees(wrap(gyaw - planned_heading)), "first_turn_deg": None, "reapproaches": 0,
             "framing_report": None}
    P = {"entered": False, "leg": "TURN1", "twist": (0.0, 0.0), "ok_since": None, "still_since": None, "neck_sent": False,
         "u": 0.0, "last_arm": None, "path": None, "neck_targets": None, "first_cmd_done": False}

    def enter(name, t):
        if state["phase"] in state["phases"]:
            state["phases"][state["phase"]]["end"] = t
        state["phase"] = name
        state["phases"][name] = {"start": t, "end": None}
        P.update(still_since=None, ok_since=None)

    def still_for(t, ok, dwell):
        """True once `ok` has held for `dwell` seconds."""
        if not ok:
            P["still_since"] = None
            return False
        if P["still_since"] is None:
            P["still_since"] = t
        return t - P["still_since"] >= dwell

    def fail(t, msg):
        state["error"] = msg
        state["phases"][state["phase"]]["end"] = t

    # ------------------------------------------------------------------ DRIVE
    def drive(obs, t, dt):
        x, y, yaw = obs["base_pose"]
        dist = math.hypot(gx - x, gy - y)
        bearing = math.atan2(gy - y, gx - x)
        leg = P["leg"]
        lin_t = ang_t = 0.0

        def turn_rate(err, tol_leg):
            w = math.sqrt(2 * cfg["drive_ang_decel"] * max(abs(err) - 0.3 * tol_leg, 0.0))
            return math.copysign(max(min(w, cfg["drive_max_ang_vel"]), cfg["drive_creep_ang"]), err)

        if leg == "TURN1":
            if dist < cfg["drive_pos_tol"]:
                leg = "TURN2"
            else:
                err = wrap(bearing - yaw)
                if state["first_turn_deg"] is None:
                    state["first_turn_deg"] = math.degrees(err)
                if abs(err) < cfg["drive_turn_first_tol"]:
                    leg = "DRIVE"
                    P["line"] = (x, y, bearing)                  # the straight leg follows this line to the goal
                else:
                    ang_t = turn_rate(err, cfg["drive_turn_first_tol"])
        if leg == "DRIVE":
            sx, sy, lh = P["line"]
            ux, uy = math.cos(lh), math.sin(lh)
            along_rem = (gx - x) * ux + (gy - y) * uy            # distance left along the line
            lateral = -(x - sx) * uy + (y - sy) * ux             # left of the line is positive
            if dist < cfg["drive_pos_tol"]:
                leg = "TURN2"
            elif along_rem < 0.0:                                # went past the goal without arriving: stop, SETTLE will re-approach
                leg = "TURN2"
            else:
                v = math.sqrt(2 * cfg["drive_lin_decel"] * max(dist - 0.3 * cfg["drive_pos_tol"], 0.0))
                lin_t = max(min(v, cfg["drive_max_lin_vel"]), cfg["drive_creep_lin"])
                # heading plus cross-track correction (Stanley): aim at the line, a little further along it the further off it we are
                want = lh - math.atan2(cfg["drive_cross_track_gain"] * lateral, max(P["twist"][0], 0.1))
                err = wrap(want - yaw)
                ang_t = max(-cfg["drive_steer_max"], min(cfg["drive_steer_max"], cfg["drive_steer_gain"] * err))
                if abs(wrap(lh - yaw)) > math.radians(20) and dist > 0.3:     # knocked far off course: turn again
                    leg = "TURN1"
                    lin_t = ang_t = 0.0
        if leg == "TURN2":
            err = wrap(gyaw - yaw)
            if state["final_turn_deg"] is None:
                state["final_turn_deg"] = math.degrees(err)      # the in-place turn at the staging pose
            if abs(err) < cfg["drive_yaw_tol"]:
                leg = "SETTLE"
            else:
                ang_t = turn_rate(err, cfg["drive_yaw_tol"])
        if leg == "SETTLE":
            lin, ang = P["twist"]
            pos_err, yaw_err = dist, abs(wrap(gyaw - yaw))
            at_rest = abs(lin) < 1e-9 and abs(ang) < 1e-9
            in_tol = pos_err < cfg["drive_pos_tol"] and yaw_err < cfg["drive_yaw_tol"]
            if not in_tol and at_rest:                           # drifted out after stopping: re-approach, or give up
                state["reapproaches"] += 1
                P["ok_since"] = None
                if state["reapproaches"] > cfg["drive_max_reapproach"]:
                    state["arrival"] = {"pos_err": pos_err, "yaw_err_deg": math.degrees(yaw_err), "ok": False}
                    fail(t, f"DRIVE: the base is not within {cfg['drive_pos_tol'] * 100:.0f} cm / {math.degrees(cfg['drive_yaw_tol']):.0f} deg of the "
                            f"staging pose after {cfg['drive_max_reapproach']} corrective re-approaches (now {pos_err * 1000:.1f} mm, "
                            f"{math.degrees(yaw_err):.2f} deg)")
                    return []
                state["final_turn_deg"] = None
                leg = "TURN1" if pos_err >= cfg["drive_pos_tol"] else "TURN2"
            elif in_tol and at_rest:
                if P["ok_since"] is None:
                    P["ok_since"] = t
                if t - P["ok_since"] >= cfg["drive_settle_s"]:
                    state["arrival"] = {"pos_err": pos_err, "yaw_err_deg": math.degrees(yaw_err), "ok": True}
                    P["leg"] = leg
                    enter("PEDESTAL", t)
                    return [{"mode": "base", "twist": (0.0, 0.0)}]
        P["leg"] = leg
        lin, ang = P["twist"]
        lin = _slew(lin, lin_t, cfg["drive_lin_accel"], cfg["drive_lin_decel"], dt)
        ang = _slew(ang, ang_t, cfg["drive_ang_accel"], cfg["drive_ang_decel"], dt)
        P["twist"] = (lin, ang)
        return [{"mode": "base", "twist": (lin, ang)}]

    # ------------------------------------------------------------------ PEDESTAL
    def pedestal(obs, t, dt):
        target = task_cfg["pedestal_q"]
        applied = obs["applied"]["pedestal"]
        if abs(obs["pedestal_height"] - target) < cfg["pedestal_tol"] and abs(applied - target) < 1e-9 and \
                still_for(t, abs(obs["joint_velocities"][ped_vadr]) < cfg["pedestal_settle_vel"], cfg["pedestal_settle_s"]):
            enter("ARMS", t)
            return []
        if abs(applied - target) < 1e-9:
            return []
        step = cfg["pedestal_speed"] * dt
        return [{"mode": "pedestal", "height": applied + max(-step, min(step, target - applied))}]

    # ------------------------------------------------------------------ ARMS
    def arms(obs, t, dt):
        applied = np.array(obs["applied"]["arm_targets"][arm])
        ready = np.array(task_cfg["ready_q"], float)
        if P["path"] is None:
            via = task_cfg["ready_via_q"]
            pts = np.array([applied] + ([np.array(via, float)] if via is not None else []) + [ready])
            seg = np.linalg.norm(np.diff(pts, axis=0), axis=1)
            P["path"] = (pts, np.r_[0.0, np.cumsum(seg) / seg.sum()])
        q_now = np.array([obs["joint_angles"][a] for a in arm_idx["qadr"]])
        qd = max(abs(obs["joint_velocities"][v]) for v in arm_idx["vadr"])
        if P["u"] >= 1.0 and np.abs(q_now - ready).max() < cfg["arms_tol"] and \
                still_for(t, qd < cfg["arms_settle_vel"], cfg["arms_settle_s"]):
            enter("NECK", t)
            return []
        if P["last_arm"] is None or np.allclose(applied, P["last_arm"], atol=1e-12):      # advance only when the last command was applied
            P["u"] = min(1.0, P["u"] + dt / cfg["arms_move_s"])
        s = _min_jerk(P["u"])
        pts, frac = P["path"]
        i = min(int(np.searchsorted(frac, s, side="right")) - 1, len(pts) - 2)
        q = pts[i] + (s - frac[i]) / (frac[i + 1] - frac[i]) * (pts[i + 1] - pts[i])
        P["last_arm"] = q
        return [{"mode": "arms", "arm_targets": {arm: [float(v) for v in q]}, "gripper": {arm: float(cfg["finger_open"] * s)}}]

    # ------------------------------------------------------------------ NECK
    def neck_phase(obs, t, dt):
        if not P["neck_sent"]:
            targets, report = frame_points(model, data, points_fn(model, data, task_cfg))
            state["framing_report"] = report
            P["neck_targets"], P["neck_sent"] = targets, True
            return [{"mode": "neck", "neck_targets": targets}]
        q = np.array([obs["joint_angles"][a] for a in neck["qadr"]])
        goal = np.array([P["neck_targets"][n] for n in neck["names"]])
        qd = max(abs(obs["joint_velocities"][v]) for v in neck["vadr"])
        if np.abs(q - goal).max() < cfg["neck_tol"] and still_for(t, qd < cfg["neck_settle_vel"], cfg["neck_settle_s"]):
            enter("DONE", t)
            state["done"] = True
        return []

    phases = {"DRIVE": (drive, "drive_timeout"), "PEDESTAL": (pedestal, "pedestal_timeout"), "ARMS": (arms, "arms_timeout"),
              "NECK": (neck_phase, "neck_timeout")}

    def step(obs):
        if state["done"] or state["error"]:
            return []
        t = obs["time"]
        dt = obs["timestep"] * obs["steps_per_frame"]
        if not P["entered"]:
            P["entered"] = True
            state["phases"]["DRIVE"] = {"start": t, "end": None}
            lead = [{"mode": "neck", "neck_targets": dict(zip(robot_specs.NECK_SPECS["active_joints"], robot_specs.NECK_SPECS["drive_pose"]))}] \
                if neck is not None else []                       # the neck looks ahead while driving (it already does; made explicit)
        else:
            lead = []
        phase = state["phase"]
        fn, timeout_key = phases[phase]
        if t - state["phases"][phase]["start"] > cfg[timeout_key]:
            fail(t, f"{phase} timed out after {cfg[timeout_key]:.0f} s")
            return []
        return lead + fn(obs, t, dt)

    return {"name": "staging", "step": step, "state": state}
