# Code generated by Claude
"""
Flat config dicts for the beaker-on-hotplate task (models/scenes/chemistry_lab_beaker_hotplate.xml).

Every pose and threshold of the task lives here so a later run can randomize it by copying a dict and
changing entries (task_beaker_hotplate.apply_task_poses() writes the object poses into the model).
Plain dicts of numbers, strings and tuples; no nesting, no classes.

Planned sequence (NOT built yet): DRIVE to the staging pose -> PEDESTAL to pedestal_q -> ARMS to the ready pose
-> HANDOFF (the VLA takes over the arm from here). The base and the arms never move at the same time.

World frame: the bench is centred on the origin (top z = 0.96, x +-2.2, y +-0.8). The robot faces its own
+x. The staging pose is on the +y side of the bench, facing -y (yaw = -90 deg).
"""

import math

# ----------------------------------------------------------------------------------------------------------
# Scene, objects and poses
# ----------------------------------------------------------------------------------------------------------
TASK_CFG = {
    "scene": "models/scenes/chemistry_lab_beaker_hotplate.xml",

    # Objects (xy in the world; z comes from the bench top). These equal the defaults in
    # models/objects/*.xml; the values here are the ones applied at load. 20 cm centre to centre; the hotplate is on
    # the robot's right of the beaker (the left arm and shoulder hide the robot's left side from the eagle camera).
    # y = 0.66 puts the 18 cm deep hotplate 5 cm from the bench's front edge (the layout search's rule).
    "beaker_xy": (1.00, 0.66),
    "hotplate_xy": (0.80, 0.66),
    "beaker_settle_clearance": 0.002,      # m, the beaker is dropped from this height above the bench top
    "warmup_s": 1.0,                       # start-up as combined_controller.py: arms held at zero while the robot settles,
    "resettle_s": 0.4,                     # then the drooped pose is captured as the resting pose and held

    # Robot spawn on open floor, 2.6 m from the bench edge and facing +y, away from the bench, so DRIVE needs a real
    # turn (about 180 deg) and a real drive (about 2.2 m). It is roughly north of the staging area on purpose: the
    # heading from spawn to staging is -89 deg, so the final in-place turn is only ~1 deg. With a spawn far to the
    # side the final turn is large and sweeps a footprint corner (0.46 m from base_link's origin) into the bench unless
    # the standoff is large, which puts the objects out of reach. Re-run the layout search after moving the spawn: it
    # checks the swept footprint for the configured spawn.
    "spawn_xy": (0.70, 3.40),
    "spawn_yaw": math.radians(90.0),

    # --- from experiments/beaker_hotplate_layout_search.py (results in data/beaker_hotplate_layout/); re-run it if the
    # --- objects, spawn, pedestal or the grasp orientation constraint change ---
    "staging_xy": (0.7500, 1.2213),        # base_link origin, m; 8 cm from the bench edge (base front to bench top edge)
    "staging_yaw": math.radians(-90.0),    # facing the bench
    "pedestal_q": -0.2,                    # pedestal_lift command, m of stage travel (0 = raised, negative = lowered)
    "arm": "left",                         # the arm that gets the ready pose
    "ready_q": (-1.00748, -0.70464, 0.47191, 1.24247, -0.77442, -0.08043, 0.61180),   # that arm's 7 joints, rad (margin 40 deg)
    "ready_tcp": (1.0000, 0.7100, 1.1750), # world xyz of the TCP at ready_q when the base is at the staging pose
    "ready_via_q": (-0.64235, -1.42671, -0.28301, 0.51899, 0.02738, 0.07867, 0.21018),  # waypoint hanging pose -> via -> ready (joint margin 29.7 deg; 16 cm from the bench along the staging path, re-planned with a 12 cm path margin because the arm's servo lag plus base drift used up the earlier 6.5 cm); a straight move hits the bench
    # Left-arm joint solutions of the other task poses (from the layout search; the beaker is held upright for the last two)
    "grasp_q": (-1.07325, -0.36123, 0.79668, 0.53576, -1.02172, 0.19696, 0.19506),        # TCP at beaker mid-height, fingers open (margin 30.7 deg)
    "above_plate_q": (-1.36316, -0.26016, 1.13214, 0.74114, -0.94935, -0.13076, 0.37412), # TCP 10 cm above hotplate_top, beaker held (24.9 deg)
    "setdown_q": (-1.25683, -0.23374, 1.16252, 0.69941, -1.15110, -0.01193, 0.24228),      # beaker bottom 2 mm above the hotplate top, beaker held (23.4 deg)
}

# ----------------------------------------------------------------------------------------------------------
# Staging pose search (offline), experiments/beaker_hotplate_staging_search.py
# ----------------------------------------------------------------------------------------------------------
SEARCH_CFG = {
    "n_samples": 6_000_000,                # random joint-space samples per arm (uniform within joint limits)
    "seed": 0,
    # Which gripper poses count as "reachable". The grasp is a side pinch at beaker mid-height, so the
    # approach axis (hand +z) must point forward and down, and the fingers must open sideways, not up/down.
    "approach_down_deg": 45.0,             # nominal approach axis: this far below horizontal, towards the bench
    "approach_cone_deg": 45.0,             # allowed angle between the approach axis and the nominal one
    "finger_axis_max_z": 0.5,              # |z of the finger-opening axis (hand y)| <= this (30 deg off horizontal)
    # Candidate grid
    "standoffs": (0.05, 0.08, 0.11, 0.14, 0.18, 0.22),   # m, base front edge to bench edge at the final yaw
    "laterals": tuple(round(0.05 * i, 2) for i in range(-6, 7)),   # m along the bench from the objects' midpoint
    "pedestal_qs": (0.0, -0.04, -0.08, -0.12, -0.16, -0.20, -0.228),
    "pedestal_stop_margin": 0.01,          # m, candidates this close to the lowest command (the torso-contact stop) are skipped
    "min_clearance": 0.05,                 # m, base footprint to bench at the staging pose (the requirement)
    "required_clearance": 0.08,            # m, wanted: footprint to bench at the staging pose (the hard minimum is min_clearance)
    "required_turn_clearance": 0.05,       # m, wanted: swept footprint of the final turn (hard minimum min_turn_clearance)
    "min_turn_clearance": 0.02,            # m, the footprint swept by the final in-place turn (the drive stops short, on the far side)
    "gap_resolution": 0.03,                # m, sampled gaps within this of the best go on to IK (the sample density limits them; IK then gives the exact gap)
    "gap_flag": 0.03,                      # m, report anything above this
    "reach_radius": 0.03,                  # m, neighbour count radius, the tie-break for how deep inside the workspace a target is
    # Ready pose: TCP this far above the beaker top and this far back towards the robot
    "ready_clear_above_top": 0.115,        # m; the fingertips are 15 mm past the TCP, so they end up ~10 cm clear
    "ready_back_off": 0.05,                # m, horizontal, towards the robot ("in front of" the beaker)
    "grasp_height_frac": 0.5,              # grasp point = beaker mid-height
    "place_clear_above_plate": 0.10,       # m, second reach target above hotplate_top
    "finger_open": 0.044,                  # m, fully open (both fingers)
    "path_margin": 0.03,                   # m, the arm path stays this far from the bench, objects and furniture
}

# ----------------------------------------------------------------------------------------------------------
# Joint layout + staging search with slack at every task pose (experiments/beaker_hotplate_layout_search.py)
# ----------------------------------------------------------------------------------------------------------
LAYOUT_CFG = {
    "arm": "left",
    "n_samples": 20_000_000,               # random joint samples of that arm (the usable ones are kept, with their joint margin)
    "seed": 1,
    # Object pair: slid together along the bench (hotplate to the robot's right of the beaker, i.e. smaller world x)
    "spacings": (0.20, 0.25, 0.30),        # m, beaker to hotplate centre
    "bench_edge_margin": 0.05,             # m, objects at least this far from every bench edge; fixes the pair's y
    "pair_xs": (0.6, 0.8, 1.0, 1.2, 1.4),  # beaker x positions tried (reach does not depend on x; furniture and the turn do)
    # Staging pose, relative to the pair: standoff (base front to bench edge), lateral offset from the pair midpoint
    # along the bench, yaw offset from facing the bench, pedestal command
    "standoffs": (0.08, 0.10, 0.12, 0.14, 0.16),
    "laterals": tuple(round(0.05 * i, 2) for i in range(-8, 3)),
    "yaw_offsets_deg": (-20.0, -10.0, 0.0, 10.0, 20.0),
    "pedestal_qs": (0.0, -0.04, -0.08, -0.12, -0.16, -0.20),
    # Requirements
    "required_clearance": 0.08,            # m, base footprint to bench at the staging pose
    "required_turn_clearance": 0.05,       # m, footprint swept by the final in-place turn
    "min_furniture_clearance": 0.03,       # m
    "required_margin_deg": 10.0,           # every arm joint this far from its limit at every task pose
    "clear_margin": 0.003,                 # m, arm geoms (except the fingers on the beaker) stay this far from everything else
    "path_margin": 0.03,                   # m, the rest -> via -> ready path stays this far from everything
    "holding_finger_q": 0.0368,            # m per finger: gap 70 mm = the beaker diameter (gap = 2 q - 3.6 mm)
    "setdown_clearance": 0.002,            # m, the held beaker's bottom starts this far above the hotplate top
    # Robustness: base perturbed by +-dx, +-dy, +-dyaw (all 8 corners)
    "robust_xy": 0.02,
    "robust_yaw_deg": 2.0,
    # Search effort
    "reach_radius": 0.015,                 # m, samples within this of a target give the screening margin
    "n_screen_keep": 120,                  # candidates (by screening margin) that get the exact IK
    "n_seeds": 100,
}

# ----------------------------------------------------------------------------------------------------------
# Scripted staging (src/staging_source.py): spawn -> DRIVE -> PEDESTAL -> ARMS -> NECK -> DONE (= HANDOFF)
# ----------------------------------------------------------------------------------------------------------
STAGING_CFG = {
    # DRIVE: turn in place toward the staging xy, drive straight, turn to the staging yaw (ground-truth base pose).
    # Gentle starts: the base's yaw drifts when it starts to move (the arms swing), so the acceleration is slow.
    "drive_max_lin_vel": 0.3,              # m/s
    "drive_lin_accel": 0.1,                # m/s^2
    "drive_lin_decel": 0.15,               # m/s^2
    "drive_max_ang_vel": 0.4,              # rad/s
    "drive_ang_accel": 0.2,                # rad/s^2
    "drive_ang_decel": 0.2,                # rad/s^2
    "drive_pos_tol": 0.01,                 # m, arrival tolerance (never loosened: a miss is reported)
    "drive_yaw_tol": math.radians(1.0),    # rad
    "drive_creep_lin": 0.02,               # m/s, lowest speed while still outside the tolerance (so the base converges)
    "drive_creep_ang": 0.03,               # rad/s
    "drive_turn_first_tol": math.radians(2.0),   # the turn toward the goal ends within this; the drive steers the rest
    "drive_steer_gain": 1.0,               # 1/s, heading error -> yaw rate while driving
    "drive_cross_track_gain": 1.5,         # 1/s: heading aimed at the line, further along it the further off the line (Stanley)
    "drive_steer_max": 0.1,                # rad/s
    "drive_settle_s": 0.3,                 # the arrival must hold this long with the base at rest
    "drive_max_reapproach": 3,             # corrective re-approaches before DRIVE gives up (-> the episode is STAGING_FAILED)
    "drive_timeout": 120.0,                # s
    # Pose corrections after PEDESTAL and after ARMS (the pedestal and arm moves push the base off its pose): if the base is outside
    # drive_pos_tol / drive_yaw_tol it is moved back. NEW values (not from the earlier approved set):
    "correction_aim_frac": 0.5,            # the corrections go to within this fraction of the tolerance (aim for the centre, not the edge)
    "correction_timeout": 60.0,            # s per correction
    "correction_arms_max_pos": 0.02,       # m: with the arm extended, a base error above this fails the episode (STAGING_FAILED) instead of moving
    "correction_arms_max_yaw": math.radians(2.0),   # rad: same for yaw (2 deg = the layout search's verified base-perturbation range)
    "correction_arms_min_base_clearance": 0.05,     # m: base to bench, checked every tick of the extended-arm correction (it is 0.08 at the staging pose)
    "correction_arms_min_arm_clearance": 0.03,      # m: the task arm to the bench, same check
    # PEDESTAL
    "pedestal_speed": 0.05,                # m/s of command change (the lift's jog speed)
    "pedestal_tol": 0.003,                 # m
    "pedestal_settle_vel": 0.002,          # m/s
    "pedestal_settle_s": 0.3,
    "pedestal_timeout": 30.0,
    # ARMS: minimum-jerk move along rest -> ready_via_q -> ready_q (joint-space arc length), gripper opening on the way
    "arms_move_s": 10.0,                   # s; was 6: at 6 s the servos lagged the path by up to 6 deg and the fingers grazed the bench top
    "arms_tol": 0.03,                      # rad, every joint
    "arms_settle_vel": 0.02,               # rad/s
    "arms_settle_s": 0.3,
    "arms_timeout": 30.0,
    "finger_open": 0.044,                  # m
    # NECK: frame_points() on the task points, then hold
    "neck_tol": 0.01,                      # rad
    "neck_settle_vel": 0.02,               # rad/s
    "neck_settle_s": 0.3,
    "neck_timeout": 15.0,
}

# ----------------------------------------------------------------------------------------------------------
# Episode runner (src/episode_runner.py)
# ----------------------------------------------------------------------------------------------------------
EPISODE_CFG = {
    "timeout_after_handoff": 60.0,         # s of sim time under AUTO control after HANDOFF with no success -> outcome TIMEOUT (paused while the operator has control)
    "operator_timeout": 300.0,             # s of sim time under operator (teleop) control with no success -> outcome TIMEOUT (also the budget of a teleop-start episode)
    "log_hz": 10.0,                        # state / command log, written on the first tick of every 1/log_hz s of sim time
    "exclusive": True,                     # one subsystem moves at a time (the neck is exempt); off by default elsewhere
    "spawn_z": 0.22,                       # m, height the base is dropped from at spawn (it settles onto its wheels)
}

# ----------------------------------------------------------------------------------------------------------
# Success check: check_success(model, data, cfg=SUCCESS_CFG)
# ----------------------------------------------------------------------------------------------------------
SUCCESS_CFG = {
    "beaker_site": "beaker_base",
    "hotplate_site": "hotplate_top",
    "hotplate_plate_geom": "task_hotplate_top_plate",   # its half extents are the top footprint
    "beaker_body": "task_beaker",
    "footprint_margin": 0.01,              # m, beaker_base must be inside the top footprint minus this
    "height_tol": 0.005,                   # m, |beaker_base z - hotplate_top z|
    "upright_max_deg": 15.0,               # beaker local z against world z
    "speed_max": 0.01,                     # m/s
}
