# Code generated by Claude
"""
Flat config dicts for the beaker-on-hotplate task (models/scenes/chemistry_lab_beaker_hotplate.xml).

Every pose and threshold of the task lives here so a later run can randomize it by copying a dict and
changing entries (task_beaker_hotplate.apply_task_poses() writes the object poses into the model).
Plain dicts of numbers, strings and tuples; no nesting, no classes.

Planned sequence (NOT built yet): DRIVE to the staging pose -> PEDESTAL to pedestal_q -> ARMS to the ready pose
-> HANDOFF (the VLA takes over the arm from here). The base and the arms never move at the same time.

World frame: the bench is centred on the origin (top z = 0.96, x +-2.2, y +-0.8). The robot faces its own
+x. The staging pose is on the +y side of the bench, facing -y (yaw = -90 deg).
"""

import math

# ----------------------------------------------------------------------------------------------------------
# Scene, objects and poses
# ----------------------------------------------------------------------------------------------------------
TASK_CFG = {
    "scene": "models/scenes/chemistry_lab_beaker_hotplate.xml",

    # Objects (xy in the world; z comes from the bench top). These equal the defaults in
    # models/objects/*.xml; the values here are the ones applied at load. 20 cm centre to centre; the hotplate is on
    # the robot's right of the beaker (the left arm and shoulder hide the robot's left side from the eagle camera).
    "beaker_xy": (1.00, 0.68),
    "hotplate_xy": (0.80, 0.68),
    "beaker_settle_clearance": 0.002,      # m, the beaker is dropped from this height above the bench top
    "warmup_s": 1.0,                       # start-up as combined_controller.py: arms held at zero while the robot settles,
    "resettle_s": 0.4,                     # then the drooped pose is captured as the resting pose and held

    # Robot spawn on open floor, 2.6 m from the bench edge and facing +y, away from the bench, so DRIVE
    # needs a real turn (about 170 deg) and a real drive (about 2.2 m). It is roughly north of the staging
    # area on purpose: the heading from spawn to staging is -75 deg, so the final in-place turn is ~15 deg.
    # With a spawn far to the side the final turn is ~40 deg and sweeps a footprint corner (0.46 m from base_link's origin) into the bench unless
    # the standoff is 22 cm or more, which puts the objects out of reach. Re-run the staging search after
    # moving the spawn: it checks the swept footprint for the configured spawn.
    "spawn_xy": (0.70, 3.40),
    "spawn_yaw": math.radians(90.0),

    # --- from experiments/beaker_hotplate_staging_search.py (results in data/beaker_hotplate_staging/); re-run it if
    # --- the objects, spawn, pedestal or cameras change ---
    "staging_xy": (0.8750, 1.2213),        # base_link origin, m; 8 cm from the bench edge (base front to bench top edge)
    "staging_yaw": math.radians(-90.0),    # facing the bench
    "pedestal_q": -0.2,                    # pedestal_lift command, m of stage travel (0 = raised, negative = lowered)
    "arm": "left",                         # the arm that gets the ready pose
    "ready_q": (-1.42142, -0.45600, 0.86935, 1.22879, -0.95571, 0.44376, 1.20655),   # that arm's 7 joints, rad
    "ready_tcp": (1.0000, 0.7300, 1.1750), # world xyz of the TCP at ready_q when the base is at the staging pose
    "ready_via_q": (-0.86967, -0.83671, -0.11607, 0.66404, -0.33348, 0.77695, 0.82962),  # one waypoint between the hanging pose and ready_q (None = straight move); a straight move hits the bench
}

# ----------------------------------------------------------------------------------------------------------
# Staging pose search (offline), experiments/beaker_hotplate_staging_search.py
# ----------------------------------------------------------------------------------------------------------
SEARCH_CFG = {
    "n_samples": 6_000_000,                # random joint-space samples per arm (uniform within joint limits)
    "seed": 0,
    # Which gripper poses count as "reachable". The grasp is a side pinch at beaker mid-height, so the
    # approach axis (hand +z) must point forward and down, and the fingers must open sideways, not up/down.
    "approach_down_deg": 45.0,             # nominal approach axis: this far below horizontal, towards the bench
    "approach_cone_deg": 45.0,             # allowed angle between the approach axis and the nominal one
    "finger_axis_max_z": 0.5,              # |z of the finger-opening axis (hand y)| <= this (30 deg off horizontal)
    # Candidate grid
    "standoffs": (0.05, 0.08, 0.11, 0.14, 0.18, 0.22),   # m, base front edge to bench edge at the final yaw
    "laterals": tuple(round(0.05 * i, 2) for i in range(-6, 7)),   # m along the bench from the objects' midpoint
    "pedestal_qs": (0.0, -0.04, -0.08, -0.12, -0.16, -0.20, -0.228),
    "pedestal_stop_margin": 0.01,          # m, candidates this close to the lowest command (the torso-contact stop) are skipped
    "min_clearance": 0.05,                 # m, base footprint to bench at the staging pose (the requirement)
    "required_clearance": 0.08,            # m, wanted: footprint to bench at the staging pose (the hard minimum is min_clearance)
    "required_turn_clearance": 0.05,       # m, wanted: swept footprint of the final turn (hard minimum min_turn_clearance)
    "min_turn_clearance": 0.02,            # m, the footprint swept by the final in-place turn (the drive stops short, on the far side)
    "gap_resolution": 0.03,                # m, sampled gaps within this of the best go on to IK (the sample density limits them; IK then gives the exact gap)
    "gap_flag": 0.03,                      # m, report anything above this
    "reach_radius": 0.03,                  # m, neighbour count radius, the tie-break for how deep inside the workspace a target is
    # Ready pose: TCP this far above the beaker top and this far back towards the robot
    "ready_clear_above_top": 0.115,        # m; the fingertips are 15 mm past the TCP, so they end up ~10 cm clear
    "ready_back_off": 0.05,                # m, horizontal, towards the robot ("in front of" the beaker)
    "grasp_height_frac": 0.5,              # grasp point = beaker mid-height
    "place_clear_above_plate": 0.10,       # m, second reach target above hotplate_top
    "finger_open": 0.044,                  # m, fully open (both fingers)
    "path_margin": 0.03,                   # m, the arm path stays this far from the bench, objects and furniture
}

# ----------------------------------------------------------------------------------------------------------
# Success check: check_success(model, data, cfg=SUCCESS_CFG)
# ----------------------------------------------------------------------------------------------------------
SUCCESS_CFG = {
    "beaker_site": "beaker_base",
    "hotplate_site": "hotplate_top",
    "hotplate_plate_geom": "task_hotplate_top_plate",   # its half extents are the top footprint
    "beaker_body": "task_beaker",
    "footprint_margin": 0.01,              # m, beaker_base must be inside the top footprint minus this
    "height_tol": 0.005,                   # m, |beaker_base z - hotplate_top z|
    "upright_max_deg": 15.0,               # beaker local z against world z
    "speed_max": 0.01,                     # m/s
}
