# Code generated by Claude
"""
The task policy of the beaker-on-hotplate task: ONE source that owns the whole task in the controller's "auto" mode.

    policy = make_task_policy(model, data, task_cfg=TASK_CFG, staging_cfg=STAGING_CFG, arm_stage=make_hold_stage())

Two stages, in order:
  staging     src/staging_source.py (DRIVE -> PEDESTAL -> CORRECT_PEDESTAL -> ARMS -> CORRECT_ARMS -> NECK -> DONE), unchanged. It makes its own
              drift / clearance / pose-error measurements and reports them (policy["report"]()).
  arm stage   after staging (DONE = HANDOFF) the arm stage owns the arms and grippers; the base, pedestal and neck hold. An arm stage is a
              dict {"name", "step"(obs) -> command(s) or None, "state", optionally "resume"()}. Provided here:
                make_hold_stage()                      holds (nothing is commanded). Replaces the old IdleSource.
                make_request_operator_stage(reason)    asks for operator control once, then holds (so after the operator hands control
                                                       back the policy simply continues: holding).
              and, test only, src/episode_test_sources.make_cheat_arm_stage.

The controller (src/control_loop.py) steps the policy only in "auto" mode; in "teleop" mode it is paused, and resume() continues its current stage.
Rule for every policy: on resume, every subsystem starts from where the operator left it, and the policy then moves it toward what it wants; it never
jumps to a stale target. The staging stage does this for the base (its controllers slew from the applied Twist), the arm (src/rate_limit.py from the applied
targets, arm_max_speed), the gripper (the same, gripper_max_speed, after resume()), the pedestal (its phase ramps from the applied height) and the neck
(the loop slews it). A new policy or arm stage must do the same.
policy["status"]() -> {"stage": "STAGING" | the arm stage's name, "phase": the staging phase ("DONE" once staging is complete), "handoff": bool,
"error": the staging error or None}; the loop publishes it as obs["policy"].
"""

from src.staging_source import make_staging_source
from src.task_config import STAGING_CFG, TASK_CFG


def make_hold_stage():
    return {"name": "hold", "step": lambda obs: None, "state": {}}


def make_request_operator_stage(reason="manipulation is not implemented: operator control requested"):
    state = {"requested": False}

    def step(obs):
        if not state["requested"]:
            state["requested"] = True
            return {"mode": "request_teleop", "reason": reason}
        return None

    return {"name": "request_operator", "step": step, "state": state}


def make_task_policy(model, data, task_cfg=TASK_CFG, staging_cfg=STAGING_CFG, arm_stage=None, points_fn=None):
    staging = make_staging_source(model, data, task_cfg, staging_cfg, **({"points_fn": points_fn} if points_fn else {}))
    arm = arm_stage or make_hold_stage()
    st = staging["state"]

    def status():
        done = st["done"]
        return {"stage": arm["name"] if done else "STAGING", "phase": "DONE" if done else st["phase"], "handoff": done, "error": st["error"]}

    def step(obs):
        staging["observe"](obs)
        if not st["done"]:
            return staging["step"](obs)
        if staging["restoring"]():                 # after a hand-back: put back what the operator moved (pedestal, neck) before the arm stage goes on
            cmds, finished = staging["restore_step"](obs, obs["time"], obs["timestep"] * obs["steps_per_frame"])
            if not finished:
                return cmds
        return arm["step"](obs)       # the first call is the tick after staging set DONE (the handoff tick)

    def resume():
        staging["resume"]()
        if st["done"] and "resume" in arm:
            arm["resume"]()

    return {"name": "policy", "step": step, "state": {"staging": st, "arm": arm["state"]}, "status": status, "resume": resume,
            "report": staging["report"], "staging": staging, "arm_stage": arm}
