# Code generated by Claude
"""
Beaker-on-hotplate task: scene loading, start-up settle and the success check.

Plain functions and flat dicts (src/task_config.py), no classes. The drive -> pedestal -> arms sequence is NOT
here (deliberately not built yet; the control loop is being refactored first).

Reused from the repo: src.simulator.RobotSimulator (scene load, arm / finger position actuators, cameras, the
placeholder pedestal lift) and the start-up of experiments/combined_controller.py / pedestal_lift_test.py (warm-up
with the arms held at zero, capture of the drooped pose as the resting pose, short re-settle with it held).
"""

import math
from pathlib import Path

import mujoco
import numpy as np

from src import robot_specs
from src.neck import neck_ids, set_neck_pose
from src.simulator import RobotSimulator
from src.task_config import TASK_CFG, SUCCESS_CFG

PROJECT_ROOT = Path(__file__).resolve().parent.parent


# ----------------------------------------------------------------------------------------------------------
# Small helpers
# ----------------------------------------------------------------------------------------------------------
def wrap(a):
    """Angle wrapped to (-pi, pi]."""
    return math.atan2(math.sin(a), math.cos(a))


def yaw_to_quat(yaw):
    return np.array([math.cos(yaw / 2), 0.0, 0.0, math.sin(yaw / 2)])


def bench_top_z(model):
    g = model.geom("bench_top")
    return float(model.geom_pos[g.id][2] + model.geom_size[g.id][2])


def arm_ids(model, side):
    """Actuator ids, joint qpos addresses and joint ids of one arm's 7 joints, and its 2 finger actuators."""
    act = [model.actuator(f"{side}_joint{i}_ctrl").id for i in range(1, 8)]
    jnt = [int(model.actuator_trnid[a, 0]) for a in act]
    qadr = [int(model.jnt_qposadr[j]) for j in jnt]
    vadr = [int(model.jnt_dofadr[j]) for j in jnt]
    fingers = [model.actuator(f"{side}_finger{k}_ctrl").id for k in (1, 2)]
    return {"act": act, "jnt": jnt, "qadr": qadr, "vadr": vadr, "fingers": fingers}


# ----------------------------------------------------------------------------------------------------------
# Loading
# ----------------------------------------------------------------------------------------------------------
def apply_task_poses(model, data, cfg=TASK_CFG):
    """Write the object poses from the config into the model / data (no stepping).

    The hotplate is a static body, so moving it is a body_pos edit; the beaker is a free joint, so qpos.
    """
    top = bench_top_z(model)
    hp = model.body("task_hotplate")
    model.body_pos[hp.id] = [cfg["hotplate_xy"][0], cfg["hotplate_xy"][1], top]
    jq = model.joint("task_beaker_free").qposadr[0]
    data.qpos[jq:jq + 7] = [cfg["beaker_xy"][0], cfg["beaker_xy"][1], top + cfg["beaker_settle_clearance"], 1, 0, 0, 0]
    data.qvel[model.joint("task_beaker_free").dofadr[0]:][:6] = 0.0
    mujoco.mj_forward(model, data)


def load_task(cfg=TASK_CFG, cameras=True):
    """RobotSimulator on the task scene, with the pedestal lift, objects placed.

    cameras: True = robot_specs.CAMERA_SPECS, False = none, or a list of camera spec dicts."""
    cams = robot_specs.CAMERA_SPECS if cameras is True else (cameras or None)
    sim = RobotSimulator(model_path=str(PROJECT_ROOT / cfg["scene"]),
                         cameras=cams,
                         pedestal_lift=robot_specs.PEDESTAL_SPECS)
    apply_task_poses(sim.model, sim.data, cfg)
    return sim


def spawn_and_settle(sim, cfg=TASK_CFG):
    """Place the robot at the spawn pose and bring it to rest like combined_controller.py does.

    Returns a dict whose "hold" is the full ctrl vector that holds the resting pose: the drooped arm joint angles (arms hang under gravity at zero), fingers at 0, pedestal at its
    default command. The wheel motors stay at ctrl 0.
    """
    model, data = sim.model, sim.data
    data.qpos[0:3] = [cfg["spawn_xy"][0], cfg["spawn_xy"][1], 0.22]
    data.qpos[3:7] = yaw_to_quat(cfg["spawn_yaw"])
    mujoco.mj_forward(model, data)

    dof = int(model.jnt_dofadr[0])                   # the base's free joint (the first joint)
    ped = model.actuator(robot_specs.PEDESTAL_SPECS["actuator_name"]).id
    wheels = {model.actuator("left_motor").id, model.actuator("right_motor").id}
    unclaimed = [a for a in range(model.nu) if a not in wheels]
    hold = np.zeros(model.nu)
    hold[ped] = robot_specs.PEDESTAL_SPECS["target_height"]
    neck = neck_ids(model, robot_specs.NECK_SPECS)
    if neck is not None:
        hold[neck["act"]] = robot_specs.NECK_SPECS["drive_pose"]

    def run(seconds):
        for _ in range(int(round(seconds * robot_specs.PHYSICS_HZ))):
            data.ctrl[:] = hold
            data.qvel[dof + 0:dof + 2] = 0.0              # base held still: xy, roll, pitch, yaw rate; z is left to
            data.qvel[dof + 3:dof + 6] = 0.0              # physics so the robot settles onto its wheels
            mujoco.mj_step(model, data)

    run(cfg["warmup_s"])
    for a in unclaimed:                     # capture the drooped pose; kill any residual swing
        if a == ped or (neck is not None and a in neck["act"]):
            continue
        j = int(model.actuator_trnid[a, 0])
        hold[a] = data.qpos[model.jnt_qposadr[j]]
        data.qvel[model.jnt_dofadr[j]] = 0.0
    mujoco.mj_forward(model, data)
    run(cfg["resettle_s"])

    return {"hold": hold, "ped": ped, "wheels": wheels, "base_dof": dof}


# ----------------------------------------------------------------------------------------------------------
# Success check
# ----------------------------------------------------------------------------------------------------------
def check_success(model, data, cfg=SUCCESS_CFG):
    """(bool, diagnostics): is the beaker standing on the hotplate top and at rest?

    All of: (a) beaker_base xy inside the hotplate top footprint minus a margin, (b) beaker_base z within
    height_tol of hotplate_top z, (c) the beaker's z axis within upright_max_deg of world z, (d) linear speed
    below speed_max. `diagnostics` holds each sub-condition's pass flag and measured value.
    """
    base = data.site(cfg["beaker_site"]).xpos
    top = data.site(cfg["hotplate_site"])
    top_pos, top_R = top.xpos, top.xmat.reshape(3, 3)
    half = model.geom_size[model.geom(cfg["hotplate_plate_geom"]).id][:2] - cfg["footprint_margin"]
    local = top_R.T @ (base - top_pos)                       # beaker_base in the hotplate top frame
    dz = float(base[2] - top_pos[2])
    body = model.body(cfg["beaker_body"])
    z_axis = data.xmat[body.id].reshape(3, 3)[:, 2]
    tilt = math.degrees(math.acos(float(np.clip(z_axis[2], -1.0, 1.0))))
    speed = float(np.linalg.norm(data.qvel[model.joint("task_beaker_free").dofadr[0]:][:3]))
    diag = {
        "a_xy_in_footprint": {"ok": bool(np.all(np.abs(local[:2]) <= half)), "offset_xy_m": local[:2].round(4).tolist(),
                              "allowed_half_extent_m": half.round(4).tolist()},
        "b_height": {"ok": abs(dz) <= cfg["height_tol"], "dz_m": round(dz, 4), "tol_m": cfg["height_tol"]},
        "c_upright": {"ok": tilt <= cfg["upright_max_deg"], "tilt_deg": round(tilt, 1), "max_deg": cfg["upright_max_deg"]},
        "d_at_rest": {"ok": speed < cfg["speed_max"], "speed_m_s": round(speed, 4), "max_m_s": cfg["speed_max"]},
    }
    return all(v["ok"] for v in diag.values()), diag


# ----------------------------------------------------------------------------------------------------------
# What the neck camera should frame
# ----------------------------------------------------------------------------------------------------------
def framing_points(model, data, cfg=TASK_CFG):
    """World points the neck camera has to keep in view for this task: the beaker, the hotplate and the arm's gripper.

    Corners of the beaker's and the hotplate's bounding boxes (so their whole bodies fit, not just their centres) and the
    gripper's TCP, hand origin and finger tips of the arm that carries the task (cfg["arm"], at whatever pose it is in).
    Returns {} if the scene has no task."""
    if mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "task_beaker") < 0:
        return {}
    pts = {}

    def box(name, center, half):
        for i, (sx, sy, sz) in enumerate(((a, b, c) for a in (-1, 1) for b in (-1, 1) for c in (-1, 1))):
            pts[f"{name}_corner{i}"] = np.array(center) + np.array([sx, sy, sz]) * np.array(half)

    top = bench_top_z(model)
    g = model.geom("task_beaker_glass")
    r, hh = float(model.geom_size[g.id][0]), float(model.geom_size[g.id][1])
    bpos = data.body("task_beaker").xpos
    box("beaker", bpos + [0, 0, hh], [r, r, hh])
    hot = data.body("task_hotplate").xpos
    base = model.geom("task_hotplate_base")
    box("hotplate", hot + [0, 0, float(model.geom_size[base.id][2])], [float(model.geom_size[base.id][0]), float(model.geom_size[base.id][1]),
                                                                       float(model.geom_size[base.id][2])])
    side = cfg["arm"]
    hand = data.body(f"openarm_{side}_hand")
    R = hand.xmat.reshape(3, 3)
    tcp = data.body(f"openarm_{side}_hand_tcp").xpos
    pts[f"{side}_gripper_tcp"] = tcp.copy()
    pts[f"{side}_gripper_hand"] = hand.xpos.copy()
    for k, sgn in enumerate((-1, 1)):                                      # the finger tips: 1.5 cm past the TCP, +-4.5 cm across
        pts[f"{side}_gripper_tip{k}"] = tcp + R @ np.array([0.0, sgn * 0.045, 0.015])
    return pts
