# Code generated by Claude
"""
Webcam teleop command source (MediaPipe -> geo_kin SEW-Mimic), moved out of experiments/combined_controller.py.

The solver, the preview handling and the fake operator for testing are the old code. The SEW-Mimic safety filter is
where it was: geo_kin's RetargetSession (collision_avoidance=True) inside session.solve(); nothing here moves it.

    source = make_teleop_source(model, data, camera=0, preview=True, fake=False, simclock=False)
    source["start"]()         # called by the loop after the settle (builds the session and the camera / fake operator)
    source["step"](obs)       # every tick: reads a camera frame; when enabled returns an arms command (arm_targets)
    source["enable"]() / source["disable"]()   # what F2 does through the loop's router

Only arm joint targets come from this source; the grippers, pedestal and base stay on the keyboard.
"""

import math
import time

import mujoco
import numpy as np

# Per-frame cap on how fast the arm PD targets may move toward the
# solver's goal, so the first engaged frame (drooped rest pose -> tracked
# pose) ramps instead of snapping.
TELEOP_MAX_JOINT_VEL = 3.0   # rad/s
PREVIEW_WINDOW = "MediaPipe Pose Estimation"   # title set by xrt_devices


def install_preview_capture(store):
    """Route the MediaPipe preview into `store` instead of an OpenCV window.

    The camera library draws its pose-overlay frame with cv2.imshow and quits
    the whole device if its window stops being visible. Replacing both
    functions lets the viewer draw the frame itself, as one more inset next to
    the simulated cameras: no second window to place on a small VM screen
    (mutter ignores window moves), and the frame is stored in
    store["preview_frame"] (BGR) for snapshots.
    """
    import cv2
    orig_get_prop = cv2.getWindowProperty

    def imshow(name, img):
        store["preview_frame"] = img.copy()

    def get_window_property(name, prop):
        if name == PREVIEW_WINDOW:
            return 1.0  # "visible"; there is deliberately no window
        return orig_get_prop(name, prop)

    cv2.imshow = imshow
    cv2.getWindowProperty = get_window_property


class _FakeSource:
    """Scripted operator for testing without a webcam (CC_FAKE_TELEOP=1).

    In view for 4 s, out of view for 4 s, repeating. Draws a synthetic
    preview frame through cv2.imshow like the real camera thread does.
    `clock` is time.monotonic, or sim time (CC_FAKE_TELEOP_SIMCLOCK=1) for reproducible runs.
    """

    def __init__(self, clock=time.monotonic):
        self.clock = clock
        self.t0 = clock()

    def get_frame(self):
        import cv2
        ph = (self.clock() - self.t0) % 8.0
        in_view = ph < 4.0
        img = np.full((480, 640, 3), 70 if in_view else 25, np.uint8)
        cv2.circle(img, (int(100 + 440 * (ph / 8.0)), 240), 40,
                   (0, 200, 255) if in_view else (80, 80, 80), -1)
        cv2.putText(img, "FAKE OPERATOR " + ("in view" if in_view else "out of view"),
                    (30, 60), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (255, 255, 255), 2)
        cv2.imshow(PREVIEW_WINDOW, img)
        return object() if in_view else None  # any non-None = engaged

    def cleanup(self):
        pass


class _FakeSession:
    """Stand-in solver for _FakeSource: swings every arm joint gently."""

    def __init__(self, lo, hi, clock=time.monotonic):
        self.lo, self.hi = lo, hi
        self.clock = clock
        self.t0 = clock()

    def reset(self, *args):
        pass

    def solve(self, frame, engaged, q_current_right, q_current_left):
        from types import SimpleNamespace
        ph = self.clock() - self.t0
        out = {}
        for sd in ("right", "left"):
            goal = 0.4 * np.sin(ph + np.arange(7))
            out[f"q_goal_{sd}"] = np.clip(goal, self.lo[sd], self.hi[sd])
        return SimpleNamespace(**out)


def make_teleop_source(model, data, camera=0, preview=True, fake=False, simclock=False):
    ctl = {"warned": set(), "engaged": False, "on": False}    # `teleop` in the old run(); also holds "preview_frame"
    box = {}                                                  # session, source, arm tables, filled in by start()

    def start():
        import atexit
        from geo_kin_core.types import RetargetFrame
        box["RetargetFrame"] = RetargetFrame

        arm_ids = {}
        arm_qadr = {}
        arm_lo = {}
        arm_hi = {}
        for side in ("right", "left"):
            ids = [mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_ACTUATOR,
                                     f"{side}_joint{i}_ctrl") for i in range(1, 8)]
            jids = [model.actuator_trnid[a, 0] for a in ids]
            arm_ids[side] = ids
            arm_qadr[side] = [model.jnt_qposadr[j] for j in jids]
            arm_lo[side] = np.array([model.jnt_range[j, 0] for j in jids])
            arm_hi[side] = np.array([model.jnt_range[j, 1] for j in jids])
        box.update(arm_ids=arm_ids, arm_qadr=arm_qadr, arm_lo=arm_lo, arm_hi=arm_hi)

        # The arms start in MANUAL (keyboard); F2 switches them to the webcam
        # operator and back, so the base can be driven into place first.
        if fake:
            clock = (lambda: data.time) if simclock else time.monotonic
            session = _FakeSession(arm_lo, arm_hi, clock)
            source = _FakeSource(clock)
            print("Teleop: FAKE scripted operator (CC_FAKE_TELEOP=1), no webcam; "
                  "no safety filter (the fake solver has none)")
        else:
            from openarm_teleop.session import make_session
            from xrt_devices.integrations.geo_kin import MediaPipeDeviceAdapter
            # Solver first, so a licence problem can't leave a camera running.
            # geo_kin's RetargetSession defaults to collision_avoidance=True
            # (checked in its signature). Passed explicitly, as Kong's demo
            # does, and deliberately not switchable: the safety filter stays on.
            session = make_session(collision_avoidance=True)
            session.reset(data.qpos[arm_qadr["right"]].copy(),
                          data.qpos[arm_qadr["left"]].copy())
            # display=True makes the library draw the pose overlay on the
            # camera feed; install_preview_capture hands that frame to the
            # viewer instead of opening a window.
            source = MediaPipeDeviceAdapter(camera_id=camera, display=preview)
            atexit.register(source.cleanup)
        box.update(session=session, source=source)
        if preview:
            install_preview_capture(ctl)
        if not fake:
            print("Teleop safety filter (collision avoidance): ON")
        print(f"Teleop: camera {camera}, preview={'on' if preview else 'off'}. "
              f"Arms start MANUAL; press F2 for teleop, then raise both arms "
              f"to shoulder height to engage.")

    def _set(on):
        """Switch the arms between MANUAL keys and the TELEOP webcam operator (the old set_teleop)."""
        if on == ctl["on"]:
            return
        if on:
            box["session"].reset(data.qpos[box["arm_qadr"]["right"]].copy(),
                                 data.qpos[box["arm_qadr"]["left"]].copy())
            ctl["engaged"] = False
        ctl["on"] = on
        print("Arms: TELEOP (webcam operator; raise both arms to engage; "
              "grippers stay on keys)" if on else
              "Arms: MANUAL (jog keys: left arm 1-8 / Q-I, right arm A-K / Z-,)")

    def step(obs):
        # --- Teleop: arm PD targets from session.solve() ---
        tframe = box["source"].get_frame()  # also keeps the preview fresh
        if not ctl["on"]:
            return []
        arm_ids, arm_qadr, arm_lo, arm_hi = box["arm_ids"], box["arm_qadr"], box["arm_lo"], box["arm_hi"]
        q_cur = {sd: data.qpos[arm_qadr[sd]].copy() for sd in arm_ids}
        out = box["session"].solve(
            tframe if tframe is not None else box["RetargetFrame"](),
            engaged=tframe is not None,
            q_current_right=q_cur["right"], q_current_left=q_cur["left"])
        if (tframe is not None) != ctl["engaged"]:
            ctl["engaged"] = tframe is not None
            print("Teleop: " + ("ENGAGED" if ctl["engaged"]
                                else "tracking lost — holding last pose"))
        targets = {}
        if tframe is not None:
            for sd in ("right", "left"):
                goal = getattr(out, f"q_goal_{sd}", None)
                if goal is None:
                    if (sd, "none") not in ctl["warned"]:
                        ctl["warned"].add((sd, "none"))
                        print(f"Teleop WARNING: solve() gave no q_goal_{sd}")
                    continue
                goal = np.asarray(goal, dtype=float)
                if goal.shape != (7,) or not np.isfinite(goal).all() \
                        or np.abs(goal).max() > math.pi:
                    if (sd, "range") not in ctl["warned"]:
                        ctl["warned"].add((sd, "range"))
                        print(f"Teleop WARNING: q_goal_{sd} invalid or "
                              f"outside ±pi, frame ignored: {goal.round(2)}")
                    continue
                clipped = np.clip(goal, arm_lo[sd], arm_hi[sd])
                if (sd, "clip") not in ctl["warned"] and \
                        not np.allclose(clipped, goal):
                    ctl["warned"].add((sd, "clip"))
                    print(f"Teleop: q_goal_{sd} clipped to joint limits "
                          f"(first seen: {goal.round(2)})")
                cur_t = np.asarray(obs["applied"]["arm_targets"][sd], dtype=float)
                max_d = TELEOP_MAX_JOINT_VEL / 60.0
                targets[sd] = [float(v) for v in cur_t + np.clip(clipped - cur_t, -max_d, max_d)]
        return [{"mode": "arms", "arm_targets": targets}] if targets else []

    def status():
        return ("MANUAL" if not ctl["on"] else
                "TELEOP tracking" if ctl["engaged"] else
                "TELEOP no body, holding")

    return {"name": "teleop", "start": start, "step": step, "enable": lambda: _set(True), "disable": lambda: _set(False),
            "status": status, "state": ctl, "cleanup": lambda: box["source"].cleanup()}
